### ISSUE TITLE
Behaviour of user_can_only_view_guest_transfers_shared_with_them

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1000]
This was reported on the mailing list. I am duplicating here to allow interested parties to track it.

```
To be exact, when this option is turned off, and a user creates a guest voucher, who then creates a transfer that is not shared, this transfer:

1- Is visible in the mytransfers overview of the user who created the guest voucher
2- Causes email notifications to be sent to the user
```

**Comment by monkeyiq** [comment]
An update is available at https://github.com/filesender/filesender/pull/1001

**Comment by WebSpider** [comment]
This fix seems to be only in development and filesender-3. Will this be backported to filesender-2.x as well?

**Comment by monkeyiq** [comment]
The above update (1001) should be in 2.25 and later: https://github.com/filesender/filesender/releases/tag/master-filesender-2.25

If this is still not working as expected in 2.25 and over I will have another dig at it.

I was tempted to rename development to development2 but left development and master as the version2 trees for now to avoid everybody having to rename branches. In the future once FileSender 3.x is released and the 2.x series is more 'parked' I will likely rename these 2.x branches to development2 and master2 so that people do not accidentally use the 2.x series for a PR.
