### ISSUE TITLE
group guest vouchers

### ISSUE THREAD

**Issue by leifj** [filesender/filesender#1008]
It would be useful to have the ability for a group to download the result of a guest voucher upload - ie for a guest voucher to address a group of recipients.

**Comment by WebSpider** [comment]
So, you want a voucher to have one guest user, and multiple guest recipients? This is already possible!

\When you log in using the guest voucher, separate the email addresses using a comma ( , )
![image](https://user-images.githubusercontent.com/437323/117798157-1fc48500-b251-11eb-98d7-611bc938d8fe.png)

**Comment by WebSpider** [comment]
@leifj did this solve your issue? If it did, please feel free to close it :)
