### ISSUE TITLE
Not able to add a remote application, multiple missing entries in documentation 

### ISSUE THREAD

**Issue by vinnyalvs** [filesender/filesender#1040]
Hello,

I am not able to make API requests through` remote_application` mode. Probably is due to bad config options, the problem is the documentation is missing multiple parts in this specific topic. 

Maybe together we can understand the problem and I can update the documentation. 

I did the following, in config.php: 

I set: 

$config['auth_remote_application_enabled'] = true;

and

$config['remote_applications'] = array ('app_name' => 'app_secret', true, array( 'get' => TRUE, 'post' => TRUE));

Finally, I tested with the FilesenderRestClientExample but only got `auth_remote_unknown_application`

**Comment by monkeyiq** [comment]
There were a few things making this harder, certainly a documentation issue and probably also a CI issue where some form of remote application checks in CI would halp catch bit rot.

Firstly a grepping seemed to show that the `remote_applications` should be `auth_remote_applications` instead.

After a bunch of debug outputting and tinkering I arrived at the below config.php fragment that seems to work. The `appname` in the below is the remote_application name and all the information for that is in an array under the key. Without the `info` ACL the test example would fail with permission denied, which, while true, is a little confusing while trying to get an initial run going.

```
$config['auth_remote_application_enabled'] = true;
$config['auth_remote_applications'] = array (
    'appname' => array( 'secret' => 'appsecret', 'isAdmin' => true, 'acl' => array( 'get' => TRUE, 'post' => TRUE, 'info' => TRUE))
);
```

With the below I could run the following against my local instance.

```
$c = new FilesenderRestClient('https://localhost/filesender/rest.php', 'application', 'appname', 'appsecret');
```

**Comment by vinnyalvs** [comment]
Thank You. You helped me a lot. 

Just reinforcing: if someonte wants to make the endpoints `transfer` or `guest` available to the application, they need to set these specifics endpoints in the acl array:

```
$config['auth_remote_application_enabled'] = true;
$config['auth_remote_applications'] = array (
    'appname' => array( 'secret' => 'appsecret', 'isAdmin' => true, 'acl' => array( 'get' => TRUE, 'post' => TRUE, 'info' => TRUE, 'transfer' =>TRUE, 'guest' =>TRUE ))
); 
```

**Comment by vinnyalvs** [comment]
Since the docs has already been updated I am closing this issue.
