### ISSUE TITLE
JS Errors: quota + Invalid or unexpected token

### ISSUE THREAD

**Issue by pjc2000** [filesender/filesender#1058]
Hi all.

I have followed the install documentation for the V2 and it went good.

I have the (last) filesender installed and working and the simplesaml also working.

What I want to do is to use the filesender and the authentication with an user database. Simplesaml works well with the database and I can authenticate using the filesender. But I can't use the "Select files" nor the "Clear all" because they are like disabled. Nothing happens. Even the drag & drop does not work.

Using chrome I have the following:
- Uncaught SyntaxError: Invalid or unexpected token >>> filesender-config.js:67
- ui.js?v=a3165d40-1622663497:463 Uncaught TypeError: Cannot read property 'quota' of undefined

I think the first one is related to the option "max_transfer_files" and the second one with a "quota" (I don't know witch).

My "config.php" is as the following:

$config['site_url'] = 'https://repository.wakaru.eu/filesender';
$config['admin'] = 'admin';
$config['admin_email'] ='XXXX@wakaru.eu';
$config['email_reply_to'] ='no-reply@wakaru.eu';

$config["db_type"] ='pgsql';
$config['db_host'] ='127.0.0.1';
$config['db_database'] ='filesender';
$config['db_username'] ='filesender';
$config['db_password'] ='XXXXX';

$config['auth_sp_saml_simplesamlphp_url'] ='https://repository.wakaru.eu/simplesaml/';
$config['auth_sp_saml_simplesamlphp_location'] ='/opt/filesender/simplesaml/';

$config['auth_sp_saml_email_attribute'] = 'email';
$config['auth_sp_saml_uid_attribute'] = 'uid';
$config['auth_sp_saml_authentication_source'] = 'GAIA'; >>> my auth source

$config['terasender_enabled'] = true;          
$config['terasender_advanced'] = true;       
$config['terasender_worker_count'] = 5;     
$config['terasender_start_mode'] = 'single'; 

config['storage_type'] = 'filesystem';
$config['storage_filesystem_path'] = '/opt/filesender/filesender/files';

I don't know if it's a bug because I followed all "the red" parts of the configuration.

Thanks.

PJC

**Comment by monkeyiq** [comment]
The first issue might be also causing the second. So we should try to address the first one first. Assuming your site can be accessed using the URL `https://localhost/filesender/` then you could try loading the 
```
https://localhost/filesender/filesender-config.js.php
```
and see if that json page is well formed or stops abruptly at line 67 (which also may be the last line in the file).

**Comment by pjc2000** [comment]
Hi.

I did what you suggested and there is the output (something is wrong):

if (typeof window === 'undefined') {
	window = {};
}
if (!('filesender' in window)) window.filesender = {};

window.filesender.config = {
    log: true,
    
    site_name: 'FileSender',
    
    upload_chunk_size: 5242880,
    
    upload_display_bits_per_sec: false,

    max_transfer_size: 107374182400,
    max_transfer_files: 30,

    max_transfer_file_size: 0,
    max_transfer_encrypted_file_size: 0,

    ban_extension: 'exe,bat',
    extension_whitelist_regex: '^[a-zA-Z0-9]*$',
    
    max_transfer_recipients: 50,
    max_guest_recipients: 50,
    
    max_transfer_days_valid: 20,
    default_transfer_days_valid: 10,
    max_guest_days_valid: 20,
    default_guest_days_valid: 20,
    
    chunk_upload_security: 'key',
    
    encryption_enabled: '1',
    encryption_min_password_length: '0',
    encryption_generated_password_length: '0',
    upload_crypted_chunk_size: '5242912',
    crypto_iv_len: '16',
    crypto_crypt_name: 'AES-CBC',
    crypto_hash_name: 'SHA-256',

    terasender_enabled: true,
    terasender_advanced: true,
    terasender_worker_count: 5,
    terasender_start_mode: 'single',
    terasender_worker_file: 'lib/terasender/terasender_worker.js?v=a3165d40-1622674073',
    terasender_upload_endpoint: 'https://repository.wakaru.eu/filesender/rest.php/file/{file_id}/chunk/{offset}',
    terasender_worker_max_chunk_retries: 20,
    
    stalling_detection: false,

    max_legacy_file_size: 2146435072,
    legacy_upload_endpoint: 'https://repository.wakaru.eu/filesender/rest.php/file/{file_id}/whole',
    legacy_upload_progress_refresh_period: 5,
    
    valid_filename_regex: '^[ \\/\\p{L}\\p{N}_\\.,;:!@#$%^&*)(\\]\\[_-]+$',
    base_path: '/filesender/',
    support_email: '',
    autocomplete: {
        enabled:  false,
        min_characters: 3
    },
    message_can_not_contain_urls_regex: '',

    auditlog_lifetime: 31,
    
    logon_url: '<br />
<b>Warning</b>:  session_name(): Cannot change session name when headers already sent in <b>/opt/filesender/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php</b> on line <b>72</b><br />
<br />
<b>Warning</b>:  session_id(): Cannot change session id when headers already sent in <b>/opt/filesender/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php</b> on line <b>192</b><br />
<br />
<b>Warning</b>:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in <b>/opt/filesender/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php</b> on line <b>244</b><br />
<br />
<b>Warning</b>:  session_id(): Cannot change session id when headers already sent in <b>/opt/filesender/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php</b> on line <b>192</b><br />
<br />
<b>Fatal error</b>:  Uncaught SimpleSAML\Error\Exception: Disabling PHP option session.use_cookies failed. in /opt/filesender/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php:246
Stack trace:
#0 /opt/filesender/simplesaml/lib/SimpleSAML/Session.php(352): SimpleSAML\SessionHandlerPHP-&gt;loadSession('')
#1 /opt/filesender/simplesaml/lib/SimpleSAML/Session.php(268): SimpleSAML\Session::getSession()
#2 /opt/filesender/simplesaml/lib/SimpleSAML/Auth/Simple.php(51): SimpleSAML\Session::getSessionFromRequest()
#3 /opt/filesender/filesender/classes/auth/AuthSPSaml.class.php(231): SimpleSAML\Auth\Simple-&gt;__construct('GAIA')
#4 /opt/filesender/filesender/classes/auth/AuthSPSaml.class.php(164): AuthSPSaml::loadSimpleSAML()
#5 /opt/filesender/filesender/classes/auth/AuthSP.class.php(79): AuthSPSaml::logonURL(NULL)
#6 /opt/filesender/filesender/www/filesender-config.js.php(119): AuthSP::logonURL()
#7 {main}
  thrown in <b>/opt/filesender/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php</b> on line <b>246</b><br />

**Comment by monkeyiq** [comment]
It looks like it is trying to disable setting the saml cookie but ini_set is failing (maybe due to permissions).

You could try setting session.use_cookies = false in your php.ini so it doesn't have to change that. 

I am wondering why the SAML cookies are not being set properly though. If you do a web dev trace in your browser are you seeing any cookies coming back during the saml auth setup?

**Comment by WebSpider** [comment]
You can also set simplesamlphp to use a local database for sessions

**Comment by pjc2000** [comment]
Dear friends,

I solved my problem. It was syntax problem with my /etc/php.ini fiile.

Sorry...
