### ISSUE TITLE
security: allow a user to indicate the recipient must be logged in to download

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1066]
This assumes that a user knows they are sending to somebody on the same service. This might not be used all the time but it might be useful to limit the availability of transfers. 

There are a few options for this, allowing anyone who can log in to the system or if not using get a link allow only people who can log in using the email addresses you are sending the link to. I would not check that those users exist to avoid leaking emails to users but if people are closely collaborating they likely know what the right addresses are for this context. It may be an idea to default to the tighter security setup for email addresses. If you nominate email addresses then you might want only those people to access the files.

It could also be handy in a guest case. If send only to me is active then one would need to authenticate to the system as the person who invited the guest in order to download. So this protects if a link to the download page is accidentally shared.

**Comment by guidoaben** [comment]
that's related to #914 I think, with #914 being the broader case and #1066 the narrower case.

**Comment by monkeyiq** [comment]
I think at least having this narrower case working is a good start :)
