### ISSUE TITLE
Consistency: UX is different with/without streamsaver

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1076]
While preparing an upgrade from 2.18 to 2.25 we found that UX has changed.

With streamsaver enabled, and downloading chunks, users do no longer see the percentage of the download complete.
In 2.18 and earlier, users saw a percentage number of the download, indicating how far the download is.
In 2.25 with streamsaver enabled, the users see the chunk that is downloading, the total number of chunks, and the % of the chunk that is completed.

It would seem users are less interested in the amount of chunks (which is something they dont know anyway), and the completion of a chunk, and more in the overall completion of the download.

Are there some settings that I've missed, or is the UX inconsistent at this point?

**Comment by monkeyiq** [comment]
There does seem to be a change there. 

The old percentage was misleading as the entire file was downloaded before it was decrypted leading to large waits without any UI updates for larger files in 2.18.

**Comment by monkeyiq** [comment]
update here https://github.com/filesender/filesender/pull/1077

**Comment by monkeyiq** [comment]
This will be available in the next release
