### ISSUE TITLE
Add Brazilian Portuguese as an Official Language,

### ISSUE THREAD

**Issue by vinnyalvs** [filesender/filesender#1078]
Hello

Following the project guidelines, I was able to translate the Filesender in poeditor. https://poeditor.com/join/project/RqXr9WBJwU
As you can see the (BR) Portuguese is now 100% translated. 

I hope in the next update pt-BR could be incorporated as an Official Language.

**Comment by monkeyiq** [comment]
This is great news! I have created and merged https://github.com/filesender/filesender/pull/1080 above to bring this into the repository. The automatic update scripts have been updated so Brazilian Portuguese will continue to be updated as things are refreshed in the future. This translation will be included in the next release!

I have added the name "Brazilian Portuguese" in the drop down for this translation. Please let me know if there is a more expected description for the translation that would improve the user interface.
https://github.com/filesender/filesender/blob/dd079410d88d923556ca14a85d7a3751f4367085/language/locale.php#L68

**Comment by vinnyalvs** [comment]
Thank you! 

@monkeyiq I think in the locale.php it should be 'Português Brasileiro'.

**Comment by monkeyiq** [comment]
This should be updated in https://github.com/filesender/filesender/pull/1083 thanks for the info. 

Once I do a release of the 2.x series I will also merge these changes into the bootstrap (3.x development series).

**Comment by vinnyalvs** [comment]
Ok. Thanks for the update. 

Since the subject of the issue is done i am now closing the issue
