### ISSUE TITLE
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'"

### ISSUE THREAD

**Issue by dxdemetriou** [filesender/filesender#1088]
This is after updating from 2.25 to 2.26, there are a lot like this errors:
Chart.bundle.min.js:7 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-z7zcnw/4WalZqx+PrNaRnoeLz/G9WXuFqV1WCJ129sg='), or a nonce ('nonce-...') is required to enable inline execution.

Another, not sure if related, it's on "File Encryption" when a password is generated it says that's not too long, and the same password when copied and pasted it's green.

**Comment by monkeyiq** [comment]
Hmm, I knew I would forget to enable something during final testing. The chartjs CSP issue should be fixed with https://github.com/filesender/filesender/pull/1089

**Comment by monkeyiq** [comment]
The https://github.com/filesender/filesender/pull/1090 adds better handling of these messages when using generated passwords. There was also a case where if the mandatory user supplied password length was longer than the generated password length the messages were not shown when the user moved from generated password to not generated. I only found that by setting the needed user entered password length to 50 or so which is probably longer than sites were using.

You should only be able to paste a password (or explicitly alter it) if "Generate password" is not selected.

**Comment by dxdemetriou** [comment]
Another one on 2.26 release is the missing of the contents in the "About" and "Help" pages (it shows an empty non expanded box). There is no any error in the browser's development move. If you see the source of those page the content exists.

**Comment by monkeyiq** [comment]
I'm not sure why they were in the page footer too but it seems more reasonable after https://github.com/filesender/filesender/pull/1095 is merged.

**Comment by monkeyiq** [comment]
Seemed like an idea to push these into a new release https://github.com/filesender/filesender/releases/tag/master-filesender-2.27

**Comment by dxdemetriou** [comment]
Very fast, thanks :)
I tried the 2.27 release and everything works as expected now.

About the strict checks on the encryption not everything is hidded when "File Encryption" checkbox is unticked, and I have tried this fix (I don't know if it's the correct way as I'm not very good in php yet):
www/js/upload_page.js : line1616
`
        if( filesender.ui.transfer.encryption ) {
            filesender.ui.files.checkEncryptionPassword(filesender.ui.nodes.encryption.password, true );
        } else {
            var msg = $('#encryption_password_container_too_short_message');
            msg.hide();
            var msg2 = $('#encryption_password_container_must_have_numbers_message');
            msg2.hide();
            var msg3 = $('#encryption_password_container_must_have_upper_and_lower_case_message');
            msg3.hide();
            var msg4 = $('#encryption_password_container_must_have_special_characters_message');
            msg4.hide();
            var msg5 = $('#encryption_password_container_can_have_text_only_min_password_length_message');
            msg5.hide();
        }
`

**Comment by monkeyiq** [comment]
I added a class to various password validation items in the HTML template:
https://github.com/filesender/filesender/blob/031aa946b49453d307d58e9cb135743f6a5fe97b/templates/upload_page.php#L210

The javascript in upload_page.js uses that class to hide all the elements with it:
https://github.com/filesender/filesender/blob/031aa946b49453d307d58e9cb135743f6a5fe97b/www/js/upload_page.js#L557

Are there specific items that are not hidden with you select file encryption?

**Comment by dxdemetriou** [comment]
> I added a class to various password validation items in the HTML template:
> https://github.com/filesender/filesender/blob/031aa946b49453d307d58e9cb135743f6a5fe97b/templates/upload_page.php#L210
> 
> The javascript in upload_page.js uses that class to hide all the elements with it:
> https://github.com/filesender/filesender/blob/031aa946b49453d307d58e9cb135743f6a5fe97b/www/js/upload_page.js#L557
> 
> Are there specific items that are not hidden with you select file encryption?

It hides only the "Sorry, your password is too short"

The remaining lines are:
- Password must contain at least one number (0,1,3...9)
- Password must contain UPPER and lower case characters
- Password must contain at least one special character such as !@#$%^&*()<>
- If your password has more than 40 characters without significant repetition then there are fewer restrictions on the contents of your password.

**Comment by monkeyiq** [comment]
https://github.com/filesender/filesender/pull/1103 should fix things. I am not sure why I went back from hide() to using that other function.

**Comment by monkeyiq** [comment]
Digging into this a little more I had made the presumption that the file encryption checkbox and generate password combination worked the same before you added any files. It seems the previous code was ok if you had not added files (how I tested) but if you added files to upload then the generate password didn't hide things. I'm not sure why, but the new code using hide() works in both cases. I turned on needing numbers, upper/lower and special chars for testing. I have just tested the code for 2.28 and hopefully this will close the issue.

**Comment by dxdemetriou** [comment]
I tried the 2.28 and tried to compare with older versions but it's still the same. The only way that worked for me was this:
https://github.com/filesender/filesender/commit/29271682456bd414b2bb901f52151df6861f3fea
I think that sliding function works only when changing the password but not when the checkbox is unchecked.

**Comment by monkeyiq** [comment]
I thought I would double check that you have the updated templates/upload_page.php file in place with the passwordvalidation classes applied https://github.com/filesender/filesender/blob/427dd82df7b18a17c635ac260d788d2eb48fae0f/templates/upload_page.php#L210 this is likely not the issue but might be handy to mention.

So when you load the upload page, add a file, then select "Generate password" and not all the red lines for password length and numbers being required disappear there in 2.28?

**Comment by monkeyiq** [comment]
I am mainly testing these in Firefox & Chrome.

**Comment by dxdemetriou** [comment]
No, when writing/generated an encrypted password everything works as expected. That I said, let's say somebody checked the "File Encryption" but changed their mind and unchecked it, the only text is hiding is the "Sorry, your password is too short" (and the other remaining texts could make some confusion to the users). Actually, when encryption_enabled is false everything related should be hidden. I tried it both in Firefox & Chrome.

**Comment by monkeyiq** [comment]
Ah I see! I was focused on the Generate password toggle. Hopefully https://github.com/filesender/filesender/pull/1105 clears things up...

**Comment by dxdemetriou** [comment]
Yes, that fixed it, thanks.

**Comment by monkeyiq** [comment]
Sorry it took a bit of back and forth :/
