### ISSUE TITLE
Git branching model?

### ISSUE THREAD

**Issue by lifenautjoe** [filesender/filesender#109]
Have you guys considered using one?
It would make contribution and general understatement of the ongoing developments way easier and thus attract contributors.

Of course I'll recommend [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) as the industry de facto. 

This issue is raised over me confidently going to the master branch and assuming it was in perfect condition to later find out it's undergoing major undocumented changes.

**Comment by jornane** [comment]
> This issue is raised over me confidently going to the master branch and assuming it was in perfect condition to later find out it's undergoing major undocumented changes.

Can you elaborate?

**Comment by madsi1m** [comment]
master is updated mostly by pull requests

**Comment by lifenautjoe** [comment]
Coming back from holidays just now, sorry for the delay. 
I meant as in having a master branch where code is in a stable state aka released code and keep all the ongoing development works in develop. Makes it easier to contribute as I can just branch out from master and know that no changes I am not aware of can interfere with what I am doing. Same thing can be done from branching out from a tagged release commit but it's just messy. 

Reason I'm mentioning this is that we are considering using Filesender as a file transfer solution and we are very concerned over having a good collaboration strategy with the project we choose to employ.

**Comment by madsi1m** [comment]
Isn't this how we already do things?

Create a branch, do your mods and create a pull request.

Master branch is always good. Releases are a subset of master branch commits.

Cheers
Michael

On 29 Aug 2017, at 21:23, Joel Hernández <notifications@github.com<mailto:notifications@github.com>> wrote:


Coming back from holidays just now, sorry for the delay.
I meant as in having a master branch where code is in a stable state aka released code and keep all the ongoing development works in develop. Makes it easier to contribute as I can just branch out from master and know that no changes I am not aware of can interfere with what I am doing. Same thing can be done from branching out from a tagged release commit but it's just messy.

Reason I'm mentioning this is that we are considering using Filesender as a file transfer solution and we are very concerned over having a good collaboration strategy with the project we choose to employ.

**Comment by lifenautjoe** [comment]
Not quite, I meant having a develop branch where people branch from, open a PR to develop, merge to develop and once a set of features are done (In this example all the features required for version 2.0 for example) create a release branch from develop which is then merged to master. This merge usually accompanied with all required documentation, bug fixes and breaking changes. 

I am specifically talking about the git-flow branching model which is explained [here](http://nvie.com/posts/a-successful-git-branching-model/). 

Cheers,
Joel.

**Comment by monkeyiq** [comment]
This might be interesting to consider post 2.0 release. Though I think perhaps the number of contributions for this project and rate of change might just make it simpler to continue to work on master.

Otherwise there is an effort to back port patches that are needed from the dev to a 2.0.1 type stable branch. Each release will be git tagged so folks could cherry pick updates from master to a branch from the release tag if desired.

**Comment by monkeyiq** [comment]
The FileSender board has decided that all PRs are now against development. At release time the changes between the last release and development are merged into master to form the new release.
