### ISSUE TITLE
"include me as a recipient" can't be overwritten

### ISSUE THREAD

**Issue by zivel** [filesender/filesender#1110]
On the latest Bootstrap Branch (2.27) when you change the "include me as a recipient" on the upload page, it get's ignored. 
It stores in the DB whatever is set by default.

I was trying to debug but it's kind of hard to figure out what is going on, when you press upload and the whole terrasender thing starts... so if anybody has some pointers where to look, I'd be glad to invesigate.

**Comment by monkeyiq** [comment]
The short answer is that https://github.com/filesender/filesender/pull/1111 hopefully fixes this issue.

The checkbox was moved and the selectors in the javascript were no longer finding that add me checkbox to add to the list of elements to send during transfer creation.

As far as the nuts and bolts go for those with an interest, the upload_page will call filesender.ui.startUpload() and that will eventually call transfer.start(). Inside transfer.start it calls filesender.client.postTransfer() which will do an HTTP POST to create the transfer. That HTTP POST is the call that will set the options for the transfer. The terasender code is for sending the bulk of the actual file content and one might ignore it during initial investigations for the case of metadata setting. One potential caveat to that is metadata specific to encrypted files.

https://github.com/filesender/filesender/blob/ed193a2adfe2e82fa0f822c0e5a74a61a91538c3/www/js/transfer.js#L1209

It can be illuminating to console.log the transfer.options at filesender.client.postTransfer() time just to double check that it is what is expected.

**Comment by zivel** [comment]
Thank you! It works like a charm!
