### ISSUE TITLE
Disable guest users/system/tab

### ISSUE THREAD

**Issue by justchris1** [filesender/filesender#1123]
I have reviewed the documentation, but can't find a setting to disable the 'guest' system entirely.  Since all of our users are authenticated, it would be desirable to entirely disable this function.

**Comment by monkeyiq** [comment]
I don't think there is currently an option to disable guests. I also think one should be able to disable (and not present) this option.

**Comment by monkeyiq** [comment]
Since this has been merged and independently tested and is quite old now I am closing the issue.
