### ISSUE TITLE
Stall warning on large files causing failed uploads on 2.0beta1.

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#113]
This bug was reported on the mailing list.

During an upload, despite the fact that I'll be getting good speeds, I'll get the following message.

"Upload seems to be stalled (way slower than expected), do you want to try restarting it or stop it ?"

The upload still continues in the background. I can choose ignore and it will continue, but often once then upload reached 100% it still  continues to uploads. Most recent test showed me uploading 10GB of a 6GB file.

Turning off terasender stops the issue. ( with performance drop). But more accurately, leaving terasender on and turning off stall detection, obviously stops the alert, but also seems to stop the sanity check entries in the logs.

To disable stall detection:
$config['stalling_detection'] = false;

**Comment by madsi1m** [comment]
I've seen this on an older commit as well. And disabling stall detection did fix it. I re-enabled it on ours and we no longer have the issue. It could be a timing, with terrasender not all chunks respond in the order they were uploaded, but haven't done any digging (yet)

**Comment by monkeyiq** [comment]
There are some assumptions in the old detection code which have been updated in https://github.com/filesender/filesender/pull/209 which should lead to less false positives for stall detection.

**Comment by jornane** [comment]
> The upload still continues in the background. I can choose ignore and it will continue, **but often once then upload reached 100% it still continues to uploads.** Most recent test showed me uploading 10GB of a 6GB file.

This issue is not addressed in #209.

**Comment by WebSpider** [comment]
@monkeyiq it would seem this issue is no longer valid, at least im not seeing incorrect stall reports in our production environment anymore

**Comment by monkeyiq** [comment]
Thanks for the update! It is very hard to trigger such stalls in local testing.

**Comment by WebSpider** [comment]
Relabeling so we can solve this (or determine it is solved) before 3.0 release

**Comment by WebSpider** [comment]
Not seen any reports about stalling issues for over a year.
