### ISSUE TITLE
Site_url setting not working behind reverse proxy

### ISSUE THREAD

**Issue by ekrister** [filesender/filesender#1138]
Hi, 

I'm trying to get filesender running behind a basic apache reverse proxy, expecting being able to set the external url with the 'site_url'-setting. Instead, as soon as I reach the front page, filesender redirects me to the local url of the server instead. It looks like it just ignores the domain part of the setting. 

Is there something I am missing? 

In comparison, the 'baseurlpath'-setting in simplesaml.php seems to work just as expected.

**Comment by ekrister** [comment]
Found the problem: the option "force_ssl" which defaults to "true" and the function "forceHTTPS" always redirects to the local address insted of reading it from the "site_url". Setting "force_ssl" to "false" allowed me to do the SSL on the proxy server instead.

**Comment by vinnyalvs** [comment]
@ekrister  Since this is a problem with configuration (which you already solved) and not a bug or new feature I think you may close the issue. 

What do you think?

**Comment by ekrister** [comment]
Yeah, there were other issues too that I ran into, when trying to run this through a reverse proxy, but I don't know if this is something that you want to support in filesender and therefore of any interest to mention here.

So yeah, I will close this issue now, thanks.

**Comment by vinnyalvs** [comment]
@ekrister the best place to ask stuff and get help is the mailing list, other people could have the same problems as you
https://sympa.uninett.no/lists/filesender.org/info/filesender-dev
