### ISSUE TITLE
Feature request: show remaining time in the upload dialog

### ISSUE THREAD

**Issue by zivel** [filesender/filesender#1146]
Hi there

We had a request from a user who ask, if it would be possible to show an estimate remaining time of an upload based on the current upload speed and the file/transfer size. 
It would help him to plan his work processes.

Thank you
- Renato

**Comment by monkeyiq** [comment]
I like this idea. I think it might be interesting to also include some sort of indication of how much the speed is varying so that the quality of the estimate could be known.

**Comment by monkeyiq** [comment]
I have created a PR https://github.com/filesender/filesender/issues/1146 against development and will port that over to development3 when updates are brought in.

**Comment by monkeyiq** [comment]
The PR is https://github.com/filesender/filesender/pull/1178

**Comment by monkeyiq** [comment]
This will be ported over to development3 for the next 3.x alpha release.

**Comment by monkeyiq** [comment]
Since this was merged over 6 months ago I am closing the issue here. If there are issues with the ETA feature then please reopen or create a new issue. Thank you for suggesting this feature.
