### ISSUE TITLE
Bug: call to non-existing functions during install/upgrade

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1182]
During install and upgrade, calls to non-existing functions are being made, in fact blocking installs and upgrades.
I created a pull request to fix this, see https://github.com/filesender/filesender/pull/1181

**Comment by monkeyiq** [comment]
As a fix was merged in Jan and no additional feedback has occurred I am closing the issue. If there are more or new dangling references please either reopen or create a new issue.
