### ISSUE TITLE
Link to documentation results in a 404 not found

### ISSUE THREAD

**Issue by hvwees** [filesender/filesender#1183]
The link to the documenation: http://docs.filesender.org/v2.0/install/ results in a 404 error.

Where can the documentation be found?

**Comment by thijskh** [comment]
https://docs.filesender.org/filesender/v2.0/install/

**Comment by hvwees** [comment]
Link should be updated on the release page https://github.com/filesender/filesender/releases

**Comment by monkeyiq** [comment]
Thanks! I have updated the release notes for the 2.30 and latest 3.x alpha and recorded that update as Erratum.

I have a governance issue open about the /filesender/ prefix being needed https://github.com/filesender/governance/issues/21
