### ISSUE TITLE
Help: Somewhere in my setup is forcing HTTPS and I'm unable to load FileSender instance

### ISSUE THREAD

**Issue by WhatIsWilsonDoin** [filesender/filesender#1206]
Hi,

I've been following this FileSender [install guide](https://docs.filesender.org/filesender/v2.0/install/) but I'm stuck on step 12 which is to "Visit the URL to your FileSender instance". I keep getting ERR_CONNECTION_TIMED_OUT in my browser with the message "10.10.0.150 took too long to respond". I also realize that I'm getting pushed to HTTPS every time for some reason, but I can't find where in my setup it is set to do so. And I don't have SSL set up at all right now because this is just a testing environment. 

Step 5 of this guide is to modify the NGINX config files. Before I completed that step, I was able to load a basic "Hello World!" page as well as my phpinfo(); page, so I know my NGINX isn't completely wrong. Does anyone have an idea where I'm going wrong? I appreciate any advice. 

I'm copying in most of my nginx.conf, filesender site file, and my filesender php config file. If there are any other files you or someone else might want to see to give me a hand, just let me know. 

Thanks!

**OS**: Ubuntu 20.0.4.3 LTS
**PHP version**: PHP 7.4.3 (cli) (built: Nov 25 2021 23:16:22) ( NTS )
**System Info (uname -a)**: Linux ubuntu2004 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
**Database**: mariadb  Ver 15.1 Distrib 10.6.5-MariaDB

### /etc/nginx/nginx.conf
```
user www-data;
worker_processes 4;
pid /run/nginx.pid;
#include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 1024;
	use epoll;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	#ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	#ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
        gzip_disable "MSIE [1-6]\.(?!.*SV1)";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
```

### /etc/nginx/sites-available/filesender_domain site file
```
server {
	listen 80;
	add_header X-Frame-Options sameorigin always;
        client_body_buffer_size 256k;
        client_max_body_size 32m;

	server_name 10.10.0.150;

	root /opt/filesender/filesender/www;
	index index.php;

location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
    }

        location / {
            try_files $uri $uri/ /index.php?args;
        }

        location ^~ /saml {
            alias /opt/filesender/simplesaml/www;
            location ~ ^(?<prefix>/saml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
                include fastcgi_params;
                fastcgi_pass  localhost:9090;
                fastcgi_param SCRIPT_FILENAME $document_root$phpfile;
                fastcgi_param PATH_INFO       $pathinfo if_not_empty;
            }
        }

        location ~* \.(ico|docx|doc|xls|xlsx|rar|zip|jpg|jpeg|txt|xml|pdf|gif|png|css|js)$ {
            root   /opt/filesender/filesender/www/;
        }
}
```

### /opt/filesender/filesender/config/config.php
```
$config['site_url'] = 'http://10.10.0.150/filesender';                // String, URL of the application
//
$config['admin'] = '';            // String, UID's (from  $config['saml_uid_attribute'])
                                    // that have Administrator permissions

$config['admin_email'] ='';       // String, email  address(es, separated by ,)
                                    // to receive administrative messages (low disk  space warning)

$config['email_reply_to'] ='';    // String, default no-reply email  address
$config['force_SSL'] = false;

$config['auth_sp_saml_simplesamlphp_url'] ='http://127.0.0.1/simplesaml/';     // Url of simplesamlphp
$config['auth_sp_saml_simplesamlphp_location'] ='/opt/filesender/filesender/simplesaml/';   // Location of s>
```

**Comment by monkeyiq** [comment]
Could you please try setting force_ssl in your filesender/config/config.php using all lower case? 

```
$config['force_ssl'] = false;
```

**Comment by WebSpider** [comment]
@WhatIsWilsonDoin did this solve the issue for you?

**Comment by monkeyiq** [comment]
Please feel free to reopen the issue if it is still unresolved. As this has not been confirmed or commended on for about 6 months I think I will close it as resolved unless reopened.
