### ISSUE TITLE
Incorrect password not showing

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1211]
We've gotten some feedback by our users that sometimes encrypted transfers are failing. It turns out that sometimes users are not correctly informed of incorrect passwords.

This is reproducable in our installs by:
1) Running filesender 2.30 or 2.31 (not tested on other versions)
2) Enable terasender and streamsaver
3) Making an encrypted transfer with multiple files in it
4) Downloading the transfer as a zip, but supply an incorrect password using the download.php entry

Result:
1) The user does not receive a notification the password was incorrect, download begins
2) A (nearly) empty zipfile is downloaded, giving the impression to the user the download has completed
3) The zipfile does not contain the contents expected

Checked on: 
Chromium Version 97.0.4692.71 (Official Build) snap (64-bit)
Firefox 96.0 (64-bit)

**Comment by monkeyiq** [comment]
I am testing for this with `encryption_key_version_new_files=0`. If one is using a value of `3` then FileSender will use GCM and also AEAD to halt at the very first chunk of download if the password is wrong.

I have two files, one about 1mb and one 27mb which I am testing with in a single transfer. Maybe not large enough. So I also tried a 170mb and 434mb file in combination in a single upload. I get the incorrect password dialog fairly soon after attempting to download these and also `Incorrect Password` shown for the progress of the first file in the list.

The nearly empty zip file you are seeing hints to me that perhaps FileSender was trying to stream the download but halted at around the same time as it does here though is not showing the error message in the browser? The web console shows me the following toward the end when the bad password dialog is shown here.

```
decryptBlob() about to really decrypt() nonStreamed false
crypto_app.js:14 decrypt(e) nonStreamed false
crypto_app.js:14 DOMException
crypto_app.js:14 decrypt(e5) nonStreamed false
crypto_app.js:14 decrypt(e5) msg 
crypto_app.js:14 decryptDownloadToBlobSink() explicit error OperationError
crypto_app.js:14 DOMException
ui.js:51 [07:48:52] [terasender driver] Stopping workers
crypto_app.js:14 zip64 sink error()
```


Chrome 97.0.4692.71 (Official Build) (64-bit)

**Comment by monkeyiq** [comment]
There is always the unfortunate possibilities that the issue is only triggered for some config.php settings. Hopefully I can get it to happen locally.

**Comment by WebSpider** [comment]
We are using key version 3 for new files, I will post more related config settings in a few hours

**Comment by monkeyiq** [comment]
Feel free to email me config.php stuff (after removing passwords and other stuff).

**Comment by monkeyiq** [comment]
This is a bit of a long shot as the code was added only in release 2.31. Could you please try commenting out the line cited below which was added for TeraReceiver mode. I notice when looking over your and my download console text that there is a difference there which would cause this assignment to run only there.

https://github.com/filesender/filesender/blob/faeb7fd4f2b6da413f32029d40cbcc6144c5f298/www/js/crypter/crypto_app.js#L1101

If that has the desired outcome then I can try to reason why it is different between here and there.. (and possibly other installations).

**Comment by WebSpider** [comment]
We are having trouble reproducing this after recent browser updates.
