### ISSUE TITLE
Missing translation for accepted site-wide aup

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1216]
When accepting a site-wide AUP, there is a missing translation in all languages:

https://github.com/filesender/filesender/blob/0403101f4620b6f8dfd04a7649cd55103e7e3ac8/www/js/service_aup_page.js#L46

**Comment by monkeyiq** [comment]
I have added a prefix to the terms_accepted and it is now on poeditor with English + en_au translations. I will do a batch import of translations from poeditor before the next release.
