### ISSUE TITLE
Download notifications and ZIP downloads

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1220]
With streamsaver and terasender enabled on filesender 2.31, a download notification is sent for every file downloaded, when the user selects "Download as ZIP", instead of once per download.

For transfers with hundreds of files, this turns Filesender into a spambot.

**Comment by monkeyiq** [comment]
This is an interesting issue. The "Download as ZIP" is mostly performed client side. As far as the server sees at the moment it can only notice that the encrypted content of the files is requested. This is similar to if the user sequentially clicks to download each file.

I am thinking that perhaps some form of intent signalling from the download page would be needed so a client can register download events on the many files as a single action and result in a single email with the entire operation as contents.

**Comment by WebSpider** [comment]
This is inconsistent with the zip/tar download when downloading non-encrypted non-streamsaver: That's done server side, as far as I can see, and in any case, not generating all the notifications.

**Comment by monkeyiq** [comment]
I am working on a fix for this.
