### ISSUE TITLE
Feature request: Store and reproduce folder layout

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1223]
When uploading a complete folder, using either encrypted or unencrypted transfer options, as an enduser I would like to be able to ensure the folder structure is retained when the transfer is downloaded as a .zip file.

**Comment by monkeyiq** [comment]
This seems to be done at the upload page. 

If I click to send an entire directory then the path information is lost. The files list does not show paths and the resulting download of tar/zip doesn't have then either.

If I drag and drop a directory to the "Drag or choose file(s) to send" part of the web page then the files to upload list shows directory paths intact and the resulting transfer can be downloaded with paths included.

I will take a look at the upload page javascript as it is a real shame that this difference exists.

**Comment by monkeyiq** [comment]
I just tested https://github.com/filesender/filesender/pull/1224 with encryption using "select a directory" and the path information was retained. I am still in the process of rebuilding a Edge-non-chromium env for testing that browser.

**Comment by WebSpider** [comment]
We will be testing this PR this week. Thanks for the quick response!

**Comment by WebSpider** [comment]
@monkeyiq unfortunately this breaks sending single files with a valid filename

**Comment by monkeyiq** [comment]
Update added, sorry about that :/

**Comment by monkeyiq** [comment]
I have now merged https://github.com/filesender/filesender/pull/1224 bringing the subdirectory name preservation into what will be the next release.

**Comment by WebSpider** [comment]
We will be testing this as we prepare for 2.36 release

**Comment by WebSpider** [comment]
This is fixed in 2.36, thanks a lot!
