### ISSUE TITLE
Filesender blog

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1230]
The FileSender blog is referenced in https://github.com/filesender/filesender/blob/a58d832caed622d236c7fe6e174fbd430af0d7a7/README.md?plain=1#L12, however when clicking, you get to an empty non-HTTPS website.

If there is no blog, there is no use in mentioning it .. if there is one, it is not showing :)

**Comment by peter-** [comment]
References to *that* blog (there's also [another one](https://filesender.wordpress.com/) that still works but is outdated) are fixed in #1262 (if merged).

**Comment by monkeyiq** [comment]
I have merged https://github.com/filesender/filesender/pull/1262
