### ISSUE TITLE
filesender3: CSP style-src "strict" blocks elements from templates

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1244]
When running filesender3 with CSP attribute "style-src: self", as per the value for `use_strict_csp` [here](https://github.com/filesender/filesender/blob/716aedbedadaf243b5cd6cc12240918a0520c871/classes/utils/Security.class.php#L78), a few elements become blocked.

These elements are (at least):
https://github.com/filesender/filesender/blob/716aedbedadaf243b5cd6cc12240918a0520c871/templates/upload_page.php#L335
https://github.com/filesender/filesender/blob/716aedbedadaf243b5cd6cc12240918a0520c871/templates/upload_page.php#L509
https://github.com/filesender/filesender/blob/716aedbedadaf243b5cd6cc12240918a0520c871/templates/upload_page.php#L510
https://github.com/filesender/filesender/blob/716aedbedadaf243b5cd6cc12240918a0520c871/templates/guests_page.php#L156

I suppose, the best solution here is to use elements of a stylesheet instead of inline styles

Additionally, language strings sometimes contain values that violate this CSP, which I will raise a seperate issue for.

**Comment by monkeyiq** [comment]
From a quick grep in language it seems the help and about text both have inline styles (for Dutch).

**Comment by monkeyiq** [comment]
It is probably a good idea to close this and perhaps create related issues for other spots that might need attention for use_strict_csp as needed.
