### ISSUE TITLE
Per chunk digests for non-encrypted uploads

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1259]
The integrity of encrypted transfers is protected. It would be nice to calculate and store a digest (sha256 for example) for chunks for non encrypted transfers to allow verification of data. This would help detect faults in storage by verifying that the data downloaded exactly matches the data that was uploaded either at the time of download or optionally later.

**Comment by monkeyiq** [comment]
As a follow up for this, if the digests could be downloaded then the FileSender code could be used, possibly at a much later stage, to reverify a download. This feature would allow a user to verify a download is still as it was perhaps years later.

**Comment by monkeyiq** [comment]
I had put this before the FileSender board in 2022.

**Comment by WebSpider** [comment]
The missing digests actually hinder in tracking down complex integrity issues, as I'm finding out on a regular basis :)

**Comment by monkeyiq** [comment]
Are the integrity issues that to do with storage (hardware) or something that FileSender is getting wrong?
