### ISSUE TITLE
FileSender, I have a clean set-up, but I have a white page coming up

### ISSUE THREAD

**Issue by baybarshan008** [filesender/filesender#1299]
FileSender, I have a clean set-up, but I have a white page coming up. Can you help me do what?

https://www.hizliresim.com/8tvcc7f

![2022-07-22 09_53_35-Ubuntu 64-bit - VMware Workstation](https://user-images.githubusercontent.com/98581839/180381463-12dd9ae6-fc99-447b-a56f-b5228de1c33e.png)

When I review the log, the following terminal printout comes in, and I don't understand why the project didn't open.
root@toor:/opt/filesender/filesender/log# cat filesender_2022-07-22_05h.log
[2022-07-22 05:37:57] [cron:info] Cron started

The technologies I use in the project.
- Ubuntu 22.04
- Apache
- Postgresql

**Comment by monkeyiq** [comment]
Please check that the JSON file generated from your config parses alright. The end of the file is normally where the issue presents itself, for example with a string that does not close or an error message. This can be seen in the following URL

```
https://192.168.8.135/filesender/filesender-config.js.php
```

If that looks ok, is there anything in the browser web console that might be a clue.

**Comment by baybarshan008** [comment]
sorry, no error message on the scanner. i've added a screenshot of the config file. Can you see the image of the Config file? Is there a mistake in this section? In addition, what should I do to troubleshoot the problem?

If the app can work, we'll apply myself to our architecture. In this case, we offered an idea to support the open source developer instead of purchasing another application license, but I get an error running the application. i have to be able to bring it to life in 2 days.

![2022-07-25 08_52_50-Ubuntu 64-bit - VMware Workstation](https://user-images.githubusercontent.com/98581839/180708469-536f51f6-8c8a-4daf-b098-e3923480f07d.png)

![2022-07-25 08_48_18-Ubuntu 64-bit - VMware Workstation](https://user-images.githubusercontent.com/98581839/180708475-c9d0272e-9211-4c44-bfed-7ae5083e4492.png)

**Comment by monkeyiq** [comment]
The filesender-config.js.php should show a whole page and start out with something like:

```
if (typeof window === 'undefined') {
	window = {};
}
if (!('filesender' in window)) window.filesender = {};

window.filesender.config = {
    log: true,
    
    site_name: 'FileSender',
   ... many more lines ...
```

You could try editing your config.php checking for missing end quotes etc. Though maybe if there is nothing on the  filesender-config.js.php page then maybe FileSender is not getting that far. In that case I might suggest some debugging in the main site page to see where things are stopping.

**Comment by baybarshan008** [comment]
the codes for page filesender-config.js.php are in the image.
![2022-07-26 13_24_04-Ubuntu 64-bit - VMware Workstation](https://user-images.githubusercontent.com/98581839/180985459-200011ea-3d65-4603-ad23-901e32703f12.png)
![2022-07-26 13_23_41-Ubuntu 64-bit - VMware Workstation](https://user-images.githubusercontent.com/98581839/180985465-b6a4ca42-bc4a-4c07-a046-b5aa91214cbc.png)

Can you help me enable debugging on the homepage?
![2022-07-26 13_27_14-Ubuntu 64-bit - VMware Workstation](https://user-images.githubusercontent.com/98581839/180985752-ec9d642f-cf11-4fb5-a351-85bf95c9fedb.png)

**Comment by monkeyiq** [comment]
If you do not have a DNS entry you could use either the local ip address of the server or something that client machines can resolve (/etc/hosts entry) to the server. For example in config.php:
```
$config['site_url'] = 'https://192.1.1.1/filesender';
```

I don't think recent releases have the gpc call in them:
https://github.com/filesender/filesender/blob/development/includes/init/init_web.php

Which version are you trying to bring up?

**Comment by baybarshan008** [comment]
I use PHP 8.0. I set it up because it's my current version. Which version of PHP should I use for project support?
@monkeyiq

**Comment by WebSpider** [comment]
I know several working installs with 7.4
Havent seen any reports of 8.0 working :)

**Comment by WebSpider** [comment]
@baybarshan008 are you still experiencing this issue?

**Comment by WebSpider** [comment]
Closing this issue as it seems stale. If it is not, feel free to reopen. If you are experiencing a similar issue, feel free to refer to this one for context.
