### ISSUE TITLE
REST Client: Add transfer creation test to CI

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#130]
The CI does not currently include tests for the REST client. This makes it easier to break without detection by the development team.

Cases;

* Auth with bad login
* Success login
* Creating a transfer with a local file
* Perhaps listing or other REST API use

**Comment by WebSpider** [comment]
Is this issue still relevant?

**Comment by monkeyiq** [comment]
yes. I will propose it to the FileSender board for consideration

**Comment by monkeyiq** [comment]
I just noticed the title. Adding a rest client upload / download / create guest run to the CI would be useful to ensure that the various rest clients do not break release to release.
