### ISSUE TITLE
Database.php script don't work for me

### ISSUE THREAD

**Issue by regastrid** [filesender/filesender#1300]
Hello, i tried to execute the script database.php but a lot of errors come out : 

![image](https://user-images.githubusercontent.com/48769445/180753057-3bb6974f-a5f9-44da-a64b-d7801b2a6630.png)

And the log say that : 

![image](https://user-images.githubusercontent.com/48769445/180753237-43a02067-b884-4a09-b039-fa46c8fb80e0.png)

When i tried to see the page http://localhost/filesender, it's show me this : 

![image](https://user-images.githubusercontent.com/48769445/180753334-98da5dcc-5d80-40a8-aee7-213f539b23c8.png)

I'm on php 7.4.30
Can someone help me ? i begin to be crazy !!

Thanks for you help !

**Comment by WebSpider** [comment]
You have not filled your `config.php` correctly. There is at least `db_type` and `db_database` missing.

**Comment by monkeyiq** [comment]
I made the error message more obvious in https://github.com/filesender/filesender/pull/1348 

Seems like a small update to make the solution more known.

**Comment by monkeyiq** [comment]
@regastrid did setting db_type in config.php work ok and allow you to complete the installation?

**Comment by monkeyiq** [comment]
Please reopen this issue if the above information did not fix it for you.
