### ISSUE TITLE
[2022-07-29 08:56:49] [upgrade:error] [8] Undefined variable: logger in /opt/filesender/filesender/classes/utils/DatabasePgsql.class.php at line 170

### ISSUE THREAD

**Issue by baybarshan008** [filesender/filesender#1303]
![2022-07-29 11_27_55-Ubuntu-2 - VMware Workstation](https://user-images.githubusercontent.com/98581839/181717914-cbccffb2-dc68-448b-9971-3db193993a32.png)

![2022-07-29 11_28_39-Ubuntu-2 - VMware Workstation](https://user-images.githubusercontent.com/98581839/181718107-e5bed13b-a989-4127-b8a8-0338bc731226.png)

![2022-07-29 11_29_45-](https://user-images.githubusercontent.com/98581839/181718229-348761f0-7900-47d0-a679-bafaa5c11af8.png)

How do I solve the problem?

@monkeyiq

**Comment by monkeyiq** [comment]
Which version of FileSender are you using?

**Comment by baybarshan008** [comment]
https://github.com/filesender/filesender

Default branch: development

**Comment by monkeyiq** [comment]
Looking at github development, the code in `createTableSecondaryIndex()` and it's method arguments are different. There is a logger parameter in development as well as release 2.35 and 2.34.
https://github.com/filesender/filesender/blob/development/classes/utils/DatabasePgsql.class.php#L226

Maybe there is some stale code somewhere in the installation?

**Comment by monkeyiq** [comment]
I think without feedback on the issue in such a long time it might be resolved or no longer of interest. If it is the later please reopen the issue and I can try to help track it down further. Thank you.
