### ISSUE TITLE
Show logged-on user in "My Transfers - See the transfer logs" when "user must login" and "get link instead of sending" are selected in "Upload"

### ISSUE THREAD

**Issue by dxdemetriou** [filesender/filesender#1314]
It could be usefull if it's possible instead of "Recipient Anonymous started downloading" to show the username of the logged-in user if the user is logged-on

**Comment by monkeyiq** [comment]
I'll do some more validation on https://github.com/filesender/filesender/pull/1354 but it is likely to get merged soon :)

**Comment by monkeyiq** [comment]
This has some privacy concerns because it exposes the downloading user's email to the person who created the transfer. The option is off by default but is now available for sites who wish to do this.
