### ISSUE TITLE
redirection after file upload

### ISSUE THREAD

**Issue by kyaky** [filesender/filesender#1324]
Hi Team,

I found an issue that, when I use the guest token upload link generated via web interface, it shows a success pop up window after a successful upload.  **[screenshot 1]**  
![image](https://user-images.githubusercontent.com/5505790/191476851-ac26f8bf-29d8-4561-bcd8-9146a2860ce7.png)

default redirection is ok. **[screenshot 2]**
![image](https://user-images.githubusercontent.com/5505790/191477032-244f3570-5afd-42e2-9d95-9f1b95a8e73e.png)

When I use a guest upload token generated by Rest API, it doesn't show success window. After successful upload, it redirects me to false page 

**[screenshot 3]**
![image](https://user-images.githubusercontent.com/5505790/191477179-1407eb95-ab66-474a-9988-7ef87ecd6bef.png)

In my Rest API script, I do have transfer_options passed along with my json

'transfer_options' => array('email_daily_statistics','redirect_url_on_complete' => array( 'available' => false, 'advanced' => true, 'default' => '' ),'web_notification_when_upload_is_complete' => array( 'available' => true, 'advanced' => false, 'default' => true )),

However I don't think these two options are doing any thing to this issue, no matter true or false I set them to.
'redirect_url_on_complete'
'web_notification_when_upload_is_complete'

Any advice? Thanks

**Comment by kyaky** [comment]
#1318 is fixed but #1324 has nothign to do with #1318. 

#1324 is a seperate issue .

#1324 is same as #536

**Comment by monkeyiq** [comment]
It seems with the current `deveopment` branch an upload performed as a guest who was created from the REST api succeeds with a URL '...filesender/?s=home' without the vid etc and the `false` in there.

**Comment by monkeyiq** [comment]
Sorry about that, must have got the wrong button there :/ Could you please test with development to see if things work ok there. Perhaps there is another difference in our configuration which is causing this issue.

**Comment by WebSpider** [comment]
This is fixed for us in 2.39

**Comment by monkeyiq** [comment]
If anybody bumps into this issue again please reopen the issue or report a new one.
