### ISSUE TITLE
Feature request: verify e-mail-address on download

### ISSUE THREAD

**Issue by baumrasen** [filesender/filesender#1325]
It would be nice to have an option on upload, that the downloader should enter an additional verification code. This should be send on download-request to the e-mail-address, which is associated with the download-token.

The expiration time for this code should be set in the config. Default 5 min for example.

There should be the possibility to send a new verification code.

There could be an option to "keep the downloader signed in" (by cookie, which is associated with the a-mail-address of the downloader)

**Comment by WebSpider** [comment]
This has been added in 2.41
