### ISSUE TITLE
fix undefined php index HTTP_X_FILESENDER_ENCRYPTED_ARCHIVE_DOWNLOAD

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1330]
Avoid php notices like PHP Notice: Undefined index: HTTP_X_FILESENDER_ENCRYPTED_ARCHIVE_DOWNLOAD in .../www/download.php on line 409, see this pull request: https://github.com/filesender/filesender/pull/1327

**Comment by monkeyiq** [comment]
https://github.com/filesender/filesender/pull/1327 is now merged. Thank you for the issue and PR :)
