### ISSUE TITLE
Guest Vouchers Not Working

### ISSUE THREAD

**Issue by drudich** [filesender/filesender#1333]
We are able to send out a guest voucher just fine, however when the guest clicks on the link, selects the file to upload and clicks the upload button, they are presented with the following error:

![image](https://user-images.githubusercontent.com/39833704/198310648-15878f01-7407-4984-8286-3f93138b522a.png)

We have been using FileSender for years and never had this issue... we recently upgraded to v2.37, so I'm not sure if that introduced this issue.  I looked through the configuration directives and I'm not seeing anything pertaining to enabling/disabling guest authentication. 

Thanks in advance!

**Comment by drudich** [comment]
I upgraded the version of PHP on the server and it's working properly now.

**Comment by benjulios** [comment]
I owe you some beers
