### ISSUE TITLE
[Proposal] How about using Weblate?

### ISSUE THREAD

**Issue by ramazansancar** [filesender/filesender#1336]
- [Web Site](https://weblate.org/)
- [Open Source Repo](https://github.com/WeblateOrg/weblate)
- [Demo (User-friendly interface)](https://hosted.weblate.org/)

**Comment by WebSpider** [comment]
What would it bring over the system we're currently using?

**Comment by ramazansancar** [comment]
Automatic push and automatic language translation support on language support

**Comment by WebSpider** [comment]
Thanks for suggesting this. 

Looking at weblate, it would either require an infrastructure to be present to run this on, or a subscription of some sorts. 
Is this correct or am I overlooking something obvious?

**Comment by ramazansancar** [comment]
Yes

> Thanks for suggesting this.
> 
> Looking at weblate, it would either require an infrastructure to be present to run this on, or a subscription of some sorts. Is this correct or am I overlooking something obvious?

Yes

**Comment by monkeyiq** [comment]
This would be a decision for the FileSender board to make. Perhaps it is better to be located at https://github.com/filesender/governance/issues

Currently translations are imported in bulk from poeditor using a script. At the moment if people wish to update translations then they are free to contribute using poeditor.

**Comment by WebSpider** [comment]
The consensus at the moment is that we do not see enough added value from weblate to migrate from our current solution.
