### ISSUE TITLE
Possibility to disable translatable email feature

### ISSUE THREAD

**Issue by moschlar** [filesender/filesender#1342]
Can the translatable email footer be disabled?

**Comment by WebSpider** [comment]
Yes, it can, but not by a config setting.

When you create a file called 
`/path/to/filesender/config/language/<your language here>/translate_email_footer.mail.php` 
and give it the contents:

```php
<?php

```
the default footer should be removed by an empty one, for this language

**Comment by monkeyiq** [comment]
@moschlar does the above solution solve things for you?

**Comment by moschlar** [comment]
:rofl: Actually - I had completely misunderstood what this feature is about.

I thought that line was nagging me to contribute to FileSender development by helping create translation files (which I would have no particular problem with) - but that it was about giving me the possibility to view this particular email content in different languages, that didn't become clear to me.

So - my issue is basically invalid - thanks, though. :wink: 

I would however very strongly urge you to change the exact wording to be something more like "View this email in other languages" or "View translated versions of this email" or something like that to make it clear to even an occasional user what its purpose is!

**Comment by monkeyiq** [comment]
A good idea! I can see how the "Translate this email" would be better put as "View this email in other languages". Thanks for the issue.

**Comment by monkeyiq** [comment]
I have updated the English / English AU in poeditor for this.
