### ISSUE TITLE
Ability to migrate from Filesystem to FilesystemChunked

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#136]
The new FilesystemChunked storage allows files to be stored as chunks instead of being assembled into a single file on disk. There is no easy way to convert from storage_type Filesystem to FilesystemChunked while retaining the existing files at the moment.

Current winning option;
* store the storage_type used for the transfer in the database so the admin can change things as they like without breaking any existing uploaded files. Possibly add a migration script to fill the storage_type based on if it is a file or directory so that existing installations from master can be easily updated.

A few other options come to mind;
* Graceful fallback. If the uid is not a directory then fallback to Filesystem storage for that file so existing files can still be served while new files are created chunked.
* Script to convert files into chunked files. This might be less desirable than the above due to run time. The script could run two pass, in the first creating the chunks in directories and the later just renaming the directories and files. This would allow chunked files to be done while the system is running and lessen the downtime while switching storage to chunked (the second renaming pass).

**Comment by jornane** [comment]
Add a field to the database so we know for each file which storage class was used. This will make it safe for an admin to change the value of the storage class without being afraid of stuff breaking, and it will prevent running uploads from being interrupted when the value is changed (the value is set at the start of the upload).

**Comment by jornane** [comment]
For backwards compatibility, it could assume StorageFilesystem if no class is set (files created before the change) but that would break stuff for those already using FilesystemChuncked. I'd still pick this solution, and send out a warning to everyone, stating that you're not affected if you use the latest beta or older.

**Comment by monkeyiq** [comment]
Adding the storage_type used during upload to the database seems like the right choice. There is some ability to workout fallbacks now but it will likely not scale as other storages are added.

**Comment by monkeyiq** [comment]
I editing the top post to reflect the current desired winning solution.

**Comment by madsi1m** [comment]
current winning solution will work fine. Probably not necessary for a change script. Maybe back fill the old transfers to default?
