### ISSUE TITLE
Allow per-domain settings

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1381]
We use filesender for several federated clients. Now some would like to have encryption activated by default, other another setting, etc ...
It would be nice if in the config (or a config-include), we could override settings on a per-client-login-domain setting. Even an if-structure would already be ok, but so far I have not been able to get it to work.
Or if any other way is possible, just point me in the right direction :-)

**Comment by monkeyiq** [comment]
The config class already has some code to load overrides for example passwords
https://github.com/filesender/filesender/blob/06e6b6e7b315e7363e0ee28afffd1157e7deaffc/classes/utils/Config.class.php#L139

Though I think extending the virtual hosts block might be a better fit
https://github.com/filesender/filesender/blob/06e6b6e7b315e7363e0ee28afffd1157e7deaffc/classes/utils/Config.class.php#L151

Perhaps getting auth attributes if a user is authenticated and making a file name for that federated client's overrides? Both of the above happen after the config.php base config is loaded so other config files loaded at that time will override the common settings. It is likely you will have to poke around to work out what SAML attribute you would like to use to name the config file.

```
if( Auth::isAuthenticated()) {
   $a = Auth::attributes();
   // use SAML attributes to build filename for config.php for that client
   $client_name = "FIXME";
   $client_config_file = FILESENDER_BASE.'/config/config-' . $client_name . '.php';

   $config = array();
   include_once($client_config_file);
   self::merge(self::$parameters, $config);
}

**Comment by liedekef** [comment]
Well, based on your code and example, I went a little bit further. I created a param in config.php that defines an array of attributes + regex and resulting filename to load if the regex matches for the attribute value.
Example: in config.php:

```
$config['auth_config_regex_files'] = [
        'uid' => ['@belnet.be$','belnet']
];
```
And in Config.class.php , below the section where loading the virtual host config (not inside it):
```
        // Load config regex overrides if used and present
        $auth_overrides_files = self::get('auth_config_regex_files');
        if( !empty($auth_overrides_files) && is_array($auth_overrides_files) && Auth::isAuthenticated()) {
                $a = Auth::attributes();
                foreach ($auth_overrides_files as $attr=>$regex_and_config) {
                        if (!is_array($regex_and_config)) {
                                continue;
                        }
                        list($regex, $extra_config_name) = $regex_and_config;
                        if (preg_match('`'.$regex.'`', $a[$attr])) {
                                $extra_config_file = FILESENDER_BASE.'/config/config-' . $extra_config_name . '.php';
                                if (file_exists($extra_config_file)) {
                                        $config = array();
                                        include_once($extra_config_file);
                                        self::merge(self::$parameters, $config);
                                }
                        }
                }
        }
```

So now, if my attribute "uid" matches something with "@belnet.be$", it will load the config config-belnet.php
This also allows to create multiple matching rules :-)
If you're interested, I can create a PR for this (please advise on variable names if not ok).

**Comment by monkeyiq** [comment]
Looks good! I am happy to merge the above, it seems like it would be useful to many installations :)

If you could include an entry in docs/v2.0/admin/configuration/index.md in the PR that would be great. Much of what would be that entry is in your above text :)

**Comment by liedekef** [comment]
I just created 2 new PR's (one doc, one code, don't ask me how ...) to update the functionality (allow multiple regex per attribute pointing to optional different config files).

**Comment by monkeyiq** [comment]
Both merged :)

**Comment by monkeyiq** [comment]
I think since this is reported, some nice PRs made and merged, I'll mark this is resolved.

Thank you for the report and PRs!
