### ISSUE TITLE
fallbackid null

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1382]
In  this changeset: https://github.com/filesender/filesender/commit/dd3c96d1406576721b969275c2d0f896151a3944
$fallbackid will be null if $src is empty (meaning no fallback translation found), causing a "null" string concatenation at line 476

**Comment by monkeyiq** [comment]
Thanks for the report. This should be fixed with the update in https://github.com/filesender/filesender/pull/1384.
Please reopen the issue if it persists.
