### ISSUE TITLE
feature request: force generate password

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1398]
When encryption is forced, it is not possible to also force a generated password by default (no setting present). It would be nice if optional this option could be checked (via config). A change in templates/upload_page.php and www/js/upload_page.js would also be needed for this (but I haven't gotten around doing this myself, the javascript used there is somehow not working 100% when I start changing stuff :-)  )

**Comment by monkeyiq** [comment]
I like this idea :)

**Comment by monkeyiq** [comment]
I might dig into this

**Comment by liedekef** [comment]
Well, I wanted to do this too, but the jquery used in the javascript files are weird to say the least :-) 
I nowhere see "jQuery(document).ready( function($) {" -like stuff, which would greatly simplify code to run after the dom is ready (which in the case of javascript is almost always). But for now I'll stay away from the js-files here.

**Comment by liedekef** [comment]
It seems the fix is not complete: you create 2 new variables:

```
if( $encryption_mandatory_with_generated_password ) {
    $encryption_generate_password_checkbox_checked = ' checked="checked"  disabled="disabled" ';
    $encryption_generate_password_checkbox_classes = '';
}
```
but: there're not initialized as being empty at first, nor are they actually used later on:
`                            <input id="encryption_use_generated_password"  name="encryption_use_generated_password" type="checkbox" >  `

**Comment by monkeyiq** [comment]
I was initially planning to do the update in the template so those were there. It is easier to do it in the javascript code.
If the user hacks the browser to disable the setting they could do that equally well if the HTML is setting it or javascript. Why they would want to do that and enjoy less security is another question.

**Comment by monkeyiq** [comment]
Please reopen the issue if it is still present for you. Thank you for reporting this!
