### ISSUE TITLE
Advice: Disabling non-expiring guests

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1399]
Hi All,

We are considering turning off "does_not_expire" for guests.
```
$config['guest_options']['does_not_expire'] = array(
               'available' => false,
               'advanced' => false,
               'default' => false
        );
```

What would be the best/easiest way to set all non-expiring guests to a specific datetime after we disable this feature?

**Comment by monkeyiq** [comment]
I just enabled this locally and made a few does not expire guests. It seems that `guests.expires is null` for those guests and options includes `"does_not_expire":true`.  I would say that both of those values would need to be updated for this change to work. See for example the short out in cron.php when does_not_expire==true.
https://github.com/filesender/filesender/blob/3d2282dc25aff486e04b7b9b3da17fe952a1f48e/scripts/task/cron.php#L121

Setting expires to a date for all tuples where `expires is null` should be a fairly simple SQL update. I imagine setting the does_not_expire flag might be done with string substitution to leave the other options intact. A single SQL update is likely to be the fastest way to update things.

If the count(*) for these non expiring guests is low enough php could do the update. If there are heaps of them it might be prohibitively slow.
```
foreach(Guest::allAvailable() as $guest) {
    echo "have guest...\n";
    if( $guest->does_not_expire ) {
       // to do this you need to temporarily allow setting dne in Guest::__set
        $guest->does_not_expire = false; 
// if you want to do this remove the BadExpireException in getDefaultExpire in guest::__set.
///        $guest->expires = time() + 60*60*24*90; // 90 days from now.
        $guest->save();
    }
}
```
To do the above you need in Guest.class.php
```
    public function __set($property, $value)
...
        } elseif ($property == 'does_not_expire') {
            $this->options['does_not_expire'] = Utilities::isTrue($value);
```

**Comment by monkeyiq** [comment]
It is probably a great idea to grab guest.id for all these tuples to keep an eye on them over time.
```
select id from guests where expires is null order by id desc;
```

**Comment by madsi1m** [comment]
Something like this then?

```
UPDATE Guests SET options=REPLACE(options,'"does_not_expire":true','"does_not_expire":false'), expires=NOW() + INTERVAL 40 DAY WHERE expires IS NULL
```

**Comment by monkeyiq** [comment]
Looks good. I just switched to the FileSender mysql backend, made a few guests and ran it on a few new guest tuples :)

**Comment by monkeyiq** [comment]
I guess fix merged might be applicable :)

**Comment by monkeyiq** [comment]
Please reopen the issue if it is still present for you. Thank you for reporting this!
