### ISSUE TITLE
[2.39] graph on upload page isn't shown

### ISSUE THREAD

**Issue by makinog3** [filesender/filesender#1404]
On release 2.39, a graph on the upload page isn't shown.

I confirmed that if the version of "chart.js" changed by "update javascript deps #1376" is rollbacked, it will be shown on our environment.
https://github.com/filesender/filesender/pull/1376

[not show graph](https://drive.google.com/file/d/1-2iUvxn2FDkrAhUwBCu3KN6XipAMBWJL/view?usp=share_link)

**Comment by makinog3** [comment]
I'm sorry. It has been solved.
Maybe an old version of some JavaScript files was still cached, and after clearing all of them, the graph is shown.

**Comment by monkeyiq** [comment]
No worries. I get hit by the stale js cached file a few times myself :)

**Comment by makinog3** [comment]
I thought the issue had been solved, but it occurred again.
There were JavaScript loading errors in the console of Chrome.
`./chunks/helpers.segment.js` and `@kurkle/color` are not in  our environment.

```
﻿chart.min.js:7 Uncaught SyntaxError: Cannot use import statement outside a module (at chart.min.js:7:1)
graph.js:5 Uncaught ReferenceError: Chart is not defined
    at Object.<anonymous> (graph.js:5:19)
    at c (jquery.min.js:2:28599)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29344)
    at l (jquery.min.js:2:80328)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82782)
```

**Comment by monkeyiq** [comment]
ok, I'll take a look :)

**Comment by monkeyiq** [comment]
The above https://github.com/filesender/filesender/pull/1408 should fix things.

**Comment by monkeyiq** [comment]
Please reopen the issue if it is still present for you. Thank you for reporting this!

**Comment by makinog3** [comment]
Thank you. This fix has already been taken to our site and resolved.
