### ISSUE TITLE
Feature Request - Per domain personalisation

### ISSUE THREAD

**Issue by charcoalbe** [filesender/filesender#1406]
Add possibility for personalisation (intro text / logo / custom css (?) ) per domain. 
Possibility to also link guest-uploads to domain of requester (and have personalisation work there)

**Comment by liedekef** [comment]
If the text/logo/css-url were to be options, we could use the new feature  auth_config_regex_files already for this.
So I think this could be a request to be able to have a config option for intro text/logo/css-url .
Btw: a left/right logo would be even more interesting (so people wanting to have their logo per domain could still also have the logo of the organisation running filesender visible).
While I think about this, I guess using a different theme per customer is already possible, but personally I also think the text/logo/css could merit a config option on their own :-)

**Comment by WebSpider** [comment]
Closing this issue, as the remaining TODO items will be adressed in #1547
