### ISSUE TITLE
Issue downloading encrypted files

### ISSUE THREAD

**Issue by bzouille** [filesender/filesender#1410]
Hi, 

I have the following problem with version 2.39 on Debian 11.
Uploading and downloading unencrypted files works correctly, but as soon as we want to download an encrypted file the associated password is never asked.

- Clicking on the download button has no effect. (no popup to enter decryption password)
- No visible error message on the server side (in debug mode)
- On the browser side the following message appears in the dev console

```
Uncaught TypeError: Cannot set properties of undefined (setting 'crypto_encrypted_archive_download')
    at dl (download_page.js:200:77)
    at download_page.js:232:13
    at success (client.js:147:26)
    at c (jquery.min.js:2:28599)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29344)
    at l (jquery.min.js:2:80328)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82782)
```
If you can help me to understand the problem, thanks for your help.

**Comment by monkeyiq** [comment]
Did this issue present on older versions such as 2.38 etc. This might help narrow down the code changes.

**Comment by bzouille** [comment]
Yes same issue in 2.38 (and with Chrome and Firefox)

Thanks,

**Comment by monkeyiq** [comment]
Could somebody please test with https://github.com/filesender/filesender/issues/1410 to see if this resolves the issue. Thank you.

**Comment by WebSpider** [comment]
> Could somebody please test with https://github.com/filesender/filesender/issues/1410 to see if this resolves the issue. Thank you.

I assume you mean #1422 ?

**Comment by bzouille** [comment]
Hi,

I have just tried with this patch and the popup requesting the password now appears correctly and allows the download of an encrypted file.

Thank you for this fix 👍
