### ISSUE TITLE
Using filesender CLI combined with non-email based userid fails: auth_remote_signature_check_failed

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1418]
When using the filesender CLI in an environment where the filesender userid's are derived from a SAML attribute which is not the emailaddress, but for instance a pseudorandom identifier, correct usage of the CLI client results in a `auth_remote_signature_check_failed` error.

**Comment by WebSpider** [comment]
What we're seeing here is:
- The user has an existing user, a filled `saml_user_identification_uid` and corresponding API secret
- Upon using the CLI client, a new user gets created where his `saml_user_identification_uid` becomes his email address as passed by the `-u` argument to the filesender cli
- Filesender then tries to use the newly created user, which offcourse has a different API secret from the original one, and it complains about the signature

Alternative could be to use the uid as the -r option, but then the server fails to accept a new transfer, with a `bad_email` error

**Comment by WebSpider** [comment]
User identification seems to work correctly with #1415

**Comment by monkeyiq** [comment]
I am thinking the working part comes from the use of `site_info['from_address']` instead of `user_id` in the postTransfer function.
https://github.com/KenRoy-Octo/filesender/blob/a025ce34cf032b90fed7903ad0f521c1738627c0/scripts/client/filesender.py#L231

**Comment by monkeyiq** [comment]
It seems PR 1415 was closed as it removed some recent merged PRs. I guess I could look at what was added or trace back on the `site_info['from_address']` part and create a new small PR with just that part.

**Comment by monkeyiq** [comment]
The from_address part of https://github.com/filesender/filesender/pull/1415 should be in https://github.com/filesender/filesender/pull/1442
