### ISSUE TITLE
Guest upload page - Allow the expiry date to be equal to the invite expiry date by default

### ISSUE THREAD

**Issue by Veredior** [filesender/filesender#1443]
When an authenticated user creates an invite for one or more guests, our users would like to lock or to define as default the guest upload page expiry date to be equal to the invite expiry date.

Maybe an option on the guest creation page is the way.

**Comment by monkeyiq** [comment]
It makes sense for a new option `guest_uploads_expire_when_guest_expires`  to allow the guest upload page expiry date to be clamped to the invite expiry date. 

We should be careful to not allow this to also extend the transfer expire time to be above what the sys admin wishes for transfers. So I have made the new option use the minimum of `max_transfer_days_valid` and the time the guest will expire.

As for locking I made a new option `guest_upload_expire_read_only` which allows that to be locked independent of the option above.

**Comment by Veredior** [comment]
Thank you for the quick response !
The two new options work after some testing.
One remark, the option guest_uploads_expire_when_guest_expires does not what it says. It's something more like : guest_uploads_default_expire_is_guest_expires.

I will add this remark in the pull request.

**Comment by monkeyiq** [comment]
Cool. Merged your naming updates and merged the PR. Enjoy!
