### ISSUE TITLE
Feature Request - Daily buckets for CloudS3 backend

### ISSUE THREAD

**Issue by juhassi** [filesender/filesender#1445]
Hi,

I've been testing Filesender's CloudS3 support with the intention of moving our production installation from local (file) storage to using our private ceph storage. With the fix from #1417, this looks good - but our ceph admins don't like the way Filesender uses S3 buckets.

Currently supported possibilities are "one bucket for everything" (= a huge number of objects in that bucket) or "one bucket per file" (= a lot of buckets, each with very few objects). We have S3 quotas in our environment (max buckets & max objects in a single bucket) that we would be eventually hitting.

Our ceph admins suggested to create 1 bucket per day and put all files transferred during that day to said bucket. A quick look at `classes/storage/StorageCloudS3.class.php` suggests this might not be very difficult to add; you could figure out proper bucket name by using File's upload_start. In fact it looks like most problematic would be deleting used buckets when they no longer have any objects in them.

If this would be considered a useful feature, I might try to hack together a patch.

My best current idea for bucket management would be to handle it in cron.php (or maybe in a new s3cron.php) - this would delete old buckets if they're empty and also create new buckets for the next N days/weeks. (It actually looks like current code is already calling `$client->createBucket` multiple times for the same bucket, so the cron might not even need to create new buckets -- only remove old ones).

**Comment by monkeyiq** [comment]
I am happy to take a look at such a PR. If it is useful for one site running with S3 backing it is likely to be useful for other sites as well. I would probably put the bucket delete in cron.php just checking if the active storage == s3. Something like the below but looking for "CloudS3". The fewer extra scripts an admin as to remember to run the easier life should be.

https://github.com/filesender/filesender/blob/47dd8e90e4f4f4faffad970f133b8a35efb2f51d/classes/utils/Config.class.php#L246

**Comment by juhassi** [comment]
> I am happy to take a look at such a PR. If it is useful for one site running with S3 backing it is likely to be useful for other sites as well. I would probably put the bucket delete in cron.php just checking if the active storage == s3. Something like the below but looking for "CloudS3". The fewer extra scripts an admin as to remember to run the easier life should be.

I've been hacking this together on our development host. During this, I've noticed few bugs related to StorageCloudS3 (one of them was quite serious -- filesender is deleting wrong files from the bucket when configuration option cloud_s3_bucket is set). There's a separate pull request for these fixes, #1450

**Comment by monkeyiq** [comment]
Merged, thanks for the updates in https://github.com/filesender/filesender/pull/1450 :)

**Comment by juhassi** [comment]
I've now created PR #1455 which contains a "works for me" version of S3 daily bucket support. I'll continue testing this over the next week and see if I can find any bugs.

The changes to transfers_table.php are ugly, but that's the only way I figured out to hide that particular transfer option from web ui.

There also seems to be a bug with server-side .zip file generation related to S3 backend, but I haven't yet been able to narrow it down (and archive creation code seems to be a bit difficult to follow at times). The .zips generated from S3 storage are getting corrupted if they contain a bit bigger file - creating a .zip with very small files works well. The code is throwing out an exception in the middle of the process, but the exception details are _not_ logged to server logs, so it might be a yet-another issue of PHP hitting memory limit.

**Comment by juhassi** [comment]
Found also the likely culprit for occasionally getting corrupted .zip files and merged my proposed fix to this PR.

StorageCloudS3Stream wasn't checking for stream_eof() so in some cases the server-side .zip creator was trying to download more object parts than there were available in S3 (throwing a 'Aws\S3\Exception\S3Exception' with message 'Error executing "GetObject" on ... resulted in a 404 Not Found response').

**Comment by monkeyiq** [comment]
Merged!

**Comment by monkeyiq** [comment]
Thank you for your contributions to CloudS3 and FileSender. Since these are merged I am marking this issue as resolved.
