### ISSUE TITLE
FileSender not compatible with SimpleSAML 2.0

### ISSUE THREAD

**Issue by drudich** [filesender/filesender#1467]
I tried upgrading to SimpleSAMLphp 2.0.3 and found that it is not compatible with FileSender.

FileSender references as_login.php and as_logout.php in the AuthSPSaml.class.php (line 211 and line 234) to complete the SAML authentication request and these files no longer exist in version 2.0 of SimpleSAML

**Comment by monkeyiq** [comment]
I haven't tested against SimpleSAMLphp 2. I'll take a look to see if things can be updated in a way to work against both SSP versions (maybe a config option in FileSender).

**Comment by monkeyiq** [comment]
Hopefully the current development will work for you now :) I have a slightly modded SSP 2.0.3 which I have been testing against. 

My SSP mods are mainly for a custom local db auth with a custom module.

**Comment by monkeyiq** [comment]
This will be in release 2.41 and beyond.

**Comment by madsi1m** [comment]
With newer SSPi get an error if my authsource is example-userpass and not saml:SP. (for testing)

Is there another way to setup SSP with a fake saml:SP config?

**Comment by madsi1m** [comment]
commenting this out seems to work for testing but it is possible for real installs to not use saml:SP
https://github.com/simplesamlphp/simplesamlphp/blob/fdbe0017488f831cfd857ceefb0cd807088b5d83/modules/saml/src/Controller/ServiceProvider.php#L113

**Comment by monkeyiq** [comment]
I have also commented that line out on my installation. 

Locally I am using filesender-dbauth with sqlauth:PasswordVerify on my SAML2 config.php.

**Comment by monkeyiq** [comment]
Semi related, this is the code I tend to use for local auths... https://github.com/simplesamlphp/simplesamlphp-module-sqlauth/pull/6

**Comment by tvdijen** [comment]
> Is there another way to setup SSP with a fake saml:SP config?

I don't think there is one right now, but it makes sense for SimpleSAMLphp to include a dummy saml:SP that can be used for testing purposes.
Meanwhile you _could_ try to create an anonymous class that extends saml:SP and then overload some of the methods.

**Comment by madsi1m** [comment]
I ended up deploying a SSP with saml:SP and hooking it up to another SSP used as an IDP with sqlauth and shared metadata across the two.

This works well for me in testing as it closer emulates our production as multiple institutes can log into our FileSender

**Comment by monkeyiq** [comment]
Thanks for the info. This thread is likely to be of interest to others as they migrate to saml2.

**Comment by WebSpider** [comment]
@drudich are you still seing this issue in 2.41+ ?

**Comment by drudich** [comment]
@WebSpider - this issue appears to be fixed, but I encountered a different/new issue (with email) in 2.41:

https://github.com/filesender/filesender/issues/1533

**Comment by WebSpider** [comment]
Yes, that issue should be fixed in the current development version and is awaiting a release currently. Closing this issue as it's fixed.
