### ISSUE TITLE
[3.0] cannot fold transfer information on My_Transfers page

### ISSUE THREAD

**Issue by makinog3** [filesender/filesender#1468]
We are trying the 3.0 beta1.
On `My Transfers` page, transfer information cannot be folded after it has been unfolded.
The `+` button disappears.

<img width="859" alt="Screenshot 2023-05-11 at 15 19 17" src="https://github.com/filesender/filesender/assets/2472763/3dea4c18-5a5b-47e3-b9e4-5f4294dd65e1">

↓

<img width="851" alt="Screenshot 2023-05-11 at 15 19 53" src="https://github.com/filesender/filesender/assets/2472763/040f8b34-0d86-46c3-b98e-baf496fa34b9">

**Comment by monkeyiq** [comment]
Somehow the collapse button area was being hidden. This should be fixed with https://github.com/filesender/filesender/pull/1471
