### ISSUE TITLE
[3.0] Continue button moves

### ISSUE THREAD

**Issue by makinog3** [filesender/filesender#1470]
We are trying the 3.0 beta1.
The `Continue>` button moves when the mouse is on the graph, and the `Continue>` button will be hard to click.
I would like that button relocated to the upper portion of the graph.

**Comment by monkeyiq** [comment]
I am happy to move this button. I tend to test without the graph showing which makes issues like this more able to happen :/

**Comment by monkeyiq** [comment]
Thank you for reporting these :)
