### ISSUE TITLE
Could not find PEM encoded certificate in /opt/filesender/simplesamlphp-1.19.7/cert/certificate.csr

### ISSUE THREAD

**Issue by Telmo2023** [filesender/filesender#1474]
Hello everyone, 

It's been a week that i'm trying to do filesender and authenticate this service with SAML.

When im trying to access the filesender to login appear the following error in /var/log/syslog: Caused by: SimpleSAML\Error\Exception: saml20-idp-hosted/'https://192.168.0.1/saml-idp': Could not find PEM encoded certificate in "/opt/filesender/simplesamlphp-1.19.7/cert/certificate.csr". 

I already generate certificates with the extension .pem, .csr, .cert and no one is working. I changed in the configurations files the name and extension of the certificates.
![123](https://github.com/filesender/filesender/assets/133687209/f1f5e2cc-27c3-42e6-8ff5-e4e18dd15426)

Please help me!!!!!!

![123](https://github.com/filesender/filesender/assets/133687209/f60aca29-cd39-4d01-80ac-8b2ca0bee864)
![1213123](https://github.com/filesender/filesender/assets/133687209/e32ba76f-25c5-426b-ae65-da28153b40ad)

**Comment by monkeyiq** [comment]
You could update Configuration.php to show the read certificate.
```
error_log('cert data ' . $data);
```
It seems that a file can be read but it does not contain the expected `BEGIN CERTIFICATE` lines.

The reading of the file must find something as the checks above would throw `Unable to load certificate/public key from file` for a non existent file or unreadable file (permissions).

**Comment by monkeyiq** [comment]
It seems this particular issue is solved :)
