### ISSUE TITLE
Attribute of authentication SP not found

### ISSUE THREAD

**Issue by Telmo2023** [filesender/filesender#1478]
Hi guys,

I have a problem with the authentication in Filesender. Someone please help me...

I think the problem is about the attributes of config.php in filesender!

Here are some prints:

![image](https://github.com/filesender/filesender/assets/133687209/dbe2cc32-6f65-4b83-953c-201c99a818a5)

![image](https://github.com/filesender/filesender/assets/133687209/eb103e07-9064-41a5-b119-4f001e3d5806)

![image](https://github.com/filesender/filesender/assets/133687209/ec3beda8-b6d3-43e5-a5ba-0475bccf2114)

![image](https://github.com/filesender/filesender/assets/133687209/e2bc0a6a-2ef4-4fce-95c4-ef9dc0feebb7)

**Comment by WebSpider** [comment]
Usually, there is a pretty good hint about this in `/opt/filesender/filesender/logs`

**Comment by WebSpider** [comment]
As part of your config, you have said:
`$config['auth_sp_saml_uid_attribute'] = 'test';`
This means, filesender needs to look for the user attribute `test`, which will be used as uid in filesender.

You have not configured simplesamlphp to pass the attribute `test`, but the attribute `uid`, with the value `test`.

**Comment by WebSpider** [comment]
You have configured filesender to look for the `email` attribute on a user, so it knows how to contact a user. You are not providing any in your simplesaml config, only uid and edupersonaffiliation.

**Comment by Telmo2023** [comment]
@WebSpider I'm so sorry to waste your time, but i configured like the below image and keep don't work...

![image](https://github.com/filesender/filesender/assets/133687209/d030134d-8cd0-4612-96d4-f2ab77829ee8)

**Comment by WebSpider** [comment]
Replace 'mail' for 'email' and 'email' for 'examplemail@example' and it should start working

**Comment by monkeyiq** [comment]
Please reopen the issue if there are still questions or your installation is not working as described. Thank you for the report.
