### ISSUE TITLE
E-mail fields are not visible in FileSender

### ISSUE THREAD

**Issue by Telmo2023** [filesender/filesender#1479]
Hello,

I have a problem that the fields of e-mail (send to and message...) are not visible in the upload of file!!

How can I solve this problem??

![image](https://github.com/filesender/filesender/assets/133687209/51495c03-0d2b-4b22-8a05-b7799674e21b)

**Comment by monkeyiq** [comment]
The "obter um link" / get a link is selected. In this mode the email address is not required. Turning that off should make the to, subject etc available (and required).

**Comment by monkeyiq** [comment]
Please reopen the issue if there are still questions or your installation is not working as described. Thank you for the report.
