### ISSUE TITLE
Are there any examples of avprogram_list usage?

### ISSUE THREAD

**Issue by realroywalker** [filesender/filesender#1481]
I have been testing filesender today on a small research setup and it looks great. However one thing I can't quite work out is how AV can be integrated?

I would like to send everything that gets uploaded through an AV scan to make sure it's clean before allowing anyone to download.
Looking at the docs (https://docs.filesender.org/filesender/v2.0/admin/configuration/) I came across the avprogram_list option but I'm not 100% clear from the docs if this is the option I need, or how it would be implemented.
It seems to suggest that the file is sent to the specified url and then json should be returned to state if it passed or if an error occurred what exactly should be returned and how does it track this back to the file? 
Given that the AV scan could take a reasonable period of time I assume that some tracking ID must be returned ? 

Either that or I've totally misunderstood how it works 😄

**Comment by monkeyiq** [comment]
Thanks for the feedback. It seems some key information was trapped in the PR header text and not in the docs themselves. I have brought that forward and updated it a little in the docs. If anything doesn't make sense or should be updated a little please let me know.

https://docs.filesender.org/filesender/v2.0/admin/configuration/#avprogram_list

same link but to the raw docs
https://github.com/filesender/filesender/blob/3ff1b101fef45ee569a3509cb7337d7074551b20/docs/v2.0/admin/configuration/index.md?plain=1#L563

**Comment by WebSpider** [comment]
Closing as documentation is updated
