### ISSUE TITLE
Sending many files in a transfer causes webserver to respond with 'Request-URI Too Long'

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1483]
When sending a transfer with many files, the process of downloading is aborted with a Request-URI Too Long error.
This is caused by retrieving file-related information in preparation for the download, since it only occurs during download. Upload is fine.

It seems that the query built in https://github.com/filesender/filesender/blob/e8ec51e833f8ce56c3817f09ec08642eda2d2d76/templates/download_page.php#L67 is allowed to expand indefinately. We may need to add some method to keep this sane.

**Comment by monkeyiq** [comment]
Sounds good. There might be other locations that are not using `Utilities::http_build_query` as yet as well. I'll see if I can reproduce this and work out what is going on. By many files are we talking a 20, 200, 2k or more ballpark?

**Comment by WebSpider** [comment]
Around 1000 files triggers it

**Comment by monkeyiq** [comment]
There seem to be a number of assumptions that do not work so well at 1k files. At least in the next version adding them will be quicker too ;)

**Comment by monkeyiq** [comment]
When downloading files from a non encrypted transfer the code was passing the file_id list as a GET parameter. Once that got too large for a specific environment it was going to cause problems. Things were OK at the time this assumption was made when only 6-10 files were added to an upload. Now that you can upload a whole directory etc then it is probably more common to have 2k file uploads. 

In https://github.com/filesender/filesender/pull/1490 I moved the archive download path to using a POST to send the file id list to the server. This should get around URL length issues.

**Comment by WebSpider** [comment]
Tested and fixed in 2.41

**Comment by monkeyiq** [comment]
Excellent, thank you for the confirmation :)
