### ISSUE TITLE
[Suggestion] Modernize UI

### ISSUE THREAD

**Issue by axelvugts** [filesender/filesender#1484]
I think adoption of this tool by students would benefit from a more modern UI. I've used this service a few times as a student myself, and I think the UI might "scare" less tech savvy students away.

**Comment by madsi1m** [comment]
Hi, take a look at the v3 branch, in addition to this i think there is also other work going on to better the UI/UX

**Comment by adminnr1** [comment]
Yes, V3 is already the first step to a new UI/UX. There is work going on to improve the UI/UX as we speak. 
An update will be presented during TNC on Thursday June 8.

**Comment by axelvugts** [comment]
Thanks for the replies, that's great to hear!

**Comment by monkeyiq** [comment]
Thank you for your interest in FileSender and the UI. I would have liked to make the UI updates more visible to the community as they were proposed, developed etc. There have been three UI update projects over recent years. The third of these is what is now the 3.0 alpha / beta release. 

There is a new current effort to rewrite the UI which has been kindly offered by an NREN. IIRC there was a plan to introduce this effort on the mailing list but do not recall that being done publicly so am leaving the detail vague here :/ I think there are hopes to have this merged and a 3.0 release made by the end of the year. Though the timing will depend on many factors so may be delayed (or brought forward :).

There should be PRs of this new UI made available before then so interested people can see and follow the changes.

I think I might mark the issue as resolved as the feature is actively being worked on.
