### ISSUE TITLE
php warning session_cache_limiter

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1488]
Using version 2.39, I see these php warnings in the logs a lot:

PHP Warning:  session_cache_limiter(): Cannot change cache limiter when session is active in /opt/filesender-2.39/includes/init/init_web.php on line 34

I currently added "@" in front of that line, but maybe that call should go in the if-structure below (which checks that the session isn't active yet)

**Comment by monkeyiq** [comment]
Thanks for the report, I have updated this in https://github.com/filesender/filesender/pull/1492

**Comment by monkeyiq** [comment]
I think this is handled. Please reopen or rereport if things persist.
