### ISSUE TITLE
Update favicon to match new default image

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1493]
A while back, the homepage of filesender.org has been updated.
We never got around to updating the artwork in the actual shipping software.

This issue is to update the favicon to match the new icon on filesender.org

**Comment by monkeyiq** [comment]
This appears to have been converted to a word press site? I could try to break out the icon directly from the site I guess.

**Comment by monkeyiq** [comment]
I also notice that there are now calls to google-analytics gstatic.com and directly to google.com when loading the filesender.org site. This may be considered a fair amount of third party tracking for a landing page for FileSender.

**Comment by monkeyiq** [comment]
I assume the new icon is the one at 
https://filesender.org/wp-content/uploads/2020/01/faviconwit.png

**Comment by WebSpider** [comment]
Yep, I'll be converting this to favicon and sending in a PR

**Comment by WebSpider** [comment]
> I also notice that there are now calls to google-analytics gstatic.com and directly to google.com when loading the filesender.org site. This may be considered a fair amount of third party tracking for a landing page for FileSender.

I never noticed that, but it may be a good idea to move this to a more privacy-conscious tracking service. I know a few installs of filesender have a service like that.
