### ISSUE TITLE
Login required after failed decryption

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1515]
While testing filesender 2.40 on Chromium-based browsers, we ran into an issue that we have not encountered before.
It seems that filesender has a need to report the fact that decryption failed back to the server, which only works when you are authenticated. Since a typical use for filesender is to have unknown users download your file, authentication is not always possible

**Environment**
Server: Linux CentOS 7 with filesender2.40
Client: Linux Ubuntu 22.04.2 (LTS) with 
  - Brave Version 1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit) (affected)
  - Chromium Version 114.0.5735.198 (Official Build) snap (64-bit) (affected)
  - Firefox 115.0.2 (64-bit) (**not affected**)

**How to reproduce**
1. Install filesender 2.40
2. Start a new transfer with options: send a link, encryption
3. Upload files
4. Open link in private/incognito tab of Chromium based browser
5. Enter a wrong password
6. Get a request to authenticate yourself

**More details**
Looking at the inspector in the browser, this is most likely caused by an (XHR) PUT request to /rest.php/transfer/{transferId} with content '{decryptionfailed: true}', that is sent right after the "OK" button is pressed that notifies the user of an incorrect password 

Code for this seems to be here: https://github.com/filesender/filesender/blob/bf2e12b65ea214d41147487b96fd91b2f74b310f/www/js/client.js#L562 however this has been untouched for about 2 years, so unsure why this is now popping up.

**Comment by monkeyiq** [comment]
Just tried development against Google Chrome Version 114.0.5735.90 (Official Build) (64-bit) and I can download in an Incognito window ok. The first attempt I used a bad password and got the dialog, dismissed it, then downloaded again and used the correct password.

I updated Chrome to version 115.0.5790.102 and can download ok in Incognito (Ctl+Shift+n) mode ok after a bad password there as well. 

When you are in Incognito mode do you see the cookies still being sent? I notice both PHPSESSID and SimpleSAML cookies in my Incognito so maybe I am doing something wrong/different to avoid the issue coming up. I see these cookies for the PUT to the transfer/$id URL.

**Comment by monkeyiq** [comment]
This wrong password entry logging was added after a security audit IIRC. Personally I think it the functionality is somewhat bogus because if the user has nefarious intent they would disable the call to this log function as the first order of business.

**Comment by WebSpider** [comment]
I have only the cookie from SimpleSAML's `session.phpsession.cookiename` that's being sent with the PUT

**Comment by monkeyiq** [comment]
I can get the issue when I am already in Incognito mode with the download page loaded and delete all the cookies. Then just click download and enter a bad password.

**Comment by monkeyiq** [comment]
It seems I have to specifically delete the SAML cookie to get it.

**Comment by monkeyiq** [comment]
Can you only reproduce the issue in Incognito mode?

**Comment by WebSpider** [comment]
And then, the summerholiday happened.
I've just tried to reproduce it, and I can reproduce this in normal mode as well.

**Comment by WebSpider** [comment]
This issue has disappeared over time.
