### ISSUE TITLE
Rearrange poeditor translation setup for v3

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1517]
Currently translation handling is done via poeditor in a single project, and then imported via scripts into releases.

Since a while, poeditor supports the concepts of organisations, which can have github integrations that could integratie into automated processes, like CI.

Also, we have found a number of translation terms being unused, with no easy way to detect and handle this right now.

For this reson, we should revisit the translation setup, so we can handle this better and in a more automated fashion

**Comment by WebSpider** [comment]
After some investigations, the following seems to be a feasible setup

1. **New stuff to be translated**
Whenever a new term becomes available for translation, we can sync this with poeditor. This way, whenever there is new translation work to be done, this could even be done in the mean time between the feature being added to the development code, and a release being made. This improves the overall availability of translations for new features

_Technical implementation_: Create a list of terms in the repository, and link PoEditor to it. Whenever the list changes, perform a sync operation using PoEditor's GitHub integration

2. **Obsolete terms**
Whenever a term becomes obsolete, due to a feature being removed for instance, this can also be synced with poeditor. The term would then be marked "obsolete", and be scheduled for removal from all languages after an expiry period.

_Technical implementation_: Same as 1, except the integration would have a filter that marks the obsolete term with a tag, instead of deleting it. This is configurable in the PoEditor integration for GitHub

3. **From PoEditor to release**
Whenever a new release is made, it's important for the experience of end-users that the available translations are updated. As part of the release process, we already prepare the release notes automatically, and this could be added into that process.

_Technical implementation_: Still working on this one ;)

**Comment by monkeyiq** [comment]
For 1 I had been using the `scripts/language/export-terms-to-new-and-deleted-lists.sh` script which shows the terms that are added in files in /tmp. An automated method to send those to poeditor is send-newterms-json-to-poeditor.sh though I haven't tested that automated script in a bit. I have generally been uploading `/tmp/newterms.json` to poeditor and working from there as there are normally only a small handful of new terms. 

There is currently no obsolete terms handling that I know of in FileSender :/

For 3 the current method is using `scripts/language/import-all-from-poeditor.sh` which imports all the languages listed in that script to the php files in the top level language directory tree. I have been using that script and creating predictable PRs before release to allow folks to see what is available. 

I am happy if we are wanting to update these things in 1 and 3 to use actions or integrations or whatnot. A command line script just seemed to quickest method at the time. It also eschewed having a cloud action authenticate with poeditor as the auth key can be local to the private machine running the script.

**Comment by WebSpider** [comment]
> For 1 I had been using the `scripts/language/export-terms-to-new-and-deleted-lists.sh` script which shows the terms that are added in files in /tmp. An automated method to send those to poeditor is send-newterms-json-to-poeditor.sh though I haven't tested that automated script in a bit. I have generally been uploading `/tmp/newterms.json` to poeditor and working from there as there are normally only a small handful of new terms.
> 
> There is currently no obsolete terms handling that I know of in FileSender :/

I am planning on leveraging POEditor's GitHub integration for this: https://poeditor.com/help/how_to_translate_a_language_file_from_a_github_project#kb-article-title

in the following manner:
*When a PR gets merged and changes any language*:

1- Generate a new terms list in json.
2- Use the "get terms" functionality from POEditor's integration, combined with the "import rules". New terms are tagged "new". Removed terms are tagged "obsolete"

> For 3 the current method is using `scripts/language/import-all-from-poeditor.sh` which imports all the languages listed in that script to the php files in the top level language directory tree. I have been using that script and creating predictable PRs before release to allow folks to see what is available.

*When preparations are done for a release*:

We need to discuss if we want to automate the language import from POEditor into GitHub. It's easy to do, but I don't want to solve a nonexistant problem.

> 
> I am happy if we are wanting to update these things in 1 and 3 to use actions or integrations or whatnot. A command line script just seemed to quickest method at the time. It also eschewed having a cloud action authenticate with poeditor as the auth key can be local to the private machine running the script.

For the download, a script probably is just fine. Releases dont happen that often. When we get more contributions to the project, it would be nice to handle the terms whenever a feature lands (or is removed from) development, I'd think.
