### ISSUE TITLE
Homepage not showing after upgrading to php 8

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#1539]
Good day,

I recently upgraded from php 7.4 to php 8 on the machine running Filesender. After the upgrade, the homepage was not able to render properly. Kindly assist with what might be causing this issue.(See the attached picture)

Regards
Thuso
![image](https://github.com/filesender/filesender/assets/22442842/c653c3ce-2baf-4c95-b906-4d14afc86a31)

**Comment by monkeyiq** [comment]
I have been tempted over the years to add a script to do some checks on an install. The idea came about to check if the config json is well formed as if that is not the case it can also break in not so obvious ways. Though if that json is the issue you shouldn't see php in the browser.

**Comment by monkeyiq** [comment]
Did a slight web server tweak to interpret php files fix the issue?

**Comment by madsi1m** [comment]
depending on OS php8 might install somewhere that php7 isn't

**Comment by monkeyiq** [comment]
I have php-fpm 8.2.6 installed. Perhaps the update didn't start the service?
```
systemctl status php-fpm
```

**Comment by thuso607** [comment]
I managed to resolve the issue by disabling mpm event module and enabling the mpm prefork module. This resulted in php module being able to load on to the Apache webserver.
