### ISSUE TITLE
Server does not allow writing files after they exceed 80% in storage

### ISSUE THREAD

**Issue by ruan-oliveira** [filesender/filesender#1540]
Hi,

We faced the following behavior here at Filesender.rnp.br. When it exceeded 80%, the system started to refuse the upload of some files until, with 88% of storage utilization, it started to refuse all of them.

In the service logs, we collect the following:

```
[2023-08-22 10:52:37] [user 3233] [rest:error] [StorageNotEnoughSpaceLeftException exception uid:64e4bda5a77f0] storage_not_enough_space_left
[2023-08-22 10:52:37] [user 3233] [rest:error] [StorageNotEnoughSpaceLeftException trace uid:64e4bda5a77f0] #0 /opt/filesender/classes/rest/RestServer.class.php(306): RestEndpointTransfer- >post()
[2023-08-22 10:52:37] [user 3233] [rest:error] [StorageNotEnoughSpaceLeftException trace uid:64e4bda5a77f0] #1 /opt/filesender/www/rest.php(37): RestServer::process()
[2023-08-22 10:52:37] [user 3233] [rest:error] [StorageNotEnoughSpaceLeftException trace uid:64e4bda5a77f0] #2 {main}
[2023-08-22 10:52:37] [user 3233] [rest:error] [StorageNotEnoughSpaceLeftException details uid:64e4bda5a77f0] required_space = 0
```

The message points to disk overflow, but the disk still had 700GB free.

We saw that there are the following directives with a default value:

These directives are currently defaulted:

- storage_usage_warning = 20
![image](https://github.com/filesender/filesender/assets/15300032/f64fb1bc-e2ec-4756-a217-80e8f8ef5903)

- storage_filesystem_ignore_disk_full_check = false (neste caso, não é ignorado!)
![image](https://github.com/filesender/filesender/assets/15300032/63636a4e-ec0c-45b8-81b6-c7a5108bd358)

Is this behavior a result of these directives, can you give us more details please?

**Comment by WebSpider** [comment]
The behaviour here is a bit dependant on your backend storage.

During uploads:
- filesystem: If there is not enough free space left to store one chunk (`chunk_size` parameter) you will get this error
- filesystemChunked: If `storage_filesystem_ignore_disk_full_check` is False, you will get this error if there is not enough free space left to store one chunk

Also, in general, you need to have enough space in the backend storage to store the entire transfer. This check is performed when you create the transfer, so before starting the actual upload.

**Comment by monkeyiq** [comment]
The `storage_usage_warning` appears to be a blunt instrument that you have enough storage. The default 20 should take 20% of the total storage available as a threshold. If you have more than that 20% as free space then disk full calculations in cron.php and the stats page are avoided. That you say things started becoming a problem after 80% I think is very suspicious that the full calculations might have some issue.

The statistics page should give some idea of what FileSender is thinking you have as total, used, and free size. If these values are what you are expecting then I can direct investigation to other parts of the code.

There may be a difference between what `df` reports as free and what FileSender is calculating. Does the filesystem have any reserved space for root only? If the shown free space makes sense from FileSender/stats then this shouldn't be the isssue.

**Comment by monkeyiq** [comment]
I'm guessing I'll have to fill up an instance and see how it degrades.

**Comment by WebSpider** [comment]
@ruan-oliveira is this still an issue for you? Could you provide us with feedback?

**Comment by WebSpider** [comment]
Timeout.
