### ISSUE TITLE
Only allow access for users in certain group (or email domain)

### ISSUE THREAD

**Issue by jwellner** [filesender/filesender#1541]
Using OIDC for authentication, I am looking for a way to grant access only to users in a specific group.

I can see that it's possible to grant admin privileges using `auth_sp_saml_admin_entitlement`. Is there a way to restrict login access to users with a specific entitlement as well?

Is there a straightforward way to achieve this?

**Comment by monkeyiq** [comment]
I have not used FileSender with OIDC for login. It looks like maybe you are using the SAML code in FileSender to login with OIDC?

The user login attempt could be blocked based on attributes from the login session. There is an existing config.php directive `auth_user_filter` which is unfortunately undocumented at the moment.  It appears to have either a attribute:value assertion or be able to be directly called as a php function.

https://github.com/filesender/filesender/blob/0c280ee45ae6aa90f7e17aa8ca72972ae3cde73b/classes/auth/Auth.class.php#L187

Does that look like it might allow matching against the group attribute info you have?

**Comment by jwellner** [comment]
Thanks I will have a look at this!

**Comment by WebSpider** [comment]
Has this solved the issue for you?
If it did, would you be willing to share a documentation update, so others can use this as well?

**Comment by WebSpider** [comment]
Timeout.
