### ISSUE TITLE
feature request: filesender cli client to accept folders and maintain the file structure?

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1549]
Hi team, is it possible to add a feature where filesender cli client to accept folders and maintain the file structure?
Cheers

**Comment by monkeyiq** [comment]
I like this idea.

**Comment by WebSpider** [comment]
Yeah I do as well. 
Looking at #1553 it seems that more people are after feature improvements of the CLI client

**Comment by madsi1m** [comment]
Hi here are some improvements on @PaulLocksley's merge: https://github.com/filesender/filesender/pull/1556 hope you all don't mind
