### ISSUE TITLE
Can't download a zip/tar archive with lots of files

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1557]
Found a bug where i hit URI length too long when i want to download a zip of 1000 files.
Can we change this to a POST and/or make the assumption if nothing is ticked make it download everything?

**Comment by WebSpider** [comment]
This seems to be a duplicate of #1483
What version did you run into this bug?

**Comment by monkeyiq** [comment]
The `download_page.php` should have `dlarchivepost` about 25 lines from the end. The HTML element is key as I added it at the same time as the POST update so if it is there it will indicate if it may be a bug in the current updated code. On development I see a POST to `download.php` when grabbing the archive on the download page.

**Comment by madsi1m** [comment]
@WebSpider I'm in 2.38, seems it is fixed in 2.41.
Testing from development branch I don't see any problems
