### ISSUE TITLE
Cannot load PHP session with a specific ID

### ISSUE THREAD

**Issue by maaritlinnekoski** [filesender/filesender#1560]
PHP version 7.4,  Filesender version 2.41 SimpleSamlphp version 1.19.7 running in Docker container. Authentication seems successful, but PHP session loading fails with error: logon_url: '<br />
<b>Fatal error</b>:  Uncaught SimpleSAML\Error\Exception: Cannot load PHP session with a specific ID. in /opt/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:270
Stack trace:
#0 /opt/simplesamlphp/lib/SimpleSAML/Session.php(370): SimpleSAML\SessionHandlerPHP-&gt;loadSession('76f1d21e36a169e...')
#1 /opt/simplesamlphp/lib/SimpleSAML/Session.php(285): SimpleSAML\Session::getSession()
#2 /opt/simplesamlphp/lib/SimpleSAML/Auth/Simple.php(53): SimpleSAML\Session::getSessionFromRequest()
#3 /opt/filesender/classes/auth/AuthSPSaml.class.php(273): SimpleSAML\Auth\Simple-&gt;__construct('default-sp')
#4 /opt/filesender/classes/auth/AuthSPSaml.class.php(198): AuthSPSaml::loadSimpleSAML()
#5 /opt/filesender/classes/auth/AuthSP.class.php(84): AuthSPSaml::logonURL(NULL)
#6 /opt/filesender/www/filesender-config.js.php(150): AuthSP::logonURL()
#7 {main}
  thrown in <b>/opt/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php</b> on line <b>270</b><br /> Cookie with id 76f1d21e36a169e... is saved and has HttpOnly=true and Secure = true and SameSite = none. 
[filesender.log](https://github.com/filesender/filesender/files/12865559/filesender.log)
[simplesamlphp.log](https://github.com/filesender/filesender/files/12865703/simplesamlphp.log)

**Comment by WebSpider** [comment]
Can you please attach some more information:

- Relevant entries from filesender log (usually in /opt/filesender/filesender/log/)
- Relevant entries from simplesaml log (usually in /opt/filesender/simplesaml/log/

**Comment by maaritlinnekoski** [comment]
I uploaded debug logs. After successful login and valid session found there is session not valid because we are not authenticated?
Oct 11 02:02:44 simplesamlphp DEBUG [64e849ec9d] Session: doLogin("default-sp")
Oct 11 02:02:44 simplesamlphp DEBUG [64e849ec9d] Session: Valid session found with 'default-sp'.
Oct 11 02:02:44 simplesamlphp DEBUG [64e849ec9d] Session: Valid session found with 'default-sp'.
Oct 11 02:02:44 simplesamlphp DEBUG [6393537bd2] Session: 'default-sp' not valid because we are not authenticated.
Oct 11 02:02:44 simplesamlphp DEBUG [8d9c8b9ab3] Session: 'default-sp' not valid because we are not authenticated.
Oct 11 02:02:45 simplesamlphp ERROR [TReb33916d] Error loading session: Cannot load PHP session with a specific ID.
Oct 11 02:02:45 simplesamlphp DEBUG [64e849ec9d] Session: Valid session found with 'default-sp'.
Oct 11 02:02:45 simplesamlphp DEBUG [64e849ec9d] Session: Valid session found with 'default-sp'.
Oct 11 02:02:48 simplesamlphp DEBUG [513ecb96fd] Session: 'default-sp' not valid because we are not authenticated.
Oct 11 02:02:48 simplesamlphp DEBUG [ab380023a4] Session: 'default-sp' not valid because we are not authenticated.

**Comment by maaritlinnekoski** [comment]
Yes, I have tested with Chrome, Firefox and Edge and same error when using private browsing or incognito window.

**Comment by monkeyiq** [comment]
When you are trying to login do you see the `simplesaml/module.php/core/loginuserpass` URL appear in the web console / network? I see two cookies in flight there SimpleSAML and SimpleSAMLAuthToken. 

The subsequent visit on `filesender/?s=upload` I see the PHPSESSID, SimpleSAML, and SimpleSAMLAuthToken. The value received from the loginuserpass is the one sent to `filesender/?s=upload`

The filesender.config is undefined is also not good. The user quota bar might not be an issue but if there is an issue with filesender.config in the browser then it will be effecting other things. If you visit `.../filesender/filesender-config.js.php` on your server do you receive a valid looking JSON output. If there is an issue in your `/opt/filesender/config/config.php` then that can cause the filesender-config.js.php to be malformed, usually in the form that it just stops at some line.

**Comment by WebSpider** [comment]
Closing due to lack of response
