### ISSUE TITLE
`DirectoryIterator::__construct: failed to open dir: No such file or directory'`

### ISSUE THREAD

**Issue by multimeric** [filesender/filesender#1567]
I've hit an error that reliably occurs when I try to upload a file via the REST API. The request to `PUT /file/{file_id}/chunk/{offset}` succeeds, but then the request to `PUT /file/file_ID` fails with the error:
```
DirectoryIterator::__construct(/eos/aarnet-cloudstor/cloudstor/data/filesender/files/v2/743d87a3-e10c-4e6c-9dec-72daabe46624): failed to open dir: No such file or directory'
```

This error doesn't occur when uploading the same file via the web interface, so evidently I'm doing something wrong with my API calls, but it's not clear to me exactly what that is.

**Comment by monkeyiq** [comment]
Do you have a request payload of `{complete: true}` for that PUT /file/file_ID call? It seems the rest server is expecting that to be there. Otherwise a bit more digging will be needed.

**Comment by multimeric** [comment]
Yes, that was the PUT body. But it turns out that this happened because the preceding `PUT /file/{file_id}/chunk/{offset}`  *was* failing, and I just wasn't catching the error correctly.
