### ISSUE TITLE
UI3: Logoff button in the menu?

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1574]
(I1) As it is security related I again mention the potential security issue
having logoff only offered in account settings.

**Comment by WebSpider** [comment]
In previous UI related talks, the thought was to ask this from the UX designer, if this could/should be changed
In last UI related talks, the assumption was that no feedback was to be expected from the UX designed before end of year due.

@meijer what's the current take on this?

**Comment by monkeyiq** [comment]
I have brought it back again. We can remove it again if we want to go that way.
