### ISSUE TITLE
UI3: password entry

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1581]
(u2) Encryption option seems a little hidden. Using a generated
     password seems to be reduced in presentation. No ability to
     input a password without it being seen.

**Comment by monkeyiq** [comment]
I guess the last part is the core: if we care that you can not enter a password without it shown on the screen.

**Comment by WebSpider** [comment]
We should pick a sane default here: to me, passwords are hidden, unless the user chooses to make them visible, with a little icon next to it.

**Comment by monkeyiq** [comment]
I agree that this is the default interaction method I have seen across a range of sites. I don't think too many people will be annoyed if they have to click a reveal button to show the password text as on other sites.

**Comment by monkeyiq** [comment]
If we move to the hidden by default and reveal button (which is also what 2.x does) we can always move back away from that if it is seen as bad UI design.

**Comment by monkeyiq** [comment]
I have made this shown by default as we don't know if we are going to prune it for design reasons at this stage.
