### ISSUE TITLE
UI3: Maybe explain upload size vs quota in Transfer completed display

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1585]
* (u6) Transfer completed, maybe confusing to users to see "Total
     size 7.8 MB/46.6 GB" We know the 46gb is a quota but users
     have to figure that out. Spacing is also very condensed in the
     actual numeric data.

**Comment by monkeyiq** [comment]
I guess this one comes down to if the board wants to change things.

**Comment by WebSpider** [comment]
Maybe if we replace the '/' with '. Did you know you can send files up to {}?'

**Comment by monkeyiq** [comment]
I am thinking that moving the limit and quota information to another line might make sense. It is much less useful information, mostly the user doesn't care unless they add 2000 files and can only have 1000 in a transfer. Or they add 50gb and are over storage quota. Both of those things should be indicated on the first page of the upload process and are uninteresting during the upload itself.
