### ISSUE TITLE
UI3: Adding 300 files takes a while and a while to start. May be unrelated      to this PR.

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1587]
* (u8) Adding 300 files takes a while and a while to start. May be unrelated
     to this PR.

**Comment by WebSpider** [comment]
Is this maybe related to https://github.com/filesender/filesender/pull/1490 ?

**Comment by monkeyiq** [comment]
It takes around 10 seconds to start for 300 files. This is somewhat similar in the development branch so I am closing this as being attached to the development3 / ui3.
