### ISSUE TITLE
UI3: Code details - hiding options

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1612]
(code38) The ability to hide options with config seems to work but can not be tested without options  being saved to database. For example setting available=false in https://github.com/filesender/filesender/blob/development/docs/v2.0/admin/configuration/index.md#transfer_options

**Comment by monkeyiq** [comment]
With current development3 setting available=false removes an element from the list in the UI.

```
$config['transfer_options'] = array(
...
        'email_upload_complete' => array(
            'available' => false,
...
```
