### ISSUE TITLE
UI3: Code details - Saving passwords

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1614]
(code37) Using a generated password is not correctly handled. Should avoid pbkdf2 when generated and be recorded in the database as such. Must set and respect password_version and password_encoding.

**Comment by monkeyiq** [comment]
There are also a lot of things in the javascript that still use encryption_password_container_generate_again as a checkbox. That element no longer exists so the code using that is now somewhat undefined.

**Comment by monkeyiq** [comment]
err encryption_use_generated_password rather. but both elements are still actively used in the javascript and have been stripped from the template.

**Comment by monkeyiq** [comment]
More information is here https://github.com/filesender/filesender/pull/1672
