### ISSUE TITLE
UI3: Code details - Choose how to inform recipient

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1621]
(code32) When $show_get_a_link_or_email_choice = false the default is not to select  "an email" which is the only option and so the "to" is not shown.
If you just click next and send it you get a link which should be explicitly prohibited. For example, a guest who should not be able to do that and only "send to me".

**Comment by monkeyiq** [comment]
You can no longer just click next to proceed. I have made https://github.com/filesender/filesender/pull/1669 to select the email option if get a link is not available. This avoids the confusing situation of a user having to select the one option that is available. Note that this the original functionality would default to get a link which should not be available. Now get a link is not shown and the email option is selected for the user. Before 1669 you could not proceed without selecting something so this was technically addressed but the 1669 makes for a more streamlined user experience as well.
