### ISSUE TITLE
UI3: Code details - Inconsistent options for show_get_a_link_or_email_choice

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1622]
(code31) When $show_get_a_link_or_email_choice = false; then the page only shows email at top as expected but "get a link" is still shown in the transfer options and can be set to true or false.

**Comment by monkeyiq** [comment]
I think there was a related item which got this. Something like the guest upload with to me only. At any rate forcing this to false works as one would expect at the current head of development3.
