### ISSUE TITLE
UI3: Code details - Legacy upload removed

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1625]
(code28) Use of LegacyUploadProgress has been removed.

**Comment by monkeyiq** [comment]
Some of the legacy items might not be a huge deal. Some have been legacy items since pre 2.0 so these days might be something nobody will miss.

**Comment by meijer** [comment]
@WebSpider: is it the use of LegacyUpload or LegacyUploadProgress that no longer works? 

Iirc legacyUploadProgress was implemented to support browsers that didn't do WebWorkers. Something like that. LegacyUpload was implemented to provide a graceful fallback to browsers that didn't support html5 upload. If we effectively no longer have browsers that have that problem, we could a. ignore this issue and b. contemplate removing legacy-upload support. Thoughts?

**Comment by WebSpider** [comment]
@meijer i would have to double check in the original issue which listed all the differences. Will get to that probably tomorrow.

**Comment by peter-** [comment]
I would imagine it to be difficult finding a web browser that's still maintained (current TLS versions, kept up-to-date with security fixes, etc.), supports the required JavaScript APIs for FileSender to work in general but doesn't support HTML5 uploads?  
So maybe there's even more that could be removed.

**Comment by WebSpider** [comment]
To answer the question, it's LegagyUploadProgress that no longer works.

I agree with @peter- here that we should have a look if keeping this code around still makes sense.

**Comment by monkeyiq** [comment]
I'm happy for it to be trimmed off.

**Comment by monkeyiq** [comment]
FileReader should be there these days.
https://developer.mozilla.org/en-US/docs/Web/API/FileReader
