### ISSUE TITLE
UI3: Code details - Missing functionaltity

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1629]
templates/user_page.php

(code24) The following items don't seem to do any thing
  Use transfer settings from previous upload as default settings for next transfer.
  Save email recipients from past use (used to automatically complete email fields).

**Comment by monkeyiq** [comment]
I guess short term we could hide these elements so if folks deploy a beta it is less confusing to the users.

**Comment by monkeyiq** [comment]
This is resolved with https://github.com/filesender/filesender/pull/1701 and I will track the use of the saved transfer settings in https://github.com/filesender/filesender/issues/1596
