### ISSUE TITLE
UI3: Code details - Use translatable language strings

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1636]
templates/guests_table.php
(code17) The title attribute of remind and forward is raw english text. Use tr:forward et al instead. This triggered a broad general comment instead of explicitly noting each occurance.

**Comment by monkeyiq** [comment]
There is already one issue https://github.com/filesender/filesender/issues/1652  mentioning translation strings. I think I will close this one and leave the other as the generic find and fix issue.
