### ISSUE TITLE
UI3: Code details - Alter guest filtering for table

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1637]
templates/guests_table.php
(code16) if a guest is closed then they are not shown in the table which makes the
guest->status == 'available' test seem a little strange. This is because the table
explicitly steps through only the "filtered" guests. Either allow closed guests
to be shown or explicitly filter at the database level with fromUserAvailable from guests.

**Comment by monkeyiq** [comment]
The page has been moved to using fromUserAvailable(). If that filtering is not sufficient I propose an extension to fromUserAvailable or a new method like it instead of filtering database results in 4GL
