### ISSUE TITLE
UI3: Code details - Use placemarkers

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1647]
templates/download_page.php
(code6) {tr:transfer_expires_in} <?php echo $days_to_expire ?> {tr:days} can be better handled
    using placemarkers.
    eg passing
        return array(
            'total' => $quota,
            'used' => $used,
            'available' => $quota ? max(0, $quota - $used) : null
        );
    to    
    echo Lang::tr('quota_usage')->r($usage)
--> Assume this for all mixed mode translations.

**Comment by monkeyiq** [comment]
This one kind of had the solution right in the problem description.
