### ISSUE TITLE
No RateLimitHistory cleanup

### ISSUE THREAD

**Issue by yent** [filesender/filesender#1677]
It appears that there is no cleanup task for the RateLimitHistorys table, we accumulated over 10M records over the last 8 months, far from crashing the server but still ...

As we are using the defaults rate limits that are daily based I am going to setup a simple cleaning cron but this should be handled by the cronjob according to the config ...

**Comment by monkeyiq** [comment]
I will take a look at expanding the system cron job to include this.

**Comment by monkeyiq** [comment]
I made the default a little conservative of 31 days. Just in case rate limiting is relaxed to X items per week or 2 week block etc in the future. This also gives some scope to investigate rate limit violations in the last month.
