### ISSUE TITLE
Feature Request: Reminder emails via cron job

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1679]
Hi is it possible to add a feature that emails users that a transfer is going to expire in x days (default to 7) via cron tasks?

**Comment by monkeyiq** [comment]
I like this idea. Perhaps too we can also consider how many downloads have happened for the transfer, if there is one recipient and there are zero downloads it is probably more urgent than if there is one recipient and one download. Or less than n downloads for n recipients.

**Comment by monkeyiq** [comment]
The `Transfer::sendAutomaticReminders()` in cron.php seems along these lines. The `transfer_automatic_reminder` config option is undocumented at the moment it seems. I'm reading over the code now.

**Comment by monkeyiq** [comment]
I have only tested that with a few local transfers. Used a setting of `20` and got some notifications. Made a new transfer and downloaded it before the cron job and didn't receive a redundant notification.

**Comment by monkeyiq** [comment]
another configuration option dragged kicking and screaming out of the void!

**Comment by madsi1m** [comment]
nice!
