### ISSUE TITLE
Download events consolidation

### ISSUE THREAD

**Issue by yent** [filesender/filesender#1680]
We have a case of (mainly mobile) downloaders generating large number of download events due to network lag spikes and connection losses. Last case, a user started to download a 17Gb file while roaming ... Over the next 4-5 days this generated about 50 download start events, over 1300 download end events and a staggering 9500+ download resumed events, all interleaved and with different ip addresses of course ...

This lead our statistics system to this over 22Tb was downloaded, since it looks at the download ended events.

We considered to have it look at the smallest between download starts and download ends but this is not reliable.

So we thought that having some sort of auditlog-logged transaction identifier attached at download start and kept when resuming would be useful to identify bogus downloads and count them as one. 

I will soon do a pull request on that matter :)

**Comment by yent** [comment]
Pull request is here #1681

**Comment by monkeyiq** [comment]
Let me know if you are happy for me to remake the above PR against development. 

Thanks for the contribution!

**Comment by monkeyiq** [comment]
You fix is merged. Thank you. This will be ported to the 3.x series as well as I am keeping the two relatively in sync for features and code (other than UI).
