### ISSUE TITLE
UI3: Guest made with get a link bad interaction

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1686]
When you create a guest with get a link only the email option is shown on page 2 of the upload stream. Such a guest can not upload a file :/

**Comment by monkeyiq** [comment]
FileSender 2.x does allow you to set get_a_link for a guest and then they can upload to obtain a link. One may say it is risky to allow that but it is a feature that was there. We should either disallow making guests with get a link or allow those guests to upload successfully.

**Comment by WebSpider** [comment]
This feature is in use by installations, and appreciated.

Having guests upload using a link, is usually combined with 'can only send to me' in the installations that I know of.

**Comment by monkeyiq** [comment]
The interaction above is when you set a transfer option so the guest can only get a link when they upload. This is done in the "Created transfers options" on the lower right panel when making a guest. It requires that a user trust the guest. But it is an option. When making a guest select "Get a link instead of sending to recipients" which will alter the upload time option when the guest is uploading a file rather than the options at *guest creation* time. Yes these options are a little conflated and one has to keep in mind that it is the option that will be in play when the guest is uploading rather than when the guest is being made.

**Comment by monkeyiq** [comment]
I have made a few updates in https://github.com/filesender/filesender/pull/1690 to allow this interaction to work as expected. 

Now you can invite a guest using their email. The guest gets an email with a link to filesender in it. The guests visits the site, picks a file, clicks next. Then the "email" type is default selected and they can enter who to send it to and complete the upload.

The get a link option we had before allowed the guest to upload and get a http link to the uploaded file. It is probably a bit less used and more risky to allow a guest to have this option. 

From a security point of view there isn't a huge gain over allowinga guest to "get a link" as a nefarious guest could use two burner emails addresses. One to get invited to the system and then use the second to send the file to. (then they have a link to the download page). The defence to that is the "can only send to me" option which seems like a very sane option for inviting a guest to collaborate.

**Comment by monkeyiq** [comment]
I guess I'm looking to trim dead end situations at this stage. Having the UI not allow the user to progress.

If we want to have some other policy choices then they could be added as new github issues.
