### ISSUE TITLE
filename with   '+' in the name can not been sent

### ISSUE THREAD

**Issue by Meindert-van-den-berg** [filesender/filesender#1714]
Trying to send a file with a '+' in the name, example:   this-is-a-tar-file+.tar  does not enlighten the send-button.
With filesender 1.6.1 this is no problem. With filesender 2.41 it is not possible.

**Comment by WebSpider** [comment]
A config settng is available for this:
https://docs.filesender.org/filesender/v2.0/admin/configuration/#valid_filename_regex

**Comment by Meindert-van-den-berg** [comment]
I have adjusted the config setting. Now it works. Thanks.
