### ISSUE TITLE
Drag and Drop limitations

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1715]
We've found out on our filesender 2.41 install that in chromium-based browsers, the amount of files that can be added per drag and drop action when starting a new transfer on the upload screen seems to be limited to 100.

We've seen this behavior on:
- Chromium
- Brave
- Edge

But dragging and dropping up to 1000 files works flawlessly on Firefox

**Comment by monkeyiq** [comment]
In Chrome on the latest 3.x beta I can add 300 files OK. So it seems code based rather than browser based.

**Comment by monkeyiq** [comment]
Hmm, the 2.x series at the latest development is allowing 300 files added using Chrome on Linux.

**Comment by monkeyiq** [comment]
Checking out filesender-2.41 it also allows 300 in Chrome on Linux. Time to try other platforms here I guess.

**Comment by monkeyiq** [comment]
This is also on Chrome 115.0.5790.102 (Official Build) (64-bit). I should update that and see if anything changes

**Comment by monkeyiq** [comment]
Works as well on 2.41 and Chrome 119.0.6045.159 (Official Build) (64-bit) Linux

**Comment by monkeyiq** [comment]
I can also D&D 1000 files on 2.41 and Chrome 119.0.6045.159 (Official Build) (64-bit) Linux. I was using a 300 file sample before.

**Comment by monkeyiq** [comment]
ok 1000 files works in Brave on Linux. I'm guessing this is platform related and I'll have to test windows out with these browsers.

**Comment by WebSpider** [comment]
We have tested this on Mac and Windows.
On Linux it appeared that drag and drop didn't work at all, but that could have been a security setting in the OS

**Comment by adminnr1** [comment]
Did you try to drag&drop 1000 files while dragging a folder with 1000 files (so not dragging 1000 files)? That seems to be the problem

**Comment by monkeyiq** [comment]
I see. Drag and drop of the directory only shows 100 files. Selecting the 1,000 files and D&D them at once gives all files.

I now have an isolated and reproducible bug :)

**Comment by monkeyiq** [comment]
This has now also been released.
