### ISSUE TITLE
PHP 8.3+ compatibility

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1717]
php 8.3.0 is out, having a very quick look it seems like get_class() with no args will be removed some time in a future release.

https://php.watch/versions/8.3/get_class-get_parent_class-parameterless-deprecated

https://github.com/search?q=repo%3Afilesender%2Ffilesender+get_class%28%29&type=code

**Comment by monkeyiq** [comment]
It looks like Fedora 39 updates still only has php 8.2. From m.aar / pub/fedora/linux/updates/39/Everything/x86_64/Packages/p/

**Comment by madsi1m** [comment]
some fixes: https://github.com/filesender/filesender/commit/e7493a117a7e6c2f75b73fa6687b179a5cbbe525

be interesting to see how unit tests do as they call get_class() a lot

**Comment by StCyr** [comment]
beware that you ran composer on php-8 and that you've dropped the following in filesender 2.43:lib/vendor/composer/platform_check.php:

```
if (!(PHP_VERSION_ID >= 80100)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 8.1.0". You are running ' . PHP_VERSION . '.';
}
```

for some reason it prevents users from downloading multiple files as a single zip/tar file

**Comment by monkeyiq** [comment]
I'm looking at the unit tests. It seems although there are a bunch of calls they all happen inside a non static member function. As such it seems that there moving to `get_class($this);` maintains wide php comparability while also being php 8.x and 9 safe.

**Comment by monkeyiq** [comment]
It seems we don't have any raw `get_class()` anymore?

**Comment by madsi1m** [comment]
this should fix @StCyr issue above https://github.com/filesender/filesender/pull/1735
