### ISSUE TITLE
S3: Guest transfers end up in generic bucket when daily buckets are in use

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1718]
While migrating a previously NFS-based install to S3, we encountered some unexpected behavior.

FileSender version: 2.40

Related configuration settings:
```php
$config['cloud_s3_use_daily_bucket'] = true;
$config['cloud_s3_endpoint'] = 'https://custom-swift-endpoint';
$config['cloud_s3_key'] = 'secret';
$config['cloud_s3_secret'] = 'even_more_secret';
$config['cloud_s3_bucket'] = 's3_bucket';
$config['cloud_s3_region'] = 'XX';
$config['cloud_s3_bucket_prefix'] = 's3_prefix';
```

## Behavior ##
New guest vouchers end up with the value of `cloud_s3_bucket` in as their S3 storage location, which is odd, since `cloud_s3_use_daily_bucket` is enabled.

## Expected behavior ##
We expect that guest transfers get stored together with non-guest transfers, at a location named by the `cloud_s3_bucket_prefix` and the date-code.

Possibly related: #1411

**Comment by monkeyiq** [comment]
I haven't tested https://github.com/filesender/filesender/pull/1719 against my local fake S3 yet. It should use the same bucket naming logic for both authenticated and guest users.

**Comment by WebSpider** [comment]
Just confirming, I still have to test this new behaviour.
