### ISSUE TITLE
3.0b5: Allow configurable transfer expiry settings

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1720]
Ever since #1709 the minimal transfer validity is 45 days.
For some installs this almost doubles the currently configured maximum, without the possibility to lower this, without causing FileSender to report an unrecoverable error.

Please make this more flexibily configurable (both UI and back-end), so moving to FS3.x doesn't cause the application to grow in storage footprint

**Comment by monkeyiq** [comment]
It might make more sense to remove items from the fixed choices in the drop down if they are not valid for the configured minimal transfer validity.
