### ISSUE TITLE
Issue with cron job

### ISSUE THREAD

**Issue by drudich** [filesender/filesender#1721]
I recently upgraded to version 2.42 and I got the following error after a cron job ran:

/etc/cron.daily/filesender:
PHP Warning:  Undefined variable $tr in /path-to-filesender/classes/utils/Lang.class.php on line 482
PHP Warning:  Trying to access array offset on value of type null in /path-to-filesender/classes/utils/Lang.class.php on line 482
PHP Warning:  Undefined variable $tr in /path-to-filesender/classes/utils/Lang.class.php on line 482
PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /path-to-filesender/classes/utils/Lang.class.php:482

**Comment by WebSpider** [comment]
Do you have anything in your /path-to-filesender/logs/filesender-date-of-today.log?

**Comment by monkeyiq** [comment]
To try to work out exactly where this is coming from, would you mind adding the following about live 482 of Lang.class.php and attaching the final lines matching "AAA trying" from your filesender logs?

```
        Logger::error("AAA trying to translate id $id ");
```

I think that the cron job defaults to config['default_language']  which is `en`.

At any rate, if I can manage to get an undefined $tr here it will help to make a precision fix.

**Comment by drudich** [comment]
@WebSpider  - this error is in the log file from the time that I got the cron job error:

`[2023-12-02 07:38:53] [cron:warn] No translation found for report_event_transfer_decrypt_failed in en language`

@monkeyiq  - I added that line to the Lang.class.php.  I'll send over the logs next time I see the cron error again.  It has only happened once so far (on 12/2/2023) so I'm not sure if it's a once a week job that's failing?

**Comment by monkeyiq** [comment]
After some digging I found where the report was being made that used this translation and could reproduce the issue. I have added the offending term to poeditor and imported it in https://github.com/filesender/filesender/pull/1724

If you add the new line to the [language/en_GB/lang.php](https://github.com/filesender/filesender/pull/1724/files#diff-fe509caa5cdd627bac580ddbec105439b4f232bea475fa6f66cffe037c19ad1c) and possibly the en_au file you should see that issue disappear.

The instance I saw was only triggered when an encrypted transfer has expired and a user has tried and failed to download a file from it. Though there may be other ways to get there, that is the one I found that I could do an A/B test with.

**Comment by monkeyiq** [comment]
Thanks for reporting the issue!

**Comment by drudich** [comment]
Thank you for addressing it so quickly!
