### ISSUE TITLE
db: default medium sized int in MariaDB to be int (4 bytes) instead of medium (3 bytes)

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#174]
For the sake of an extra byte per tuple the limits would be much harder to bump into for installations. The postgresql backend already converts a 'medium' request to an integer type (4 bytes).

**Comment by WebSpider** [comment]
Is this still relevant ?

**Comment by monkeyiq** [comment]
There was a case where the medium int limit was bumped into. Definitions still use the medium int (3 byte) definition and it has not been expanded to being a 32bit number in FileSender as yet.

I see that when using InnoDB storage (default and recommended for 10.2 [1]) that a medium int consumes 32 bits of storage anyway. https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-innodb
If that is the case then perhaps migration can be done without any serious data updates (assuming a site is using InnoDB already). Testing out the schema update on a largish table would be quite informative.

[1] https://mariadb.com/kb/en/choosing-the-right-storage-engine/

**Comment by WebSpider** [comment]
@monkeyiq I have a largeish install to test on, just give me a branch to test against :-)

**Comment by monkeyiq** [comment]
@WebSpider I'd imagine it is fairly easy to port 2.x/3.x. Which FileSender version is most convenient for your current testing?

**Comment by monkeyiq** [comment]
There are also a number of foreign keys to these medium integers :/ For initial testing I am dropping those FK's at the top of the database script but I hope to find a slightly more subtle way of doing the upgrade.

**Comment by monkeyiq** [comment]
FWIW this is where my patch is at currently https://github.com/filesender/filesender/pull/1225/files

I am not very happy with the dropping of the foreign keys in order for this update to work :|

**Comment by WebSpider** [comment]
> @WebSpider I'd imagine it is fairly easy to port 2.x/3.x. Which FileSender version is most convenient for your current testing?
Im currently testing 3.0alpha3

**Comment by monkeyiq** [comment]
The patch fairly easily ported over to development3 and is available at https://github.com/filesender/filesender/pull/1251

**Comment by WebSpider** [comment]
This has effectvely been done in referenced PR's
