### ISSUE TITLE
filesystemChunked and storage_filesystem_hashing are mutually exclusive

### ISSUE THREAD

**Issue by kdermody** [filesender/filesender#176]
When you turn on both storage_filesystem_hashing and filesystemChunked, storage_filesystem_hashing is ignored and a directory with the fileUID is created in the filesystem path. 

filesender-2.0-beta2

**Comment by monkeyiq** [comment]
I have just done some initial testing with https://github.com/filesender/filesender/pull/201 and the fileUID directory is now created inside the hashed path directories as it is for the default storage.

I am interested to know if using chunked files helps performance here over the seek and write method used by the default storage type. I might do some testing here to try to find out.
