### ISSUE TITLE
Error messages don't distinguish between an invalid csrf token and security token

### ISSUE THREAD

**Issue by multimeric** [filesender/filesender#1770]
There are seemingly two different security mechanisms in filesender, one of which uses the `Csrftoken` header, and the other of which uses `X-Filesender-Security-Token`. 

Here we can see that `$security_token_matches` is checking the `X-Filesender-Security-Token` header:
https://github.com/filesender/filesender/blob/fb0c6b11b82d17227dbed5faf80bf4d49cffc11b/classes/rest/RestServer.class.php#L172-L180

But then the error message makes it sound like it relates to the `Csrftoken`, with the message "rest_xsrf_token_did_not_match":
https://github.com/filesender/filesender/blob/fb0c6b11b82d17227dbed5faf80bf4d49cffc11b/classes/rest/RestServer.class.php#L288-L295

Maybe these two tokens are related in some way? But I still think it would be helpful to have a more precise error message here along the lines of `X-Filesender-Security-Token did not match`.

**Comment by monkeyiq** [comment]
I think it would be useful to be able to tell these apart too. Certainly it would help debugging an issue.

**Comment by monkeyiq** [comment]
Thanks for the report. 1798 should help work out which token is which.
