### ISSUE TITLE
Guest options incorrectly documented in the API

### ISSUE THREAD

**Issue by multimeric** [filesender/filesender#1772]
The docs suggest that the `POST /guest` endpoint accepts two top-level JSON keys called `options` and `transfer_options`:

https://github.com/filesender/filesender/blob/fb0c6b11b82d17227dbed5faf80bf4d49cffc11b/docs/v2.0/rest/index.md#L551-L552

However sending options in this format doesn't seem to actually work. In the actual JS client, we instead have a top-level key called `options` which contains `guest` and `transfer` instead:

https://github.com/filesender/filesender/blob/fb0c6b11b82d17227dbed5faf80bf4d49cffc11b/www/js/guests_page.js#L211

**Comment by monkeyiq** [comment]
I agree. The REST code is expecting data->options->guest and data->options->transfer. So the REST docs are out of date at the moment.
 
https://github.com/filesender/filesender/blob/5fadd092ed2894990791cf91ac9166ade1ba2d29/classes/rest/endpoints/RestEndpointGuest.class.php#L211
https://github.com/filesender/filesender/blob/5fadd092ed2894990791cf91ac9166ade1ba2d29/classes/rest/endpoints/RestEndpointGuest.class.php#L238

**Comment by monkeyiq** [comment]
Thank you for reporting the issue. Hopefully it is not slightly less confusing for the next folks looking to use the API.
