### ISSUE TITLE
Redirects are broken if "add_me_to_recipients" transfer option is unspecified

### ISSUE THREAD

**Issue by multimeric** [filesender/filesender#1773]
There seems to be a very strange bug originally noted in https://github.com/WEHI-ResearchComputing/FileSenderCli/issues/14, which happens under the following conditions:

* A guest is created at the `/rest.php/guest` URL
* One or more guest options are specified in the JSON body
* The `add_me_to_recipients` transfer option is unset

For example, the following API request demonstrates the behaviour:

```
{
    "recipient": "<SOME RECIPIENT>",
    "from": "<SOME SENDER>",
    "options": {
        "guest": {
            "can_only_send_to_me": false
        }
    }
}
```

This generates and sends a voucher request to the recipient, but after they upload, they get redirected to `/false&vid=a3cabb14-f52b-4b1e-9e18-e40c98f482d9`, and get an error that looks like this: ![Screen Shot 2024-01-12 at 12 45 17 pm](https://github.com/filesender/filesender/assets/5019367/8ae699a3-f059-4f7a-a0f9-4e76f1bfba0c)

If any of the above conditions are changed, for example the `add_me_to_recipients` transfer option is added, or the `guest` options key is removed, this error will not occur.

The actual cause of the error, as far as I can tell, is that it causes the hidden `<input id="redirect_url_on_complete">` element to have its value set to the string `false`, which then causes the wrong redirect. I'm not exactly sure how this happens as the client does a lot of complex things before that point.

**Comment by monkeyiq** [comment]
I could see that if there were no options and the transfer options was `[]` then I got that bad redirection. Making sure something is in that settings at guest creation time for guests created via the API enabled the expected behaviour. It is a bit messy feeling and perhaps we should use some more default options if nothing is supplied but https://github.com/filesender/filesender/pull/1786 is a move in the right direction in that it offers functional behaviour.

**Comment by multimeric** [comment]
Thanks, hopefully this fixed it!

**Comment by monkeyiq** [comment]
Let me know if it is still needing attention :)

**Comment by monkeyiq** [comment]
Please reopen if the issue still persists. This should be in the 2.45 release.
