### ISSUE TITLE
Guest vouchers: Guests sending transfers without recipients when 'add me to recipients' is ticked

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1774]
## Problem description
Guests can send a transfer without entering any recipients when 'add me to recipients' is ticked by the voucher sender. This causes guest senders to not realise the transfer did not end up at the intended recipient

## How to reproduce
1. Log in as a valid user on filesender
2. Create a guest voucher, and select 'add me to recipients', unselect 'can only send to me', send the voucher to an email address
3. As recipient of the voucher, open the voucher
4. Select a file to add to the transfer
5. 'Send' option is now available, and sends the transfer to only the intended recipient

## Solution
Add a message to confirm the guest intends to send without a recipient when:
1. 'add me to recipients' was checked in the voucher
2. 'only send to me' was unchecked in the voucher
3. the list of recipients is empty

**Comment by monkeyiq** [comment]
This should be resolved in 2.45. Please reopen if that is not the case for you.
