### ISSUE TITLE
cannot upload file, terasender error

### ISSUE THREAD

**Issue by Meindert-van-den-berg** [filesender/filesender#1778]
A person tries to upload a file. Got error "terasender source file not available".
Tried with Edge and Firefox.
Google give no clue. What is the problem?

![edge-terasender-error](https://github.com/filesender/filesender/assets/151514037/01211f7c-2281-4f63-a9b8-df8458da741d)
![firefox-terasender-error](https://github.com/filesender/filesender/assets/151514037/68a50182-f1ba-4a4c-bdb8-4124e21828df)

**Comment by WebSpider** [comment]
Does the user have permissions to open and read the file?

**Comment by Meindert-van-den-berg** [comment]
Yes he can.

**Comment by WebSpider** [comment]
I've looked at the source-code, and there are several possibilities, most of them are related to encryption.
Can you see if this person has attempted to send an encrypted file, and if he did, can you see if this works without encryption?

Also, there should be more details in the javascript console of the sender's browser.

**Comment by Meindert-van-den-berg** [comment]
Yes the upload was encrypted. He did not try it unencrypted.
Unfortunately he can not reproduce the problem. Could it be that something was wrong on his laptop and a recent OS update did solve the problem? Or is  terasender server based?

So because the problem can not be reproduced consider this Issue as 'informational'.
Thanks for you help

**Comment by WebSpider** [comment]
> Yes the upload was encrypted. He did not try it unencrypted.
> Unfortunately he can not reproduce the problem. Could it be that something was wrong on his laptop and a recent OS update did solve the problem? Or is  terasender server based?
> 

Terasender is client-based. There could have been a memory situation on his OS/browser where the encryption or parts of it could not be performed. 

Good to see it was non-repetitive, I will go ahead and close the issue, feel free to refer to it should it happen again.
