### ISSUE TITLE
Move to a more recent UUID version

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1782]
Later UUID versions maintain a portion of random data to make guessing and collisions difficult but are prefixed with time information. This setup allows databases and btrees to more effectively index a set of UUIDs. This will help as the files are stored using the UUID from the database as file names or directory names and file systems may in general use btrees to index the file/directory names. This should lead to shallower btrees and less wasted cycles on the server.

**Comment by WebSpider** [comment]
These collisions are exactly the reason why daily buckets are used on s3, so awesome enhancement!

**Comment by monkeyiq** [comment]
Thinking about this a bit more today, maybe daily buckets would be a good enhancement for the filesystem based storage too. On the paper napkin test, as one site I know has 50k active users per day and perhaps they allow 30 days holding that would make a 1.5 million entry directory. Having 30 directories of 50k+ files would be much more efficient.
