### ISSUE TITLE
Allow getting cURL-able links

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#18]
The Download button uses JavaScript to start the download. This is great for encrypted files (these must be decrypted by JavaScript) but not so great for normal files.

Users may want to open the link to the download page on their desktop, but then do the actual download on another server using curl or wget, to avoid having to download a large file to their desktop, only to send it somewhere else.

**Comment by madsi1m** [comment]
We have already solved this on our installation. I did it by adding the download url next to the Download button for unencrypted files.

If you like i can add it as a pull request.

**Comment by thijskh** [comment]
This was already fixed at one point in the pre-1.x cycle. A functional test to prevent regressions would be nice...

**Comment by jornane** [comment]
Proposed a solution.

**Comment by madsi1m** [comment]
So did I, was something our users were asking for a while back, as they need to curl from clusters.
https://github.com/filesender/filesender/pull/20

**Comment by meijer** [comment]
The functionality is good to have. We now have two pull requests that do the same only slightly differently. I believe it's in the user's interest to see this possibility explicitly, as in: there's a link you clearly see in the UI. That's in @madsi1m 's pull request. @jornane 's request creates the URL all server side which when he explained it sounded like the better way to do that. @madsi1m and @jornane, could the two of you perhaps agree on one common pull request? I'll happily approve that.

**Comment by monkeyiq** [comment]
it seems that @madsi1m closed their PR a while ago. I'm lining up to merge https://github.com/filesender/filesender/pull/19 now and then update the disclaimer message to let folks know that right click + copy link works.
