### ISSUE TITLE
Display usage graph functionality

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#1801]
Good day,

I would like to be able to view monthly usage graphs on my FileSender instance. How can I achieve that. Is there a configuration directive that I can write in the configuration to have that functionality display in the admin dashboard.

Regards
Thuso

**Comment by monkeyiq** [comment]
The aggregate statistics might be what you are after. You will want to enable it with `aggregate_statlog_lifetime` and set who has access using something like `can_view_aggregate_statistics`.

**Comment by monkeyiq** [comment]
It may take a while for the statistics to be gathered. IIRC they are not calculated and stored if aggregate_statlog_lifetime is false.

**Comment by thuso607** [comment]
Alright. thank you.

**Comment by WebSpider** [comment]
If your question has been answered sufficiently, feel free to close this issue :+1:

**Comment by thuso607** [comment]
Good day,

I have configured aggregate statistics on my Filesender instance a month ago. Since I received information that the stats take a while to gather and display. I waited hoping they will display after a month but I’m still not finding any graphs on the aggregate statistics page. Any suggestions what might be the issue will be greatly appreciated.

**Comment by monkeyiq** [comment]
It might be that an issue was introduced into the code. Does your `aggregatestatistics` table contain any tuples?

**Comment by thuso607** [comment]
There is a table named aggregatestatisticsview with 6001 rows. There isn't aggregatestatistics tables on the list of tables

**Comment by madsi1m** [comment]
there is a AggregateStatistics table (case sensitive)
did you run/re-run the https://github.com/filesender/filesender/blob/development/scripts/upgrade/database.php

**Comment by thuso607** [comment]
Oh my bad, yes there’s AggregateStatistics table with 6546 rows. I ran the database script when I upgraded to the version I’m currently on, version2.45

**Comment by monkeyiq** [comment]
The table case names being different in mysql/pgsql has been around forever, eg, AggregateStatistics / aggregatestatistics naming. I could add a migration to database.php to make them both the same but it has never seemed like a large enough issue to force migration on people.

Does the following query reveal any data that looks like non zero / possibly real?
```
select * from AggregateStatistics order by epoch desc limit 100;
```
I am seeing various epochtype, eventtypes with low event counts (this is my dev testing db) but sizesums etc.
If there is data in the database then we can turn to the code that does the presentation as a possible issue...

**Comment by thuso607** [comment]
Yes the query shows that there's existing data in the database. see attached.
![image](https://github.com/filesender/filesender/assets/22442842/6c9988c0-5c76-4d42-9de8-0692a6fe5139)

**Comment by monkeyiq** [comment]
It looks like there is some data there. I have just taken another look at my setup and can see aggregate stats on 2.x (development branch) and 3.x (development3). I found a little issue which the above PR fixes.

If you open the web console do you see any errors when trying to load graphs? If you look at the network tab on the web console and the line for `aggregate-statistics-data-for-chart.php` do you see what might be valid JSON as the response?

**Comment by thuso607** [comment]
I do not have a network tab on my web console, how do I add it? which configuration directive do I add to have it

**Comment by WebSpider** [comment]
Is this question still relevant? If not, feel free to close the issue
