### ISSUE TITLE
new filesystem daily buckets and cron job deletion

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1807]
The cron job is not deleting the per day, and per hour directories for old expired transfers. A fix is merged that can remove the old ones left by 2.46.
-----
Original:
The cron job is not deleting all the files on expiration when the new 2.46 daily buckets option is in effect. An update will be coming, in the meantime please do not enable daily/hourly buckets.

**Comment by monkeyiq** [comment]
actually this is happening if the cron job is run as a different user who can not access the /opt/filesender/files and so the filesystem is found to be not writable. Some directories are still not deleted as one would expect. Still investigating.

**Comment by monkeyiq** [comment]
I now have some of the bucket directories being deleted in the cron too.

**Comment by monkeyiq** [comment]
I had been trying to get idea 1 to go last night. The code currently makes the directories as needed which is super convenient. But the delete code is triggering that creation code path after the empty directory has just been deleted. 

For example, you upload a file, alter the database to indicate it has expired and run the cron job. The cron job notices after deleting the file(s) that the directory is empty and deletes the directory. Something triggers the getpath() code on that file some time after that and it remakes the subdirectories in the background for you.

One idea I was discussing this morning is to use the code I have but only create the directories as needed if it is in the "active window". For example the last 3 days. Otherwise the paths are calculated but the directories are no longer automatically created by that code. 

Idea 2 is what I was thinking of moving to at the end of last night. Just check for subdirs matching `now - 60 days`  and delete ones matching the per day (and subdirs in per hour first) which are already empty.

**Comment by madsi1m** [comment]
perhaps add a flag to buildpath to only mkdir when it is called from writechunk?

**Comment by monkeyiq** [comment]
I have a prototype of idea 2 going now. It seemed cleaner to just work on old directories and leave the rest of the code without additional complication.

**Comment by monkeyiq** [comment]
I have merged an update. I'll be doing some more testing on that before the next release. The good part is that you can set a number of days to go back, so it can remove the empty directories that may have been left behind by using 2.46.
