### ISSUE TITLE
Config option to prevent creation of new uploads/vouchers

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#1808]
Specifically when performing a major version upgrade/migration it would be helpful to have a config switch that prevents new data from being added to an instance, specifically preventing the creation of new transfers and vouchers. This should not affect the continued availability of downloads, though.

That way, after `max_transfer_days_valid` (or the v3 equivalent thereof) has passed all existing transfers (and vouchers, I think) will have expired on their own, all the while new transfers/vouchers can potentially be created at a shiny new, separate, replacement instance.  
(For this to be effective this setting should also prevent the extension of transfer or voucher expiration dates.)

This differs from the [existing maintenance mode](https://docs.filesender.org/filesender/v2.0/admin/configuration/#maintenance) it not making the software effectively read-only ("all pages are replaced with the maintenance page"): It would prevent new data from being added to an to-be-decomissioned instance while downloads continue working until they expire.

N.B.: In light of the upcoming major v3 release this feature would specifially be appreciated if it were made available in v2. Bonus points if the implementation could easily be backported (by deployers) to rather old v2 releases that may be running in the field, in order to avoid having to update those old v2 instances to latest-v2 when all one desires is a migration to v3, leaving the old v2 instance to die.

**Comment by monkeyiq** [comment]
I have been trying to maintain database compatibility between v2 and v3. Normally the v3 alpha/beta release mentions which of the v2 series it is based on and that should allow specific v3 and v2 interfaces to share the same database and files storage. The plan I had in mind for migration was for a site to test a v3 interface against the same database and files and when deployment is desired to redirect users to the filesender 3.x version which should allow download of the old files uploaded in 2.x.

A read only option is another solution. Both would allow for a fall-back if something undesirable was happening.

Either way  there will be a little pressure on the v3 series from as when 3.0, 3.1, etc are released if new code is only added to the 3.x series and requires a database update then there will become a time when 3.x is no longer directly database compatible with any 2.x release. Though I guess the code could be cherry picked back to 2.x to allow a very late 2.x to remain compatible for an extended period. This would then mean the database cherry pick patch and the read only patch would need to be back ported to older 2.x releases if desired.

At the moment I am performing development against `development` in the 2.x series and then updating the `development3` periodically to accept the code from new 2.x releases. UI updates for the 3.x series and deps for 3.x are directly applied only to `development3` which can lead to merge clashes that need manual resolution. This work flow would mean that a "read only" mode would automatically be ported from 2.x to 3.x for future use.

**Comment by peter-** [comment]
Thanks for implementing "read only mode"! As you write above there might be a few occasions where having this is useful to the deployer outside of major version migrations.

> The plan I had in mind for migration was for a site to test a v3 interface against the same database and files and when deployment is desired to redirect users to the filesender 3.x version which should allow download of the old files uploaded in 2.x.

While that sounds like a nice feature we're still running an older v2.x release (cf. comments on list from deployers about not keeping current) and my current plan therefore involves leaving that system behind and migrating to v3 as if it were different software, *not* by appying a few dozen minor upgrades and migrations and translation/template updates in piecemeal fahsion (which would involve testing everything a few dozen times as well).  
I.e., I was hoping we could jump forward instead of having to now do the work we couldn't do over several years (since our last v2 update) all at once.

(Had we managed to keep our instrance up-to-date the ability to only swap out the UI would be greatly appreciated, of course.)

**Comment by monkeyiq** [comment]
This is in yesterday's release. Thank you for the idea. If there is anything else that can be done to help with migration to 3.0 please open a new issue and/or email the list.
