### ISSUE TITLE
PHP fatal error Ramsey in fresh FileSender installation

### ISSUE THREAD

**Issue by sT0wn-nl** [filesender/filesender#1816]
After going through the installation documentation for a new fresh installation I see the following error message in the NGINX logging:

2024/03/11 11:07:46 [error] 16140#16140: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Ramsey\Uuid\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /opt/filesender/filesender/lib/vendor/ramsey/uuid/src/Uuid.php on line 313" while reading response header from upstream, client: 94.210.119.94, server: xxxxxx, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9090", host: "xxxxx"

Versions I use are:
* Debian 11 
* NGINX 18.0-6.1
* PHP-FPM 2:7.4+76
* PHP 7.4.33-1
* MariaDB 1:10.5.23-0
* FileSender 2.47

Filesender only shows a 404 in the browser, does anyone know what is wrong here?

**Comment by sT0wn-nl** [comment]
.

**Comment by sT0wn-nl** [comment]
.

**Comment by monkeyiq** [comment]
this may be related to needing php8.

**Comment by monkeyiq** [comment]
since we have moved back to using uuidv4 only for now it is possible to move the Ramsey dep back to an older version that is php7 compatible.

**Comment by sT0wn-nl** [comment]
Upgrading to PHP version 8 fixed the problem!
