### ISSUE TITLE
UI3: Buttons in modal popups use old theme

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1851]
Buttons in modal popups (like transfer logs) should use fs-buttons or be themed to use the CSS vars, so that they all match

**Comment by monkeyiq** [comment]
I think the popups might still be using the code from the previous rewrite which was using bootbox to display menus with bootstrap.

**Comment by monkeyiq** [comment]
I have updated the shape in 1908. I assume to be colour matched it should go from being green/red in the dialogs to blue/red instead.

**Comment by madsi1m** [comment]
looks good
