### ISSUE TITLE
CLI client config download URL hard-coded to https://sam/filesender/

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#1856]
This came in with #1668:

https://github.com/filesender/filesender/blob/0170ed100bcd3b08996f3cb9ae432e08c66931c9/templates/user_page.php#L426-L428

Downloading the Python CLI client configuration from `https://sam/filesender/...` cannot possibly work outside of some test setup. Making it dynamic from configuration (assuming `site_url` always ends in a slash, as I think it should):

```diff
- <a href="https://sam/filesender/rest.php/user/@me/filesender-python-client-configuration-file" download="filesender.py.ini" >
+ <a href="{cfg:site_url}rest.php/user/@me/filesender-python-client-configuration-file" download="filesender.py.ini" >
```

By the way -- and this is not what this issue is about (though if reproducible it may be another issue):  
I think (but may be misremembering) I was able to get the CLI client configuration generated before after replacing `https://sam/filesender` with the correct hostname and path for my server but doing that right now only gives me a JSON error message (using `master3-filesender-release3.0.beta6`) in the same web browser I'm logged in to FileSender (in order to even see the download link):

```json
{"message":"rest_authentication_required","uid":"...","details":{"method":"get","endpoint":"user"}}
```

**Comment by monkeyiq** [comment]
I've updated the link on the user profile page to use site_url again. I can see how this might have happened since the old link was dropped and I was updating many things in the 3.x ui series at the time.

**Comment by monkeyiq** [comment]
The main place I can see this exception in the code path is right at the top of `RestEndpointUser.class.php/get()`.
rest_authentication_required -> RestAuthenticationRequiredException

I tried also dropping my user login from `$config['admin']` but I can continue to download the config file ok here. I checked out beta6 (7b1f762589608cf68df04638457698c42352e865) to make sure it can download the config (with manually updated link) here.

Could you please enable exception logging and verify which line is throwing `rest_authentication_required` from your /opt/filesender/log file?

**Comment by peter-** [comment]
> I've updated the link on the user profile page to use site_url again.

Thanks!

As to the exception: I think this was based on accessing my beta6 instance from a network where the client IP address frequently changes (together with using the Shibboleth SP this may have caused loss of session every couple of clicks). So this may in fact be fully unrelated to the software and I cannot reproduce the exception atm, neither with an unmodified beta6 nor with the download link manually changed. Sorry for the noise.

FWIW, I still had the log around from when the exception occurred, and it seems to confirm what you were expeting:

```php
2024-04-04T17:20:01.728717+00:00 filesender : [rest:error] [RestAuthenticationRequiredException exception uid:660ee141b1d5e] rest_authentication_required
2024-04-04T17:20:01.728946+00:00 filesender : [rest:error] [RestAuthenticationRequiredException trace uid:660ee141b1d5e] #0 /opt/filesender/classes/rest/RestServer.class.php(299): RestEndpointUser->get()
2024-04-04T17:20:01.728990+00:00 filesender : [rest:error] [RestAuthenticationRequiredException trace uid:660ee141b1d5e] #1 /opt/filesender/www/rest.php(37): RestServer::process()
2024-04-04T17:20:01.729026+00:00 filesender : [rest:error] [RestAuthenticationRequiredException trace uid:660ee141b1d5e] #2 {main}
2024-04-04T17:20:01.729060+00:00 filesender : [rest:error] [RestAuthenticationRequiredException details uid:660ee141b1d5e] method = "get"
2024-04-04T17:20:01.729088+00:00 filesender : [rest:error] [RestAuthenticationRequiredException details uid:660ee141b1d5e] endpoint = "user"
```
