### ISSUE TITLE
UI3: seems aup_enabled doesn't do anything in dev3 builds

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1859]
Seems aup_enabled doesn't do anything in dev3 builds.
This is a requirement for us to move to v3 when it is released.

**Comment by madsi1m** [comment]
i stand corrected it seems to add a slider in transfer options
![image](https://github.com/filesender/filesender/assets/11512591/a5c0f204-fdce-4b10-8eac-cbea1a73ad58)
We would prefer this to be a one off after successful saml login rather than for each transfer

**Comment by monkeyiq** [comment]
Sorry about my poor initial recommendation. The option you want is `service_aup_min_required_version` https://github.com/filesender/filesender/blob/development/docs/v2.0/admin/configuration/index.md#service_aup_min_required_version 

I just checked this by making a new guest in ui3 and it prompted me for an AUP page on initial loading of the guest link.

**Comment by monkeyiq** [comment]
If the service_aup_min_required_version isn't working please reopen or reissue a github issue.
