### ISSUE TITLE
Help a newbie with authentication with apikey

### ISSUE THREAD

**Issue by schmildo** [filesender/filesender#1861]
I'm trying to use the AARNET implementation of filesender's API, i'd annoy them for this info but i cant find a single contact email.

I'd like to just make some succesful API queries.
After I log into AARnet's filesender page via my university's SSO, i can go to my profile and obtain my apikey.

The config file provided has these contents:
-------------
[system]
base_url = https://filesender.aarnet.edu.au/rest.php
default_transfer_days_valid = 21

[user]
username = myname@myuniversitydomain
apikey = xxxx
-------------

i'm going crazy trying to figure out the parameter names and authentication - i've trawled through the python code on github but i've had no luck.

AARNET's config file is here:
https://filesender.aarnet.edu.au/filesender-config.js.php

if i could figure out how to configure postman to query the API i'd be happy.
These unauthenticate endpoints work fine:

https://filesender.aarnet.edu.au/rest.php/lang
https://filesender.aarnet.edu.au/rest.php/info
https://filesender.aarnet.edu.au/rest.php/echo  <ACTUALLY I COULDNT GET IT TO ECHO ANY OF MY INPUTS>

but any endpoint require auth gives me errors such as the below in return.
{
  "message": "rest_authentication_required",
  "uid": "6614eedf3734a",
  "details": {
    "method": "get",
    "endpoint": "file"
  }
}

i'm clearly failing to authenticate!

Should not this work?

GET https://filesender.aarnet.edu.au/rest.php/<endpoint>?apikey=xxx&username=billy@bob.com

**Comment by schmildo** [comment]
i guess i'd like the confidence to know i'm correctly sending a query - so if there is an issue i can bother AARNET about it. but i cant even confirm i'm doing it right.

**Comment by PaulLocksley** [comment]
Hi @schmildo , 

I'd recommend giving the rest [api docs](https://docs.filesender.org/filesender/v2.0/rest/) a read, particularly the "Signed Request" and "Preparing a signed request" section. 
The example python client implements this at the start of the [call function](https://github.com/filesender/filesender/blob/2f10de366d0e6baa5b5aa829c4fbc6807bcedb38/scripts/client/filesender.py#L305) 

As for contacting AARNet, on their page you should see contact us in the top right, that page contains a form for submitting support enquirys as well as several phone numbers.

**Comment by schmildo** [comment]
> Hi @schmildo ,
> 
> I'd recommend giving the rest [api docs](https://docs.filesender.org/filesender/v2.0/rest/) a read, particularly the "Signed Request" and "Preparing a signed request" section. The example python client implements this at the start of the [call function](https://github.com/filesender/filesender/blob/2f10de366d0e6baa5b5aa829c4fbc6807bcedb38/scripts/client/filesender.py#L305)
> 
> As for contacting AARNet, on their page you should see contact us in the top right, that page contains a form for submitting support enquirys as well as some phone numbers/emails.

Oh i'm blind - thanks i didnt see the form at the bottom of the contact page.

Thanks for the tips regarding the api docs and the call function - Its nice to know i was already on the right track - i've already  tried and failed to trace those calls back in the code to find the correct API parameters (nearly everything i can see in the code is a variable with an analogous name.

The exact parameter names must be in the code somewhere.
I might have to create my own instance of the server, and use wireshark to observe the outgoing requests - if that will work.

**Comment by monkeyiq** [comment]
If you are creating your own FileSender instance for testing you can also tinker with it a bit to log the signed request on the client and server side before it is put through the hmac. This way you can debug what the client is expecting to send vs what the server expected to see in a more meaningful way.

See for example the `$signed` value on the server side.
https://github.com/filesender/filesender/blob/ea4b8ebd7ac670516b3e94b1f43b24707ca61802/classes/auth/AuthRemote.class.php#L158

**Comment by monkeyiq** [comment]
It seems the original issue has been resolved for this. Please feel free to open new issues if you experience issues with the REST api.
