### ISSUE TITLE
UI3: Option to use a calendar for transfer expiration dates. (like in FS 2.x)

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1867]
We would like to see the calendar in FS3 for setting expiry for both guests and transfers. Some of our uses use this to set hard cutoff dates for documents/data and we would like to maintain this feature.

**Comment by madsi1m** [comment]
Hi any updates on this? I see this issue as a roadblock for us to move to v3.

**Comment by monkeyiq** [comment]
Are there other blocking issues or is this the only thing currently holding you back?

**Comment by madsi1m** [comment]
I've created other issues to improve the feel but this and an "official" release are blockers:
Nice to haves:
- https://github.com/filesender/filesender/issues/1851
- https://github.com/filesender/filesender/issues/1881
- https://github.com/filesender/filesender/issues/1882

**Comment by madsi1m** [comment]
also a merge from dev branch with fixes after 2.48 we have made

**Comment by monkeyiq** [comment]
When I do a new 3.0beta release I will first do a 2.49 series release and then merge those updates into 3.x for the beta so it matches a 2.x series for the bulk of the code.

**Comment by monkeyiq** [comment]
I will work on this one first :)

**Comment by monkeyiq** [comment]
dev3 should have this one, https://github.com/filesender/filesender/issues/1882 and the update merge with dev in it now.

**Comment by monkeyiq** [comment]
I think https://github.com/filesender/filesender/issues/1881 will be next :)

**Comment by madsi1m** [comment]
datepicker seems to be working now, closing ticket

**Comment by monkeyiq** [comment]
The expire time for inviting a guest is still only a X number of days drop down.

**Comment by monkeyiq** [comment]
I think I repopened this when I noticed that the guest new invitation time setting was the new user friendly "x days" drop down rather than offering a semester friendly choose an end date via calendar method. PR 1910 should have fixed this.
