### ISSUE TITLE
UI3: Admin pages missing/hidden?

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1868]
Can not see admin pages for admins in FS3

**Comment by monkeyiq** [comment]
I see an admin with cogs in the top right of the menu. IIRC I am just using the `$config['admin']` setting to elevate my user to admin.

**Comment by monkeyiq** [comment]
If I update that to not match my user then the admin menu disappears. Are you usiung the admin config or a saml attribute to nominate admin rights?

**Comment by madsi1m** [comment]
i am using `$config['admin']` I think i have an issue with case sensitivity with my fake SAML IDP, will fix and report back

**Comment by monkeyiq** [comment]
The pages themselves might be a bit funky. Let me know if there are things that you need which are not functional.

**Comment by madsi1m** [comment]
can confirm it works. pages looks same as FS2, so fine for now.
