### ISSUE TITLE
Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array

### ISSUE THREAD

**Issue by joneskumwenda** [filesender/filesender#1869]
having the following error after successful login into filesender with remote idp
Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /opt/filesender/filesender/classes/auth/Auth.class.php:437 Stack trace: #0 /opt/filesender/filesender/classes/auth/Auth.class.php(437): in_array() #1 /opt/filesender/filesender/templates/header.php(9): Auth::isAdmin() #2 /opt/filesender/filesender/classes/utils/Template.class.php(117): include('...') #3 /opt/filesender/filesender/classes/utils/Template.class.php(124): Template::{closure}() #4 /opt/filesender/filesender/classes/utils/Template.class.php(220): Template::process() #5 /opt/filesender/filesender/www/index.php(52): Template::display() #6 {main} thrown in /opt/filesender/filesender/classes/auth/Auth.class.php on line 437

**Comment by madsi1m** [comment]
maybe add some debug lines before to see what is in self::$attributes['additional'] and/or self::$attributes
you might have not set auth_sp_saml_entitlement_attribute correctly?

**Comment by joneskumwenda** [comment]
Thanks alot, The problem was indeed that i didn't specify the auth_sp_saml_admin_entitlemen_t
