### ISSUE TITLE
auditlog_lifetime default value concerns

### ISSUE THREAD

**Issue by PaulLocksley** [filesender/filesender#1878]
Hi all, 

Recently we had users report issues with the audit log close to the end of transfers lifetime. 
We had raised the max_transfer_days_valid value in our deployment and didn't think anything of the audit log.
Because of this the initial events would age out of the audit log whilst the transfer was still active. 

This seems like a simply oversight for admins to make, is it possible to get a default value that lines up with the max_transfer_days_valid? 
ie: `auditlog_lifetime' => function() {
  return Config::get('max_transfer_days_valid') + 11;
},`
Similar to how the default site_logouturl uses the site_url value. 

I believe this would be a more useful base case, but I'm not sure if their are any limitations to this approach.  

Alternatively maybe a note under max_transfer_days_valid in the documentation to think about x settings if you are modifying this.

**Comment by WebSpider** [comment]
Thanks for the suggestion! This makes sense, but I do think we should document the impact of database size

**Comment by monkeyiq** [comment]
This seems like a great thing to slip into the 3.x series. Such as the above PR does! I made a new config key to set the amount of buffer `11` from a above which is `14` by default in the PR.

**Comment by monkeyiq** [comment]
This has now been released. Thank you for reporting it! If there are other configuration updates that are useful please continue to raise issues :)
