### ISSUE TITLE
UI3: feature request: logged out pop up?

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1881]
If we log into filesender and leave it (go to lunch) and then try and transfer a file, it fails because the session has expired.
Be nice to do a popup when the session dies (and we are not already uploading)

This has already happened to one of our testers

**Comment by monkeyiq** [comment]
This sounds good. I have also seen somebody leave the partly setup upload page open in a suspended laptop and it asked for a login again and was a bit confusing when they tried to complete. I guess for that case people don't often stall at the almost doing an upload stage.

**Comment by monkeyiq** [comment]
This has been merged and released. Thank you for the issue report.
