### ISSUE TITLE
UI3: feature request: clicking next on the wizard should scroll to top of page

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1882]
if i add say 1000 files and click Next, the page does not scroll to the top and the user doesn't see the instructions and options of what to do.
An auto scroll would fix this.

**Comment by monkeyiq** [comment]
I always thought the control bar (prev, cancel, next) should be always on screen during that process.

**Comment by madsi1m** [comment]
as it feels like we are progressing to a new page, i think scrolling to top might give a smoother UX

**Comment by madsi1m** [comment]
tested and working
