### ISSUE TITLE
Uploading of files hangs/does not complete

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#1899]
Some of our users experience an issue when uploading files. The upload process hangs on and does not complete. The progress  bar then goes back to retransmit packets. Any information on what is the cause of this and how I can resolve it will be appreciated. See the attached video screengrab for reference.

https://github.com/filesender/filesender/assets/22442842/4c1108d6-747f-4da4-89bc-e117c12546a2

Regards
Thuso

**Comment by WebSpider** [comment]
The reasons for this could be multiple, from memory issues on the client to storage issues on the server, or connection issues along the way. Best way to troubleshoot these kind of issues in my experience is to enable the Javascript console in the browser of the end-user and analyse the output there.

**Comment by monkeyiq** [comment]
There was some discussion years ago about allowing the chunk size to vary during a file upload. If the `upload_chunk_size` is 5mb as per the default then that is the amount that could be lost in transit and might need to be retransmitted. If you are running terasender with many workers `terasender_worker_count` then you might loose that many chunks.  If the chunk size could vary during an upload then it could in this case vary downwards to say 0.5mb and then it could acknowledge and accept smaller blocks and avoid as much retransmission. Though none of that context helps right now.

Trying to see why an upload chunk is failing here is what is needed. And also a bit harder unfortunately. If you can get some information about the network the user is on and if that is lossy etc it might help. There are many things that might cause a chunk retransmission, these are basically the things that might cause a 5mb `XMLHttpRequest` to fail.

**Comment by thuso607** [comment]
How much terasender_worker_count can I set to avoid losing many chunks? The current setting is 10.

**Comment by WebSpider** [comment]
You can set it all the way down to 1, and go up if you want to
