### ISSUE TITLE
Downloading an encrypted file silently fails on Internet Explorer

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#191]
When a user tries to download an encrypted file using Internet Explorer, pressing the Download button doesn't do anything.

The following is written in the console:

	❌ SCRIPT438: Object doesn't support property or method 'crypto_app'
	    download_page.js (85,17)

I'm not certain that Internet Explorer has webcrypto implemented good enough so that downloading and decrypting is possible. But if that's the problem, the user should get an error in the UI explaining the situation.

**Comment by monkeyiq** [comment]
I'll start digging here a little. 

Another data point, on Windows 10 using Edge 41.16299 upload and download of encrypted files seems to work ok. Obviously there are some IE versions where it doesn't though.

**Comment by monkeyiq** [comment]
It seems that IE 11 or later might be ok
https://developer.mozilla.org/en-US/docs/Web/API/Crypto#Browser_Compatibility

**Comment by monkeyiq** [comment]
I should have something for this tomorrow.

**Comment by monkeyiq** [comment]
We may need to crowd source to see what the minimal version of IE is for crypto or work out some other way of finding out.
