### ISSUE TITLE
Configuration error(s), please check the server logs or ask an admin to do so.

### ISSUE THREAD

**Issue by BWar81** [filesender/filesender#1915]
Hello,

I have carried out a new installation of FileSender however when I navigate to the site I get the following on screen message:

Configuration error(s), please check the server logs or ask an admin to do so.

I have looked through the Apache and syslog and can't see any errors however the following shows in the FileSender log:

[2024-06-03 08:52:59] [upgrade:info] authentication::create(1) saml_uid filesender-reserved1@localhost.localdomain
[2024-06-03 08:52:59] [upgrade:info] authentication::create(2) NOT FOUND! filesender-reserved1@localhost.localdomain
[2024-06-03 08:52:59] [upgrade:info] authentication::create(3) filesender-reserved1@localhost.localdomain

I am unable to find 'filesender-reserved1@localhost.localdomain' in any of the config files and as such I don't know why this is error exists or how to resolve it so any support would be gratefully appreciated!

**Comment by monkeyiq** [comment]
These reserved IDs are created in the database by the `scripts/upgrade/database.php` script. You should see them in your `authentications` (postresql) or `Authentications` (mariadb) table in the database. If not then that is a good place to start narrowing in for what is causing the issue.

**Comment by BWar81** [comment]
Thanks for the response :) I have had a look in the Authentications table and I can see the account in there (see output below). Is there anything else I can check for?

MariaDB [filesender]> SELECT * from Authentications;
+----+---------------------------------------------+------------------------------------------+---------------------+---------------------+---------+--------------+
| id | saml_user_identification_uid                | saml_user_identification_uid_hash        | created             | last_activity       | comment | passwordhash |
+----+---------------------------------------------+------------------------------------------+---------------------+---------------------+---------+--------------+
|  1 | filesender-upgrade@localhost.localdomain    | eece83dce87f847507180314d6b8136287df6638 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
|  2 | filesender-cronjob@localhost.localdomain    | 09551aefc9814314a39bca7665b2b6e3f7bb7768 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
|  3 | filesender-authlocal@localhost.localdomain  | fc1480ea65924356a16044044011241e417eda18 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
|  4 | filesender-phpunit@localhost.localdomain    | 1f3d0c70881af2f372047979212d631e34d6942c | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
|  5 | filesender-testdriver@localhost.localdomain | 95a3b99f10c24104ccc6a3a885761bd1cdfb5612 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
|  6 | filesender-reserved1@localhost.localdomain  | dc422eaa60c2d7f6aa89bb91fb3d5c77d1daefc9 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
|  7 | filesender-reserved2@localhost.localdomain  | 11d71451001a1929f12c121d8c51490c23b47721 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
|  8 | filesender-reserved3@localhost.localdomain  | 631bb38331308e068e9761d50636c1dcf142d721 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
|  9 | filesender-reserved4@localhost.localdomain  | 25fe1ff3e3597518aa26a75e58a6cb8193f798b9 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
| 10 | filesender-reserved5@localhost.localdomain  | 922b11256bd3cc8eb958914248636e326bbb4a03 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
| 11 | filesender-reserved6@localhost.localdomain  | 710be4f36b094642ca00abd77d1248b72e63561c | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
| 12 | filesender-reserved7@localhost.localdomain  | 8f31f04fd084fd30b32fcd9dfb822953db4d884a | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
| 13 | filesender-reserved8@localhost.localdomain  | af6c5b4e8a42b675c84ebe2d7d140675fbfec35d | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
| 14 | filesender-reserved9@localhost.localdomain  | 5db030b8e1853eba8a4ac60f745642dc69a05008 | 2024-06-03 08:52:59 | 2024-06-03 08:52:59 | NULL    | NULL         |
+----+---------------------------------------------+------------------------------------------+---------------------+---------------------+---------+--------------+

**Comment by monkeyiq** [comment]
Looking at the code that is around the initial reported error FileSender is looking for a user with the specific saml_user_identification_uid which we now know is in the table.

```
[2024-06-03 08:52:59] [upgrade:info] authentication::create(1) saml_uid [filesender-reserved1@localhost.localdomain](mailto:filesender-reserved1@localhost.localdomain)
```

https://github.com/filesender/filesender/blob/9031559f866d28223d6c025ae7bc4c05b50d22b8/classes/data/Authentication.class.php#L137

In order to hit the `authentication::create(2) NOT FOUND!` message that lookup by email address is failing some how. 

Perhaps there is an issue authenticating to the database as the user php is running as? I assume the logs do not have anything like `DBI connect error` in them. Which php version, database and db version are you using?

**Comment by BWar81** [comment]
I haven't seen any DBI connect error messages in any of the logs I have checked.

Ubuntu 22.04.4 LTS
PHP version 8.1.2
MariaDB version 10.6.16
Database major version 22

**Comment by madsi1m** [comment]
do you get any error when running scripts/upgrade/database.php from the cli?

**Comment by BWar81** [comment]
No errors, have run again and it completes successfully

**Comment by monkeyiq** [comment]
Please see just above the error line in your filesender log.
```
Configuration error(s), please check the server logs or ask an admin to do so.
```

This message is generated when one of the core configuration checks fails, or your `/opt/filesender/filesender/config/config.php` is not readable by the apache2/php user.  This is an error case I just tested that made the above error.

The individual checks are in `./includes/ConfigValidation.php`.

I have a working vm installation with 
```
Ubuntu 22.04.4 LTS
php 8.1.2-1ubuntu2.17
ii  apache2        2.4.52-1ubuntu4.9 amd64        Apache HTTP Server
ii  mariadb-server 1:10.6.16-0ubuntu0.22.04.1 all          MariaDB database server (metapackage depending on the latest version)

```

**Comment by BWar81** [comment]
Hello,

Apologies for the delay. I have checked the permissions to the /opt/filesender/filesender/config/config.php file and they are as below:

`-rw-r----- 1 root www-data 8157 Jul  4 12:24 config.php`

How can I run the `ConfigValidation.php` script to see output?

**Comment by BWar81** [comment]
Hello,

I have now found the issue:

php: message repeated 3 times: [ ConfigValidator "email_reply_to" does not validate check : "string"]

Appreciate the time taken to help :)

**Comment by monkeyiq** [comment]
As the issue was found I will close the github issue. Thank you for reporting the issue and eventual solution!
