### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by frajer** [filesender/filesender#1917]
I'm new here. I just installed Filesender on my local server. I can login to filesender, but the only thing that is working is menu. Other options  doesn't work (I can't upload and send files, neither I can send file requests).

Client log says:
"[13:14:37] JS ERROR in https://xxxx.xxx.si/filesender/filesender-config.js.php@89:16 Uncaught SyntaxError: Invalid or unexpected token",
		"[13:14:49] JS ERROR in https://xxxx.xxx.si/filesender/filesender-config.js.php@89:16 Uncaught SyntaxError: Invalid or unexpected token",
		"[13:14:49] JS ERROR in https://xxxx.xxx.si/filesender/lib/jquery/jquery.min.js@2:28760 Uncaught TypeError: Cannot read properties of undefined (reading 'quota')",
		"[13:14:49] JS ERROR in https://xxxx.xxx.si/filesender/lib/jquery/jquery.min.js@2:28760 Uncaught TypeError: Cannot read properties of undefined (reading 'upload_chunk_size')",
		"[13:14:53] JS ERROR in https://xxxx.xxx.si/filesender/filesender-config.js.php@89:16 Uncaught SyntaxError: Invalid or unexpected token",
		"[13:14:53] JS ERROR in https://xxxx.xxx.si/filesender/lib/jquery/jquery.min.js@2:28760 Uncaught TypeError: Cannot read properties of undefined (reading 'quota')",

In syslog I found only this suspicios behavior:
[TR246b3d91] Error loading session: Cannot load PHP session with a specific ID.
Jun  6 11:32:23 nextcloud simplesamlphp[30078]: PHP Fatal error:  Uncaught SimpleSAML\Error\Exception: Cannot load PHP session with a specific ID. in /opt/filesender/simplesamlphp-1.19.9/lib/SimpleSAML/SessionHandlerPHP.php:270

Can someone help me to find what I'm doing wrong?

**Comment by madsi1m** [comment]
In your browser load up https://xxxx.xxx.si/filesender/filesender-config.js.php and look at what is on line 89 and dig into the code on your local server to see where it is failing.

As a guess, does your nextcloud and/or simplesamlphp use a custom session id? Are there any security things blocking it to FileSender?

**Comment by monkeyiq** [comment]
I was just playing around with how to try to validate for these issues. It might make sense to move filesender-config.js.php to being just JSON data. That way it could possibly be validated or linted from the command line. 

As it stands filesender-config.js.php is still a full javascript file setting window.filesender.config directly. So validation needs something like eslint. In most cases the line number and a direct viewing of the filesender-config.js.php can provide enough to hint has to what is not working.

**Comment by frajer** [comment]
> In your browser load up https://xxxx.xxx.si/filesender/filesender-config.js.php and look at what is on line 89 and dig into the code on your local server to see where it is failing.
> 
> As a guess, does your nextcloud and/or simplesamlphp use a custom session id? Are there any security things blocking it to FileSender?

Line 89 in filesender-config.js.php is:

    logon_url: '

and the file is ending at this line.
[filesender-config.js.zip](https://github.com/user-attachments/files/15721565/filesender-config.js.zip)

For authentication I use simplesaml ldap search, in authsources.php there is this configuration;

    'my-ldap' => [
        'ldap:LDAP',
        'hostname' => 'ad.xxxx.si',
        'enable_tls' => false,
        'debug' => false,
        'timeout' => 0,
        'port' => 389,
        'referrals' => false,
        'attributes' => null,
        // This option is not used if the search.enable option is set to TRUE.
        'dnpattern' => 'uid=%username%,ou=people,dc=example,dc=org',
        'search.enable' => true,
        'search.base' => 'ou=xxxxx,dc=xxxxxx,dc=local',
        'search.attributes' => ['sAMAccountName'],
        'search.filter' => '(&(objectclass=user))',
        'search.username' => 'aduser',
        'search.password' => 'xxxxxx',
        'priv.read' => false,
        'priv.username' => null,
        'priv.password' => null,
    ],

I belive that security setting are not blocking anything, because in simplesaml I get all the attributes from active directory.
![image](https://github.com/filesender/filesender/assets/7531296/d6669bdc-7ca5-4b56-9f71-499fe476943a)

**Comment by frajer** [comment]
> I was just playing around with how to try to validate for these issues. It might make sense to move filesender-config.js.php to being just JSON data. That way it could possibly be validated or linted from the command line.
> 
> As it stands filesender-config.js.php is still a full javascript file setting window.filesender.config directly. So validation needs something like eslint. In most cases the line number and a direct viewing of the filesender-config.js.php can provide enough to hint has to what is not working.

For me viewing the file doesn't give me enough hints. I atttached the file in the answer to monkeyiq's answer.

**Comment by WebSpider** [comment]
Check the SAML configuration in your `config.php`, especially statements concerning

```php
$config['auth_sp_saml_authentication_source'] = 'my-ldap';
$config['auth_sp_saml_simplesamlphp_url'] ='https://my-url.my.mydomain/example/simplesaml/';
$config['auth_sp_saml_simplesamlphp_location'] ='/usr/share/filesender/simplesaml/';
```

**Comment by frajer** [comment]
> Check the SAML configuration in your `config.php`, especially statements concerning
> 
> ```
> $config['auth_sp_saml_authentication_source'] = 'my-ldap';
> $config['auth_sp_saml_simplesamlphp_url'] ='https://my-url.my.mydomain/example/simplesaml/';
> $config['auth_sp_saml_simplesamlphp_location'] ='/usr/share/filesender/simplesaml/';
> ```

I check saml configuration and it looks ok:
$config['auth_sp_saml_simplesamlphp_url'] ='https://xxx.xxx.si/simplesaml/';     // Url of simplesamlphp
$config['auth_sp_saml_simplesamlphp_location'] ='/opt/filesender/simplesaml/';   // Location of simplesamlphp libraries
$config['auth_sp_saml_uid_attribute'] = 'sAMAccountName';
$config['auth_sp_saml_authentication_source'] = 'my-ldap';

**Comment by WebSpider** [comment]
Three more locations to check for clues:

1. Your webserver logfiles (`/var/log/httpd/error.log` or similar)
2. SimpleSAML logfiles (`/path/to/simplesamlphp/log`)
3. FileSender logs (`/path/to/filesender/log`)

**Comment by monkeyiq** [comment]
It is breaking inside ` AuthSP::logonURL()`. One thought would be to create scripts/testing/show-authsp-logonurl.php with the following content
```
<?php

require_once('../../includes/init.php');

echo AuthSP::logonURL() . "\n";
```
and run it as
```
php show-authsp-logonurl.php
```

This might give more information. 

Looking at `AuthSPSaml/logonURL` it uses the following configuration keys maybe landing_page and maybe auth_sp_saml_authentication_source. It would be interesting to include some Logger::error("here") type calls in logonURL to see how far it is getting and what it is doing internally.

**Comment by frajer** [comment]
> It is breaking inside ` AuthSP::logonURL()`. One thought would be to create scripts/testing/show-authsp-logonurl.php with the following content
> 
> ```
> <?php
> 
> require_once('../../includes/init.php');
> 
> echo AuthSP::logonURL() . "\n";
> ```
> 
> and run it as
> 
> ```
> php show-authsp-logonurl.php
> ```
> 
> This might give more information.
> 
> Looking at `AuthSPSaml/logonURL` it uses the following configuration keys maybe landing_page and maybe auth_sp_saml_authentication_source. It would be interesting to include some Logger::error("here") type calls in logonURL to see how far it is getting and what it is doing internally.

The above script returns:
https://xxxx.xxx.si/simplesaml/module.php/core/as_login.php?AuthId=my-ldap&ReturnTo=https%3A%2F%2Fxxxx.xxx.si%2Ffilesender%2F%3Fs%3DuploadAuthId=my-ldap&ReturnTo=https%3A%2F%2Fxxxx.xxx.si%2Ffilesender%2F%3Fs%3Dupload

is this OK?

**Comment by monkeyiq** [comment]
It looks ok. I think the `filesender-config.js.php` should be able to get it and print it. Since it is just echoing the data formatting mistakes should be picked up later if they are present.

I assume you still get a halt at the same location if you try to get the config directly on the command line.
```
curl -k https://xxx.xxx.si/filesender/filesender-config.js.php
```

Do you have logging set to debug in your `/opt/filesender/config/config.php` file?

```
$config['log_facilities'] = 
    array(
        array(
            'type' => 'file',
            'level' => 'debug',
            'path' => FILESENDER_BASE.'/log/',
            'rotate' => 'daily'
        ),
);
```

**Comment by frajer** [comment]
> It looks ok. I think the `filesender-config.js.php` should be able to get it and print it. Since it is just echoing the data formatting mistakes should be picked up later if they are present.
> 
> I assume you still get a halt at the same location if you try to get the config directly on the command line.
> 
> ```
> curl -k https://xxx.xxx.si/filesender/filesender-config.js.php
> ```
> 
> Do you have logging set to debug in your `/opt/filesender/config/config.php` file?
> 
> ```
> $config['log_facilities'] = 
>     array(
>         array(
>             'type' => 'file',
>             'level' => 'debug',
>             'path' => FILESENDER_BASE.'/log/',
>             'rotate' => 'daily'
>         ),
> );
> ```

[fs.zip](https://github.com/user-attachments/files/15783576/fs.zip)

I can't find anything, so I attached the file with the answer of the  curl -k https://xxx.xxx.si/filesender/filesender-config.js.php and the filesender log.

**Comment by frajer** [comment]
> > It is breaking inside ` AuthSP::logonURL()`. One thought would be to create scripts/testing/show-authsp-logonurl.php with the following content
> > ```
> > <?php
> > 
> > require_once('../../includes/init.php');
> > 
> > echo AuthSP::logonURL() . "\n";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and run it as
> > ```
> > php show-authsp-logonurl.php
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This might give more information.
> > Looking at `AuthSPSaml/logonURL` it uses the following configuration keys maybe landing_page and maybe auth_sp_saml_authentication_source. It would be interesting to include some Logger::error("here") type calls in logonURL to see how far it is getting and what it is doing internally.
> 
> The above script returns: https://xxxx.xxx.si/simplesaml/module.php/core/as_login.php?AuthId=my-ldap&ReturnTo=https%3A%2F%2Fxxxx.xxx.si%2Ffilesender%2F%3Fs%3DuploadAuthId=my-ldap&ReturnTo=https%3A%2F%2Fxxxx.xxx.si%2Ffilesender%2F%3Fs%3Dupload
> 
> is this OK?

Why is there in the url twice AuthId=my-ldap&ReturnTo=https%3A%2F%2Fxxxx.xxx.si%2Ffilesender%2F%3Fs%3Dupload
I think this could be the problem. But I don't know how to fix them?

**Comment by monkeyiq** [comment]
The twice appearance will not be helping things. Especially since the first `ReturnTo` does not end with an `&` to break the second AuthId use into a new argument.

```
     logon_url: '
https://xxx.xxx.si/simplesaml/module.php/core/as_login.php?
AuthId=my-ldap&
ReturnTo=https%3A%2F%2Fxxx.xxx.si%2Ffilesender%2F%3Fs%3Dupload
AuthId=my-ldap&
ReturnTo=https%3A%2F%2Fxxx.xxx.si%2Ffilesender%2F%3Fs%3Dupload',
```

**Comment by monkeyiq** [comment]
You could try commenting out these two lines that add those attributes. If that only removes the duplicates then we might be on the right path and then we can try to see why they are replicated in your case and come up with a more permanent fix.

https://github.com/filesender/filesender/blob/461ccb284cf321b477c91d626936879dce104d87/classes/auth/AuthSPSaml.class.php#L233

**Comment by frajer** [comment]
> You could try commenting out these two lines that add those attributes. If that only removes the duplicates then we might be on the right path and then we can try to see why they are replicated in your case and come up with a more permanent fix.
> 
> https://github.com/filesender/filesender/blob/461ccb284cf321b477c91d626936879dce104d87/classes/auth/AuthSPSaml.class.php#L233

I commented out lines 233 and 234, but I get the same logon_url with doubled attributes. 

https://xxx.xxx.si/simplesaml/module.php/core/as_login.php?
AuthId=my-ldap&
ReturnTo=https%3A%2F%2Fxxx.xxx.si%2Ffilesender%2F%3Fs%3Dupload
AuthId=my-ldap&
ReturnTo=https%3A%2F%2Fxxx.xxx.si%2Ffilesender%2F%3Fs%3Dupload'

**Comment by monkeyiq** [comment]
Before the http_build_query() call before line 233 could you check what the `$target` being passed is... mostly if it has the two attributes or not. If `$target` does have two AuthId then it is being passed in and the backtrace from the debug will tell from where and we can try to work out why that is.

```
        Logger::debug("logonURL have target $target ");
```

**Comment by monkeyiq** [comment]
I guess one step forward. If the `$target` is not including two `AuthId` and they are not added by FileSender then it is probably coming from the SSP configuration.

You could take a look at the SSP file src/SimpleSAML/Auth/Simple.php

In particular seeing how the `$login` is formed from its parts. Something is causing a repeat of two attribute for you. If they are repeated with separators in the correct position it is probably not so much of a problem but they are running together and thus not allowing the value to be properly transmitted...

https://github.com/simplesamlphp/simplesamlphp/blob/85203ef6a06fd5a18ec980349bb981035b2d47a0/src/SimpleSAML/Auth/Simple.php#L319

**Comment by frajer** [comment]
> I guess one step forward. If the `$target` is not including two `AuthId` and they are not added by FileSender then it is probably coming from the SSP configuration.
> 
> You could take a look at the SSP file src/SimpleSAML/Auth/Simple.php
> 
> In particular seeing how the `$login` is formed from its parts. Something is causing a repeat of two attribute for you. If they are repeated with separators in the correct position it is probably not so much of a problem but they are running together and thus not allowing the value to be properly transmitted...
> 
> https://github.com/simplesamlphp/simplesamlphp/blob/85203ef6a06fd5a18ec980349bb981035b2d47a0/src/SimpleSAML/Auth/Simple.php#L319

I don't have this file in my installion. I use simplesamlphp version 1.19.9, because the docs of filesender states:

All versions of FileSender currently use the SimpleSAMLphp 1.x series. (https://docs.filesender.org/filesender/v2.0/install/)

Which versions of SimpleSAMLphp and Filesender do you use? I would like to try the same versions.

**Comment by madsi1m** [comment]
From memory there have been several SSP v2 "fixes" in filesender this year for SSP v2 to work.

We are currently on SimpleSAMLphp 2.2.2 and FileSender 2.48 or this commit to be exact 76c3d482918bd5cad9e86238e3dc9ebe37103f0e. That said we have been on SSP v2 for some time now.

Note if you do upgrade to SSP v2 the SSP configs are a bit different (read the upgrade notes on SSP site)

**Comment by frajer** [comment]
Thanks to all, who helped me. It was the version of PHP, that caused the troubles. It works with PHP 8.3.

**Comment by WebSpider** [comment]
@frajer thank you so much for reporting back!

Could you please let us know:

1- Which version of PHP was causing your troubles
2- What OS/distribution you were trying this on?

Just so we can solve issues like this earlier in the future!

**Comment by frajer** [comment]
> @frajer thank you so much for reporting back!
> 
> Could you please let us know:
> 
> 1- Which version of PHP was causing your troubles 2- What OS/distribution you were trying this on?
> 
> Just so we can solve issues like this earlier in the future!

PHP 8.0.3
Ubuntu 20.04.6 LTS
