### ISSUE TITLE
UI3: Selecting a transfer link opens up the e-mail detail screen

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1920]
On filesender 3.0 b7
- When creating a new transfer
- And adding a file to it
![New transfer with file](https://github.com/filesender/filesender/assets/437323/94c6739b-50cf-4807-a452-ee8e35ac1530)
- And choosing 'A Transfer link' and not 'An e-mail'
![Transfer option](https://github.com/filesender/filesender/assets/437323/f1281744-a961-4bf1-a63c-2036796153a2)

The email detail dialog is opened. This does not make any sense, since the user specifically chooses not to send an e-mail and confuses our test-users
![Screenshot from 2024-06-07 12-26-42](https://github.com/filesender/filesender/assets/437323/1239f79c-800a-43ff-8826-3b11d9afcc0d)

### Suggested fix

Only unfold the e-mail dialog when the user chooses e-mail as transfer method, and refold it if the user chooses the transfer link

**Comment by peter-** [comment]
> The email detail dialog is opened

That confused me as well but this is not an "email dialog", otherwise it would be missing the all-essential input fieled for email addresses. And the information entered there actually shows up on the web page the recipient uses to download the transfer.

While the implementation (or UI) may have been re-used from the email option I think this part of the UI would be more understandable if the `Subject` and `Message` input fields were merged into a single field called `Comment` or `Comment to recpient(s)` something like that.  
I.e., "if link" hide the `Subject` field and name `Message` differently.

**Comment by WebSpider** [comment]
> > The email detail dialog is opened
> 
> That confused me as well but this is not an "email dialog", otherwise it would be missing the all-essential input fieled for email addresses. And the information entered there actually shows up on the web page the recipient uses to download the transfer.
> 

Oh wow, now I see. I really wonder how that got there, and what purpose it serves.

> While the implementation (or UI) may have been re-used from the email option I think this part of the UI would be more understandable if the `Subject` and `Message` input fields were merged into a single field called `Comment` or `Comment to recpient(s)` something like that. I.e., "if link" hide the `Subject` field and name `Message` differently.

Agreed. Personally, I don't see any use for this at all, but there may be some installs that are looking for something like this.

**Comment by monkeyiq** [comment]
I imagined that in UI/UX land having subject and message on both paths was more user friendly. It has been there since last year.

**Comment by monkeyiq** [comment]
Perhaps we should have the UI experts chime in on this change. I have opened a governance ticket for this https://github.com/filesender/governance/issues/40

**Comment by madsi1m** [comment]
I'm in favour of simply hiding subject+message for get-a-link (keep things simple)

**Comment by monkeyiq** [comment]
It may be the case that the march updates such as "Fix/resume transfer" are intended as the final contributions to the ui3.

**Comment by monkeyiq** [comment]
I have more information that other UI updates may be coming in the future.

**Comment by WebSpider** [comment]
Any more updates on this?
We're beta-testing 3.0 in NL, and this has also come up as something users don't quite understand out of the box

**Comment by monkeyiq** [comment]
This may get pushed to a configurable setting in the future. As it is confusing to multiple deployments I have made the change not optional for now. If it is desired to be the default in the future I will make it a configurable option to work as in PR 2043 which I think a number of deployments will want to enable.

**Comment by monkeyiq** [comment]
This may well come back with the "3.1" UI update. I guess at that point we can raise another github issue, cite this one, and I'll take a look at making it optional again.
