### ISSUE TITLE
Voucher actions incorrect icons

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1922]
This was reported to me privately. I am opening a github issue for full transparency since I will likely work on an update for this issue it is useful for the community to see the history. I have modified the wording slightly in the below.

...On the Vouchers page, the icons for resend voucher and send a reminder are *different* on FileSender V3 compared to the current version [release 2.x series].

 The current version of FileSender uses: 
* the refresh icon ⟶ reminder action 
* an envelope icon ⟶ add a recipient

 FileSender V3 has 
* forward icon ⟶ reminder 
* refresh icon ⟶ send to new email address.
 
Also, can we update the text on the ‘resender voucher’ to be ‘Add a recipient’ as we have on the current version. How it is now is confusing with ‘Send a reminder’ and ‘resend voucher’ as they both sound like they do the same thing.

Ideally, it should be

* Refresh icon ⟶ Send reminder
* Envelope icon ⟶ Add recipient
* Bin icon ⟶ Delete voucher

This is also the same on the voucher detail page, so needs to be updated the same way.

**Comment by monkeyiq** [comment]
I am not sure why resend voucher was changed to the non english friendly "resender voucher".

**Comment by monkeyiq** [comment]
If RNP wants to jump in here I am happy to hand over ownership of the issue. I have taken it by default.

**Comment by madsi1m** [comment]
https://github.com/filesender/filesender/pull/1933
