### ISSUE TITLE
Can't remove single recipient from transfer

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1923]
This was also reported privately by an NREN.

...FileSender V3 does not allow a single email to be removed from a transfer, or to allow to resend the email notification to a single email address. The current version of FileSender [release 2.x series] allows for this.

 The current version of FileSender allows the user to delete individual email addresses from a transfer, or to resend the email notification with transfer details to a single email address in addition to the option to resend to all recipients.

FileSender V3 does not have any options to target individual recipients, so can only delete the entire transfer or resend the email notification to all recipients.

**Comment by monkeyiq** [comment]
I have retested 2.x and 3.x. In the 3.x you can add a new recipient to the transfer and see all the existing recipients. You are unable to perform specific actions (resend email, remove) on an individual recipient in 3.x.

**Comment by monkeyiq** [comment]
If this functionality is seen as undesirable then we can disable it with a config.php option to hide the buttons.

**Comment by monkeyiq** [comment]
It might make sense to have a single option "advanced mode" or something because there are already 3-4 options to re-enable functionality that was pruned in the 3.x update.

**Comment by monkeyiq** [comment]
it is on by default at the moment

**Comment by madsi1m** [comment]
nice
