### ISSUE TITLE
FileSender transfer quick actions missing

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1924]
This was also reported privately by an NREN. It had accompanying images in the email which I have left off the report for now.

... The quick actions are missing on the My Transfers page on FileSender V3 compared to the current version.

 The current version of FileSender has actions for transfers on the right hand side on the main My Transfers page. This allows users to quickly delete, resend the notification, add a recipient or view the logs for a transfer.

FileSender V3 does not have these actions available on the main **My transfers** page. Users have to click into the **Transfer details** page for each transfer they want to make changes to. This adds an extra step for users and may be annoying if they want to make changes to multiple transfers at the same time.

There also isn’t any obvious visual that tells me that I can click on the table to access more detail about a transfer. Maybe add something like the  icon (fa-circle-info) to the left of the ID column, similar to how it is on the current FileSender. This applies to both active and expired transfer tables, and the voucher table.

For reference, the actions are still available on the **Vouchers** page.

**Comment by monkeyiq** [comment]
Again this was reported with lovely detailed graphics. I have left the gist of the requested changes in text above.

**Comment by madsi1m** [comment]
nice
