### ISSUE TITLE
Possibility for per-file metadata

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#195]
I've been working on crypto improvements (#192) but I constantly get stuck on the problem that I want to store some metadata about a file, but I don't have a good location for it. Things I've been wanting to store so far are:

- Encryption algorithm
	- Name (`AES-CBC` or `AES-GCM`)
	- Length
- Key derivation paramaters
	- Hashing algorithm
	- Iterations
	- Salt
- Key proofing
	- Unencrypted nonce
	- Encrypted nonce

One solution would be to add all these fields to the database (`Files` table), which is a solution that could get very messy as multiple things are almost guaranteed to show up. New algorithms may also create the need for new fields, as not all algorithms have the same parameters, just the ones that we've used so far do.

A solution that I'm more comfortable with, but I still have doubts about, is to add three freetext fields to `Files`, all of them containing dictionaries in JSON/BSON/whatever. This would solve the future problem of different algorithms having different parameters, but in my opinion it still pollutes the schema quite a bit. On the other hand, we already have an `encrypted_size` field..

My proposal for a long term solution is thus: Replace the `encrypted_size` field with a free text `encryption` field. This contains a dictionary that contains **all** information about encryption. Using a big free text field will prevent us from searching the database for encryption information, but it's not something we will need to search for anyway, and it's not possible to make a scheme that we don't have to change later.

We may need a bit back and forth to get to a good solution here.

**Comment by madsi1m** [comment]
Can you use the json field in the transfer table??

On 5 Dec 2017, at 21:47, Jørn Åne <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been working on crypto improvements (#192<https://github.com/filesender/filesender/pull/192>) but I constantly get stuck on the problem that I want to store some metadata about a file, but I don't have a good location for it. Things I've been wanting to store so far are:

  *   Encryption algorithm
     *   Name (AES-CBC or AES-GCM)
     *   Length
  *   Key derivation paramaters
     *   Hashing algorithm
     *   Iterations
     *   Salt
  *   Key proofing
     *   Unencrypted nonce
     *   Encrypted nonce

One solution would be to add all these fields to the database (Files table), which is a solution that could get very messy as multiple things are almost guaranteed to show up. New algorithms may also create the need for new fields, as not all algorithms have the same parameters, just the ones that we've used so far do.

A solution that I'm more comfortable with, but I still have doubts about, is to add three freetext fields to Files, all of them containing dictionaries in JSON/BSON/whatever. This would solve the future problem of different algorithms having different parameters, but in my opinion it still pollutes the schema quite a bit. On the other hand, we already have an encrypted_size field..

My proposal for a long term solution is thus: Replace the encrypted_size field with a free text encryption field. This contains a dictionary that contains all information about encryption. Using a big free text field will prevent us from searching the database for encryption information, but it's not something we will need to search for anyway, and it's not possible to make a scheme that we don't have to change later.

We may need a bit back and forth to get to a good solution here.

**Comment by jornane** [comment]
> Can you use the json field in the transfer table??
In principle the files are encrypted individually, but I suppose that each file uses the same encryption settings anyway.

**Comment by jornane** [comment]
I don't think we should change the schema for this. We can revisit this ticket when the need arises.
