### ISSUE TITLE
MissingFileIDsException

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#1953]
Good day,

A user wants to download a file from filesender but get an error. The error reads "[DownloadMissingFilesIDsException exception uid:6683a1ff48a05] download_missing_files_ids". What causes this type of error when downloading files on filesender. I checked the expiry date of the of the upload and it has not expired. Please advice.

![image](https://github.com/filesender/filesender/assets/22442842/97af766b-0fea-43de-b33b-913345a022c9)

**Comment by WebSpider** [comment]
The request that the user sent, is missing a parameter (in this case `files_id`). 

How is the user downloading the file?

**Comment by WebSpider** [comment]
Maybe a duplicate of #1940

**Comment by monkeyiq** [comment]
A little while back the file_ids were changed from being sent as a query arg to being in a POST. This was to allow 1000s of files to be selected from a really large transfer without length limitations truncating the file list. The templates etc were updated to reflect this. If these files being stale was the cause of the issue for you it would stop all downloads though so fairly easy to see.

**Comment by monkeyiq** [comment]
This this happen when you attempt? If so which browser? If failing what do you see the for the file_ids param in the web console network traffic being sent? Which version are you on?

**Comment by monkeyiq** [comment]
Is this still happening?

**Comment by thuso607** [comment]
no, I will close it
