### ISSUE TITLE
Filesender now requires the `intl` extension.

### ISSUE THREAD

**Issue by James-REANNZ** [filesender/filesender#1958]
A recent change caused Filesender to use functions from the `intl` extension, the documentation should be updated to reflect this.

**Comment by madsi1m** [comment]
i have memories of this https://github.com/filesender/filesender/pull/1934 maybe it could have been mentioned in the release docs somewhere

**Comment by monkeyiq** [comment]
It is unfortunate that the old stdc function `strftime` became deprecated in php 8.1 https://www.php.net/manual/en/function.strftime.php

There was an issue raised with some warnings about FileSender using functions that are considered deprecated and as part of the I was looking for others and found this.

I have this distributed for development, development3, master3
https://github.com/filesender/filesender/issues/1943

IIRC the docs are generated from the master branch for the 2.x series. So until there is a new 2.x series release the php-intl dep is not shown on the docs page. See for example the page in the development branch:
https://github.com/filesender/filesender/blob/f2a2f9570e9129d600739c39cdc7eb256ea6020c/docs/v2.0/install/index.md?plain=1#L59

I imagine at some stage the docs will be taken from the master3 branch instead.

**Comment by monkeyiq** [comment]
Now that a release is made, master should have been updated in the big single patch prescribed method and so the web site will show the current documentation.
