### ISSUE TITLE
Error - unable to load composer autoloader

### ISSUE THREAD

**Issue by BWar81** [filesender/filesender#1960]
Following a new installation I get the following error:

```
FileSender encountered an error while processing your request
{unable to load composer autoloader}
```

I found the following artcle when searching for similar issues [Issue 65](https://github.com/filesender/filesender/issues/65) which suggested running `composer update`. After installing composer and running `composer update` I get the following error:

```
In JsonFile.php line 184:

  file_put_contents(./composer.lock): Failed to open stream: Permission denied
```

Any assistance would be greatly appreciated

**Comment by monkeyiq** [comment]
What version of php are you using?

**Comment by BWar81** [comment]
8.3

**Comment by monkeyiq** [comment]
I assume you still get the error when trying to use the FileSender install?

**Comment by BWar81** [comment]
Yeah same error

![image](https://github.com/user-attachments/assets/c04f9561-cb96-462f-94ed-b66e0e8a5ab1)
