### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by TheMysteriousX** [filesender/filesender#1970]
Really minor - release 2.49 hasn't been tagged as 'filesender-2.49' as the release notes say. It's been tagged as 2.49.

**Comment by monkeyiq** [comment]
Thank you for reporting this. I have checked out the 2.49 tag and made a new tag filesender-2.49 at that point and pushed the tag up to github. The `filesender-2.49` and `2.49` should be identical.

https://github.com/filesender/filesender/tree/filesender-2.49
