### ISSUE TITLE
Bigger files not downloading

### ISSUE THREAD

**Issue by vermpat** [filesender/filesender#1979]
I am experiencing a strange problem when trying to download bigger files (>100 MB) from our filesender installation.

The browser just reports "File wasn't available on this site" and "Failed - No file".
Problem exists in multiple browsers.

As far as i can tell the files have uploaded correctly, as i can see a file in the storage with the right size and timestamp.

Logging doesn't shed any light either, i just see this:

[2024-08-23 07:15:31] [rest:info] authentication::create(1) saml_uid vermeerenp
[2024-08-23 07:15:31] [rest:info] authentication::create(2) FOUND AND RETURNING 15
[2024-08-23 07:15:39] [web:info] User started to download File#6003(Wedden dat in LLF (1990 of 1991).MP4, 300506997 bytes)
[2024-08-23 07:15:39] [web:info] Event#download_started on File#6003(Wedden dat in LLF (1990 of 1991).MP4, 300506997 bytes) by Recipient#4499([patrick.vermeeren@dnw.aero](mailto:patrick.vermeeren@dnw.aero))
[2024-08-23 07:15:39] [web:info] User restarted download of File#6003(Wedden dat in LLF (1990 of 1991).MP4, 300506997 bytes) with explicit range bytes=197-
[2024-08-23 07:15:39] [web:info] User restarted download of File#6003(Wedden dat in LLF (1990 of 1991).MP4, 300506997 bytes) from offset 197
[2024-08-23 07:15:39] [web:info] Event#download_resumed on File#6003(Wedden dat in LLF (1990 of 1991).MP4, 300506997 bytes)

I am assuming there is a misconfiguration somewhere, but am unable to find it.

**Comment by WebSpider** [comment]
You might want to try setting log level to debug, that will give you more information, but will eat up some resources.

Also, see if you find anything in the browser Javascript console, that could contain some hints as well

**Comment by vermpat** [comment]
There is nothing in the javascript console.
This is what the debug log tells me:
[FS debug log.txt](https://github.com/user-attachments/files/16733728/FS.debug.log.txt)

**Comment by monkeyiq** [comment]
On the plus side it appears you can reproduce the issue in multiple browsers locally. 

You might like to check in your .../files directory for the stored file and verify the md5 against the original. Atleast that will verify that the file exists, is correct, and can be entirely read. This will probably not yield much information other than knowing the upload is succeeding as expected. I assume smaller downloads work as expected and verify in md5/sha1.

It is an interesting log. It appears something is causing an issue with login and for some reason FileSender is starting to download from byte 196 and up from then on.

What `$config['storage_type']` are you using? Which web server / php? Does this happen with encryption on/off/both? 

It may also be interesting to open the web console and look at the network traffic tab. Perhaps there is a response for the final chunk or after it to shine some light on things.

**Comment by vermpat** [comment]
Storage_type is FileSystem.
The path leads to a separate ext4 disk
We do not experience the problem with smaller files indeed, the files in the storage match the files i uploaded (As far as i can tell).
Web server is: Apache/2.4.61 (Debian)
PHP version is: PHP 8.2.20

When i check in the console:
First request (download.php?files_id=6003) gets a 302 redirect to the same path, but with a long string of characters behind it, including a simplesamlauthtoken and transaction_id
The second request (that long path mentioned before) gives a 200 OK status and these response headers:

`HTTP/1.1 200 OK
Date: Sun, 25 Aug 2024 07:24:07 GMT
Server: Apache/2.4.61 (Debian)
Strict-Transport-Security: max-age=63072000; includeSubDomains
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/8.2.20
Set-Cookie: SimpleSAML=<Removed for security>; path=/; secure; HttpOnly; SameSite=None
Expires: 0
Cache-Control: no-store, max-age=0
Pragma: private
Content-Transfer-Encoding: binary
Last-Modified: Fri, 23 Aug 2024 05:50:59
ETag: "t2307_f6003_s300506997_ranges_"
Connection: close
Content-Disposition: attachment; filename="Wedden dat in LLF (1990 of 1991).MP4"; filename*=UTF-8''Wedden%20dat%20in%20LLF%20%281990%20of%201991%29.MP4
Content-Length: 300506997
Accept-Ranges: bytes
Content-Type: application/binary`

**Comment by vermpat** [comment]
I just updated my SimpleSamlPHP installation to a new version, hoping that this might solve the issue. Unfortunately it did not. Do you have any other suggestions on where to look or what might be wrong?

**Comment by vermpat** [comment]
After a lot of troubleshooting, I managed to find the issue.
PHP was set up with 
`output_buffering = On` 
to fix an issue we were experiencing with SimpleSAMLphp.

This seems to cause an issue with downloading the bigger files. Config has been changed to 
`output_buffering = 4096` 
solving this issue. Thank you for your assistance!

**Comment by monkeyiq** [comment]
Thank you for debugging this and also including information about what configuration can cause things to go sideways! 

I might have a play with the `output_buffering` and try to see where it starts to break and maybe try to check and turn that off with an API call in the required REST methods if possible.
