### ISSUE TITLE
Empty placeholder in Download Receipt emails when no recipient is set

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [filesender/filesender#1980]
Hi,

I found that when  I upload a file, ask for download receipts, but do not specify a recipient (transfer by a Transfer link only), the download receipt has a blank email address - which makes a bad image of FileSender, making it look rather broken:
``` A file you uploaded has been downloaded from FileSender by . ```
...while when email address is specified, it has the email address in the right place:
``` A file you uploaded has been downloaded from FileSender by user@example.com. ```

I see the pattern is in `language/*/files_downloaded.mail.php` - which is 55 different language-specific files.

For English, it the pattern is:
```
{if:files>1}Several files{else}A file{endif} you uploaded {if:files>1}have{else}has{endif} been downloaded from {cfg:site_name} by {recipient.email}.
```

I'm guessing the templates were written with the assumption recipient email address would always be set, but than the assumption stopped being valid when "Transfer Link" transfers were introduced.

For English, this might be a trivial change - for the case when `recipient.email` is not provided, either stripping out the ` by {recipient.email}` part, or replacing it with e.g. `downloaded via a transfer link`.

Tricky would be fixing it across all the 55 language files - would need getting someone familiar with the language.  Not sure how to approach this part: whether better to start fixing languages we can, and wait for others to get the fix later, or whether to aim for broad sweep.

What are your thoughts?

Does the proposed approach sound reasonable?

And does doing languages piecemeal sound OK?

I'm happy to send a PR covering English (and Czech :-)

I look forward to hearing from you.

Cheers,
Vlad

**Comment by monkeyiq** [comment]
It does sound like these templates were originally created before the "get a link" option was added. I played around a bit and arrived at the following which works in both cases for me.

```
diff --git a/language/en_AU/files_downloaded.mail.php b/language/en_AU/files_downloaded.mail.php
index d35274e0..380153d2 100644
--- a/language/en_AU/files_downloaded.mail.php
+++ b/language/en_AU/files_downloaded.mail.php
@@ -13,7 +13,7 @@ subject: Download receipt
 
 Hello,
 
-{if:files>1}Several files{else}A file{endif} you uploaded {if:files>1}have{else}has{endif} been downloaded from {cfg:site_name} by {recipient.email} :
+{if:files>1}Several files{else}A file{endif} you uploaded {if:files>1}have{else}has{endif} been downloaded from {cfg:site_name} by {if:files.first().transfer.get_a_link}a transfer link{else}{recipient.email}{endif}:
 
 {if:files>1}{each:files as file}
   - {file.path} ({size:file.size})
```

These files are generated from poeditor. So updates there and PRs against those files will be silently overridden during the next import from poeditor. I might look to update the en_AU translation there in a moment. I am happy if you update the Czech poeditor translation as you may have more success with a natural sounding translation than me :)

There are two poeditor projects now, one for 2.x of FileSender and one for 3.x. So there are really `count($langs) * 2` updates that are on the cards.

There are notification options on poeditor to help in mass communication. I have also been wondering if we should also have a translation mailing list separate to that alongside the development list etc which is just for i18n discussions.

**Comment by monkeyiq** [comment]
en and en_au are both updated for 2.x and 3.x in poeditor.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the prompt and helpful reply!

I'm glad I did not attempt to send a PR - this would indeed have been wasted.

Happy to contribute the Czech translation in the poeditor.  I found the link to the FileSender 2.0 poeditor project in CONTRIBUTE.md, but so far cannot find the link for FileSender 3.0 - can you please share the link?

In FileSender 2.0,  I found the English version now shows the new template as the source - thanks for the quick action.

However, the template has `plain` and `html` alternatives - and the fix has been so far applied only to `plain`.  Can you please make the change also to the `alternative:html` section?  I'd then make the change to the Czech translation.

Cheers,
Vlad

**Comment by monkeyiq** [comment]
I added the link to the poeditor project for FileSender 3.x to CONTRIBUTE.md here https://github.com/filesender/filesender/pull/1981/files

I updated the html versions on poeditor now too. I left a space between  the email and the ":" as was originally there in the plain text version. I assume this was to allow folks to pick the email address without the client adding the : to the mix and making things more difficult. 

I left the full stop out of the html version if there is an email address. I think maybe leaving the email not as a link might help to have some spam filters less likely to pick up the notification message as a fishing thing.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks!  I've now updated the Czech translations in the FileSender 2.0 project - and I'm awaiting approval to join the FileSender 3.0 project.

Cheers,
Vlad

PS: The punctuation layout with this motivation looks very reasonable to me - I've followed this pattern in the Czech translation.

**Comment by vladimir-mencl-eresearch** [comment]
@monkeyiq , FYI, poeditor still says my participation in FileSender 3.0 translations (Czech) is pending - is it something you can approve?

**Comment by monkeyiq** [comment]
You should be good to go now. I use an admin account to login to poeditor and don't receive the emails from that so was a bit out of the loop.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks, permissions now received and I've now also done the 3.0 Czech translation update for this issue.

**Comment by monkeyiq** [comment]
Cool. I will do a mass pull of poeditor over to github later today!

**Comment by vladimir-mencl-eresearch** [comment]
Thanks!
