### ISSUE TITLE
Mention `curl -O -L -J -R "${direct_link}"` option for downloading unencrypted files directly with curl

### ISSUE THREAD

**Issue by ghuls** [filesender/filesender#1985]
Mention `curl -O -J -L -R "${direct_link}"` option for downloading unencrypted files directly with cURL on the download page (e.g. under `Direct Link:`, or add a `Download as cURL script` button.

`Direct Link: https://server.com/download.php?token=6ae29abc-6cc2-4b07-bdec-f401ce164c3b&files_ids=2936194`

```
$ curl -O -J -L -R 'https://server.com/download.php?token=6ae29abc-6cc2-4b07-bdec-f401ce164c3b&files_ids=2936194'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1266M  100 1266M    0     0  41.8M      0  0:00:30  0:00:30 --:--:-- 42.0M
curl: Saved to filename 'myfile.txt.gz'
```

**Comment by monkeyiq** [comment]
We could make this a small informational page. Include `wget` commands and if the file is encrypted mention the python and nodejs clients which can download and decrypt those from the command line.

**Comment by WebSpider** [comment]
Wouldn't it be better to put this in the documentation instead of in the software release?

**Comment by ghuls** [comment]
> Wouldn't it be better to put this in the documentation instead of in the software release?

I think it would make more sense to have it (linked) on the download page as an end-user does not necessarily knows this documentation exists when a download link is send to them by someone else.

For example in my case, when I recieved the download ling I assumed at first that filesender was just a homegrown application of my university instead of being an open source project.

**Comment by WebSpider** [comment]
I see your point. I guess it makes a lot of sense to link to our documentation page in the footer.

**Comment by monkeyiq** [comment]
I have captured some commands into a new page. I also mentioned how to download the archive which is less straight forward but one might like to do it for a larger download especially if you are downloading over ssh+tty manager to a remote machine which may be on around the clock and the laptop not so much.

**Comment by monkeyiq** [comment]
I might add a link to this under "Transfer details" in the 3.x UI. It can always be removed if it is considered offensive to the layout.

**Comment by monkeyiq** [comment]
I have added that link now. Also expanded the user docs page to describe the web UI first and then the command line tools.
