### ISSUE TITLE
storage_filesystem_hashing creating directory but saving files in root path.

### ISSUE THREAD

**Issue by kdermody** [filesender/filesender#200]
When I turn on storage_filesystem_hashing, it creates the separate directories as would be expected, but the file isn't saved in the directory, it's left in the storage_filesystem_path.

Before uploading file
```
root@burly:/azure/fs20b2# ls -lha
total 8.0K
drwxrwxrwx 4 root root 4.0K Dec 12 16:02 .
drwxrwxrwx 3 root root 4.0K Dec 12 10:26 ..
drwxrwxrwx 2 root root    0 Dec 12 14:58 log
drwxrwxrwx 2 root root    0 Dec 12 15:07 tmp
```

After uploading file
```
root@burly:/azure/fs20b2# ls -lha
total 113M
drwxrwxrwx 5 root     root     4.0K Dec 12 16:07 .
drwxrwxrwx 3 root     root     4.0K Dec 12 10:26 ..
drwxr-xr-x 2 www-data www-data 4.0K Dec 12 16:07 b
-rw-r--r-- 1 www-data www-data 113M Dec 12 16:07 b6bbe2b4-144a-ce48-3fa5-277abda1de4d
drwxrwxrwx 2 root     root        0 Dec 12 14:58 log
drwxrwxrwx 2 root     root        0 Dec 12 15:07 tmp
```

filesender-2.0-beta2

**Comment by monkeyiq** [comment]
once the CI has finished I will be merging https://github.com/filesender/filesender/pull/201 which fixes this issue and some others.  I have 176, 177, 178 and 200 (this) on the radar for very short term resolution.

This issue has likely not helped your performance testing as files were not being distributed as one would expect.

For longer term assurance I have created the following CI extension issue https://github.com/filesender/filesender/issues/202.
