### ISSUE TITLE
Version Check for CVE

### ISSUE THREAD

**Issue by BWar81** [filesender/filesender#2006]
Hello,

I have been made aware of the below CVE and I was wondering if someone could advise me how I can check what exact version of FileSender I am running please?

https://filesender.org/vulnerability-in-filesender-versions-below-2-49-and-3-x-beta/

Many Thanks,

Ben

**Comment by monkeyiq** [comment]
You could look at the `CODE_VERSION` in classes/utils/Version.class.php. 

That is updated by hand so has been susceptible to being stale from time to time. It will at least give a good starting point as to what version you are on.

**Comment by BWar81** [comment]
Hello,

That's great thank you very much, I am running version 2.48. Is there a documented process on upgrading from 2.48 to 2.49 anywhere please?

Many Thanks,

Ben

**Comment by monkeyiq** [comment]
The upgrade notes are at 
https://docs.filesender.org/filesender/v2.0/upgrade/

I will also take a bit of a look at them to see if they need some updating themselves.

**Comment by BWar81** [comment]
Thank you very much, that's worked quickly and perfectly!

**Comment by brucellino** [comment]
Is there any way to find this information from the API or web interface? My use case is testing a deployment for compliance and one of the tests is that the correct version is deployed.

**Comment by brucellino** [comment]
Ok, my bad, I found https://github.com/filesender/filesender/pull/1654
