### ISSUE TITLE
Bug in UI after adding duplicate files to the Transferfile upload dialog

### ISSUE THREAD

**Issue by so010** [filesender/filesender#2020]
If the user is adding a duplicate file to the uplaod dialog, the next button is not clickable (is grayed out). That is expected. If the user now is removing one of the dublicates the button is stil greyed out (not expected). 

If the user adds another valid file after or is removing another one from file list the next button becomes clickable again.

This bug was identified from european commision under demonstartion of EOSC-filesender service.

**Comment by monkeyiq** [comment]
I am assuming this is for FileSender 3.x from mention of the Next button. Other information I have also suggests v3.x.

From local testing on `development3`. If I add in two files with the same name, one is shown as a "Duplicate file".

If I delete the "Duplicate file" entry then all is well and the next is available right away.

If I delete the file that is not marked as the duplicate then I still see the red markings for the "Duplicate file" and the next button is not available. Adding files does not help here, as long as the "Duplicate file" is still shown (which is not a duplicate any more as I have deleted the other duplicate) then I can not upload.
