### ISSUE TITLE
Filesender 3.0rc3 - Admin page issue

### ISSUE THREAD

**Issue by kmihalj** [filesender/filesender#2035]
Well transfers are here, but click on any gives "transfer not found" .... no any info on any transfer except my own, I can get data from database, but preffered is from GUI like in versions 2.xx.

**Comment by monkeyiq** [comment]
I can confirm that this shows 'transfer not found' in `development3` but works in `development`.

**Comment by madsi1m** [comment]
Yup, it seems an admin can open his own transfers and vouchers from the admin page but all others are "not found"

**Comment by monkeyiq** [comment]
From investigation this come in when I tighten up security around viewing transfers. I will create a PR to relax that again for admin users.

**Comment by madsi1m** [comment]
thought i would give vouchers a go https://github.com/filesender/filesender/pull/2051

**Comment by monkeyiq** [comment]
@madsi1m Thanks for the patch for vouchers! I made a slight tweak there and merged voucher support for admin now.

**Comment by madsi1m** [comment]
saw that, seems to work in our test env 👍
Will close this
