### ISSUE TITLE
How many historic transfers does filesender retain

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#2056]
Hi,

I would like to know how long ago does FileSender keep record of all the transfers that I have made in the application under "My Transfers". Can I be able to view all the transfers I have made in the application under "My Transfers" or it only show recent transfers?

**Comment by monkeyiq** [comment]
You should be able to see all transfers that have not expired. Once a transfer has expired you may be able to see it under closed transfers but will be unable to download it. The transfer might be removed from closed transfers after a while depending on how the FileSender instance is configured.

The default number of days before a transfer expires is set in your config.php
https://github.com/filesender/filesender/blob/development/docs/v2.0/admin/configuration/index.md#default_transfer_days_valid

**Comment by monkeyiq** [comment]
If there is more information you would like please reopen the issue with follow ups.
