### ISSUE TITLE
Multiple landing pages on my filesender instance

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#2069]
Hi, 

I sometimes tend to land on multiple pages when accessing the filesender instance in my organization. what could be cause of this.
Below are the different landing pages that I land on. The first one is the rightful one that I should be landing on as per the instance configuration. Kindly assist

![image](https://github.com/user-attachments/assets/9059b24f-98a8-4a83-8267-c3004acd1dad)

![landingpage2](https://github.com/user-attachments/assets/05d56eca-9da0-47ac-8dd1-5e37f4b92d2d)

**Comment by madsi1m** [comment]
Looks like you are modifying one of the language files and user's browser language settings are set to something else?

We do the following to force `en_AU`, you could do the same or similar in `config.php`:
```
$config['default_language'] = 'en_AU';
$config['lang_selector_enabled'] = false;
$config['lang_browser_enabled'] = false;
$config['lang_userpref_enabled'] = false;
$config['lang_url_enabled'] = false;
```

**Comment by thuso607** [comment]
Thank you. this solved the issue.
