### ISSUE TITLE
issue with v3.0rc4 max transfer days array

### ISSUE THREAD

**Issue by gjburg** [filesender/filesender#2075]
In RC4 but also in earlier versions the config vlaue max_transfer_days_valid isn't correctly picked up in the frontend because the pull doen array only accepts 7, 15, 30, 40. 

However we've set it to max of 10 days, then the only option during upload is 7 days. 

can you please fix the array in the upload_page.php line 167

this will fix it. 
$possibleExpireDays = array( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 30, 40 );
$expireDays = array_filter(array( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 30, 40 ), function($k) {
    return $k < Config::get('max_transfer_days_valid');
});

**Comment by monkeyiq** [comment]
I think pulling the `$possibleExpireDays` out to a config setting with the default `7, 15, 30, 40` is the best move. This will allow sites to set it to their desire and the filtering code in there will take care of trimming it to valid dates.

**Comment by madsi1m** [comment]
or use the good old datepicker from FSv2:
```
$config['ui_use_datepicker_for_transfer_expire_time_selection'] = true;
$config['ui_use_datepicker_for_guest_expire_time_selection'] = true;
```
