### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by bartjkdp** [filesender/filesender#21]
I would like to create a Dockerfile for Filesender as at Stichting Pleio we deploy it on our Kubernetes infrastructure. Would you like to have a Dockerfile in the repository as well? What kind of requirements would you have on the Dockerfile? Some ideas:

- Make image as small as possible.
- Persistency by mounting volumes from outside the container.
- Configuration through environment variables?
- Should we include SimplesamlPHP? I think yes, configurable by environment variables.
- Specific PHP settings to include?

**Comment by madsi1m** [comment]
Hi bart-j,

We at AARNet, are also looking into doing this.

At the moment we are thinking of one of two extremes, First all in one container, Second, splitting up Filesender into micro services and combine it with other things we provide. For example:

container(s) for apache
container(s) for php-fpm
container(s) for database
volume container(s) for the web code, with or without non filesender web code
container(s) for load balancing

I guess it will be different per environment.

I'm not sure about including SimpleSAMLphp as they need to be configured differently per site, with cron jobs set up etc.

The great thing about filesender2s structure is how adaptable it is for different environments. In a way it’s almost like installing wordpress, one size does not fit all.

Cheers

**Comment by monkeyiq** [comment]
Docker images are now available for FileSender here
https://github.com/ualibraries/filesender-phpfpm

If this is still an active issue that you are keen to discuss feel free to reopen.
