### ISSUE TITLE
AUP settings broken?

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#226]
In the previous 1.6/1.7 release of Filesender the AUP function was working and according to the documentation is still supported, but I can't get it to work.

[](https://github.com/filesender/filesender/blob/master/docs/v2.0/admin/configuration/index.md#aupdefault:)

> aup_default
>     description: if set to 'true' the AuP (terms of service) checkbox (if enabled) is already pre-ticked for the user
> 
> aup_enabled
>     description: If set to 'true' the AuP (terms of service) checkbox is visible AND mandatory for the user to tick.

Our config:
```
$config['aup_enabled'] = true;
$config['aup_default'] = false;       // AuP value is NOT already ticked
```
But no acceptable use policy tickbox appears....

**Comment by monkeyiq** [comment]
This seems to be the same issue reported by William van Santen on the filesender-dev mailing list. 
```
* In filesender 1.6 there is the possibility for a checkbox for accepting 
the terms and conditions of the service. We don't see this in 2.0:
```
