### ISSUE TITLE
Limits: ability to set maximum file size for encrypted files

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#229]
It is not possible to set the maximum encryption file size

Feature request: possibility to configure the maximum file size for files a user want to encrypt. Our test (mac os with firefox) result in failed file decryption for files with a filesize from 2GB and up.

This was originally reported by William van Santen on the filesender-dev mailing list.

**Comment by monkeyiq** [comment]
I split this out with the "maximum encryption file size" part here and support for encrypted files over 2gb issue being in https://github.com/filesender/filesender/issues/230

**Comment by fransward** [comment]
Check! I've set the max_transfer_encrypted_file_size at 2GB:
`$config['max_transfer_encrypted_file_size'] = 1 << 31 ; 2^31 bytes = 2GB`
