### ISSUE TITLE
SimpleSAMLphp 1.15.3 support

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#262]
Hi, we are wanting to move to SimpleSAMLphp 1.15.3 which has security fixes, but filesender doesn't seem to work with it.

Can this be looked into please?

Cheers

**Comment by madsi1m** [comment]
looks like namespace has changed pull request 266 should fix this

**Comment by monkeyiq** [comment]
I've merged PR https://github.com/filesender/filesender/pull/266
