### ISSUE TITLE
beta3-Upload page-Encryption

### ISSUE THREAD

**Issue by GR0Y** [filesender/filesender#263]
Hi,

on the upload page, immediately at the connection, an alert indicates the password is too short while the box is not checked.
I tested by changing the default values (0) for 'encryption_min_password_length' => 4 and 'encryption_generated_password_length' => 4
and I get the same result.
![upload_page_sorry_passwd](https://user-images.githubusercontent.com/35217474/36834694-9abf785a-1d2b-11e8-9210-f22da2f556b3.png)

**Comment by monkeyiq** [comment]
I just ran a test with the following:
```
$config['encryption_min_password_length'] = 4;
$config['encryption_generated_password_length'] = 4;
```

In Firefox when you enable File Encryption you see the red sorry your password is too short message. It doesn't show if encryption is unchecked.

![password-too-short](https://user-images.githubusercontent.com/387108/36952834-82aa2ba6-2060-11e8-9d35-b085508ebb93.png)

Does the message appear and disappear properly when you have file encryption enabled and change the length of the password?

**Comment by GR0Y** [comment]
Hi,
Sorry, it's me. 
I have put my default.css modified from beta2 to beta3
