### ISSUE TITLE
beta3-Download_page-Encryption_css

### ISSUE THREAD

**Issue by GR0Y** [filesender/filesender#264]
Hi,

on the download page, the layout is bizzare.
- a 1 or a 0 in the lower left if the file is encrypted or not, it's debug mode ...
- a warning message appears systematically (relative to the unsupported browser) tested on IE11, Edge and FF Quantum.
![download_page_beta3](https://user-images.githubusercontent.com/35217474/36834892-41e6cd72-1d2c-11e8-8600-89d2372ac6f7.png)

Regards,

**Comment by GR0Y** [comment]
For the bizarre layout, it's just the <div class = "boxnoframe"> to replace with <div class = "box"> in download_page.php

**Comment by monkeyiq** [comment]
The 0 or 1 you are seeing is generated in download_page.php at line 129. See https://github.com/filesender/filesender/blob/master/templates/download_page.php#L128
The 0 or 1 is there to communicate from the php to the js this information, though the user shouldn't be seeing it.

The first issue is that the not_displayed css class is not having an effect for you. If you use a browser inspector is the https://github.com/filesender/filesender/blob/master/www/css/default.css#L1339 element being applied to the div tag?

The encryption warning message is triggered based on if FileSender thinks the browser supports the right crypto api. My first line of testing is on Firefox Quantum 58+. I don't see the encryption warning here. It should only be triggered by older IE versions.

The box layout was explicit, I didn't think the outer box added anything but clutter to the page. There are a number of areas in the current UI with dark lines and boxes that do not really offer anything to the user. So there is no box around the telecharger and content. Maybe we could make that part of the theme system or just revert it to having a box. Ultimately using something like bootstrap would help mitigate design issues from the codebase to an explicit theme.

**Comment by GR0Y** [comment]
idem, with the good default.css it's ok.
