### ISSUE TITLE
Upload whole directory, including subdirectories

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#28]
(Forwarding a request from one of our users)

FileSender allows uploading multiple files at once, but there is no support to upload an entire directory including subdirectories. It would be great if this can be implemented. Is there a Javascript solution to do this?

**Comment by jornane** [comment]
Seems like it's being worked on in #298

**Comment by monkeyiq** [comment]
This is in the dirtree support merged into 2.0-rc1 (disabled by default).
