### ISSUE TITLE
Generated .ZIP of 1GB fails decompression with macOS built-in Archive Utility

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#295]
When testing FileSender beta4, I've uploaded 82 files in one transfer totalling just under 1GB. The resulting .ZIP file cannot be extracted using the macOS built-in Archive Utility, but it can be extracted using The Unarchiver without any problems. However, since the file was under 4GB, no warning was displayed to the user.

I don't know the reason that the file failed extraction, but I have noticed that changes were made to the ZIP code between beta2 and beta4. If there are regressions that prevent the Archive Utility from working, these should be documented, and users should see a warning near the download button explaining the situation.

![Archive Utility error](https://user-images.githubusercontent.com/767872/38956990-8de4b6be-4359-11e8-9ec1-692cfb2d1410.png)

**Comment by monkeyiq** [comment]
Prior to recent beta releases, zip64 functionality was broken for large archives (4gb+ did not work). 
We should display the warning to osx users now that they will need the unarchiver.

**Comment by monkeyiq** [comment]
I have just updated the download page to make this clearer https://github.com/filesender/filesender/pull/512/files

I think it is possibly more confusing if the archive format changes depending on size (zip32 to zip64) as the user will be accustomed to zips working and then find an issue if and when they download a larger file (so after a larger download investment). The real solution is to offer archive formats that are better handled by the native platform https://github.com/filesender/filesender/issues/325
