### ISSUE TITLE
Cronjob failes

### ISSUE THREAD

**Issue by janwout** [filesender/filesender#297]
I am calling cron.php from a browser. But it fails with a 500 error:

PHP Fatal error: Uncaught StorageFilesystemCannotDeleteException: storage_filesystem_cannot_delete in /app/classes/storage/StorageCloudS3.class.php:203

I have storage type 'filesystem' configured in config.php. I am trying to find out why StorageCloudS3.class called when i run cron.php? Somebody got an idea?

**Comment by janwout** [comment]
wrong storage_file_class in database was the issue

**Comment by meijer** [comment]
Good to hear it's resolved. Was this a typo at your end or something we can improve in the documentation?

**Comment by janwout** [comment]
It was a leftover from testing with a S3 backend. So user Error

**Comment by meijer** [comment]
OK, tnx for sharing!
