### ISSUE TITLE
Possibility to set date format

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#299]
FileSender uses dd/mm/yyyy for the expiry date format, but according to the descriptive text it uses dd/mm/yy. I would like to change our setup to use the ISO format, which is yyyy/mm/dd. I don't think it's possible to set the date format at this time, but maybe this could be a config option?

**Comment by yent** [comment]
Afaik you can do that in translations using date_format (for display) and dp_date_format (for date picker format as it uses a slightly different kind of format string) but not in config.

**Comment by jornane** [comment]
Would it be an idea to make this configurable? As it is now I can change the format in our own instance, of course, but this requires patching and then maintaining it myself.
