### ISSUE TITLE
When logging is turned off a log file is generated anyway

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#306]
If you elect to turn off logging then a log file can sometimes be created anyway. If you want no logging that is what you should get.

**Comment by monkeyiq** [comment]
It is dubious if I should make the below settings mean "no logging". They both currently generate an error that the config is bad which I think is more explicit given the above method of "logging to the function that happens to do nothing".
```
$config['log_facilities'] = null; 
$config['log_facilities'] = array(array());
```

**Comment by monkeyiq** [comment]
I have also updated the configuration page to help keep this information easily available
https://docs.filesender.org/v2.0/admin/configuration/#log_facilities

**Comment by jornane** [comment]
Maybe you could make a "null logger" facility, to make not logging more explicit?
