### ISSUE TITLE
drag & drop not working

### ISSUE THREAD

**Issue by baumrasen** [filesender/filesender#321]
On the upload-tab the drag & drop-field is not working (on Chrome or Edge with Windows 10). Nothing happens if I drag an file and drop it in the field. It is a fresh installation with "release 2.0 rc1".

**Comment by glbrimhall** [comment]
Confirmed the bug exists if:

$config['disable_directory_upload'] = false;

is not present in config.php

short term fix: add the above config parameter to your
filesender/config/config.php

long term fix:in filesender/www/js/upload_page.js

Change:

        if (typeof filesender.dragdrop.addTree === "function") {

To
        if (filesender.dragdrop &&
            typeof filesender.dragdrop.addTree === "function") {

-geoff Brimhall

**Comment by madsi1m** [comment]
can the long term be put in a pull request?

**Comment by glbrimhall** [comment]
Ya, I'll get that going tonight.

-geoff

**Comment by glbrimhall** [comment]
Just submitted the pull request #322 to fix issue #321.
