### ISSUE TITLE
Ability to create a tar archive as well as zip

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#325]
One platforms like osx and Linux the ability to download a tarball might be more convenient than a zip file. For example, on osx a tarball can be extracted from finder by double clicking on it. For osx this would get around the zip64 issue by not needing any additional software install in order to deal with larger archives.

**Comment by monkeyiq** [comment]
Offering tar links by default on osx will also get around this issue https://github.com/filesender/filesender/issues/295

**Comment by jornane** [comment]
An additional advantage of tar is that the filesize is known in advance, which means that you can send a Content-Length header.

**Comment by monkeyiq** [comment]
The above PRs 513 and 514 bring this in.
