### ISSUE TITLE
Database schema: Handle transfer options in a more db friendly way

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#327]
Many transfer options are currently stored in a JSON text field in the database inside the Transfer.options column. This includes very common information that is not going to change or be deleted from the code any time soon such as if a transfer is encrypted or not. 

Having a json field seems to allow extensibility but winds up making SQL queries harder cross database, queries are much more inefficient (infix string match), use more storage, and there is no data type enforcement. For example encryption might be set to an array or string instead of a boolean 

The database migration script already allows new columns to be added so there is flexibility without having to fall back to a json string. Using explicit columns also lets the RDBMS enforce that encryption is boolean for us.

Most of the boolean options should be split out from the Transfer.options and the database migration script updated to allow existing data to be split out in this manner during upgrade.

**Comment by jornane** [comment]
Just curious, in what situation would you need a select query for certain transfer options?
