### ISSUE TITLE
please publish sources for debian packaging

### ISSUE THREAD

**Issue by joostvb-gh** [filesender/filesender#330]
Hi,

At http://repository.filesender.org/debian/ , binary debian packages of filesender are published (thanks a lot for that!).  I stumbled upon a problem with this packaging, and would like to fix that, and send
you a patch for it.  Having a copy of the debian/control , debian/rules and other debian packaging
files would be helpful for that.

Thanks, Bye, Joost

**Comment by monkeyiq** [comment]
I am happy to include the files from debian into the main repository. Hopefully there is a more elegant solution than extracting them from filesender_1.7~beta1_all.deb and bringing those in.

**Comment by joostvb-gh** [comment]
Hi monkeyiq,

thanks for your reply.  Unfortunately, files like debian/rules , debian/watch and debian/control do not
end up in the binary .deb package.  Unless we find back the sources, we'd have to reconstruct these
from scratch...   Maybe they're somewhere in some git repo, or perhaps some filesender*.debian.tar.xz files could be found somewhere?

Bye, Joost

PS & FYI: I've just published https://non-gnu.uvt.nl/debian/stretch/filesender/filesender_1.7~beta1~uvt1_all.deb  which just might work on current debian stable.

**Comment by joostvb-gh** [comment]
any news on this?   http://repository.filesender.org/debian/ is still lacking .dsc and .debian.tar.xz .
any plan on packaging newer releases?  we'd like to start using the multiple-file-upload features
on our debian platform.

Thanks, Bye, Joost

**Comment by monkeyiq** [comment]
I did manage to find some old files, hopefully they are of use at least for a start. I think maybe having them in the main repo is useful in that at lease they are in a known place. I will merge them in soon https://github.com/filesender/filesender/pull/510. They reference the old assembla site so are fairly dated at this stage.

**Comment by joostvb-gh** [comment]
Hi,

Thanks for this update.  For my employer it's unfortunately no longer relevant since we're no longer using our own hosted filesender instance.  However, for anybody else interested in working on the
debian packaging availability of the sources is still very helpful.  So, thanks again for tackling this one.

Bye, Joost

**Comment by monkeyiq** [comment]
I might close this for now. If anybody wants to make a PR on the new debian subdir once I merge it please feel free!
