### ISSUE TITLE
config option for the tmp directory

### ISSUE THREAD

**Issue by baumrasen** [filesender/filesender#332]
it would be nice to have a config option to make it possible to change the location of the tmp directory

**Comment by monkeyiq** [comment]
I have introduced a new config variable and function for this. Though it is only used in a few places at the moment. At least it is a base to start to move towards.
https://github.com/filesender/filesender/blob/master/classes/utils/Filesystem.class.php#L121

**Comment by monkeyiq** [comment]
https://github.com/filesender/filesender/blob/c340b7c4f0572e336a464666d1560ba0d26e8063/classes/utils/Filesystem.class.php#L121

**Comment by WebSpider** [comment]
It seems this issue is solved?

**Comment by WebSpider** [comment]
You can use `tmp_path` config option to change the location of the tmp directory
