### ISSUE TITLE
Math.random() is not a CSPRNG

### ISSUE THREAD

**Issue by fkooman** [filesender/filesender#334]
https://github.com/filesender/filesender/blob/1901e8d561220ac4a8ec034e52b7b80e46359867/www/js/upload_page.js#L1018

MDN writes:

> Math.random() does not provide cryptographically secure random numbers. Do not use them 
> for anything related to security. Use the Web Crypto API instead, and more precisely the 
> window.crypto.getRandomValues() method.

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

**Comment by fkooman** [comment]
Some suggestions:
- choose a safe password length and use that always, do NOT make this configurable;
- use a **constant time** encoding function and only use one, do NOT make this configurable.

**Comment by monkeyiq** [comment]
The original issue was addressed with https://github.com/filesender/filesender/pull/337.

It has been recommended that much of the security settings become non configurable. I defer the removal of configuration of these to a later policy choice.

**Comment by fkooman** [comment]
> It has been recommended that much of the security settings become non configurable. I defer the removal of configuration of these to a later policy choice.

You could at least have a policy as to not introduce more in the meantime ;-)

**Comment by monkeyiq** [comment]
It is also quite simple to make some of these configuration settings read only or forced to a system policy. By continuing to use the config system the magic constants can be collected in a single location.
