### ISSUE TITLE
cron-handle-shred-files.php loops. May need file locking

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#357]
We noticed that the cron job that handles the deletion of the shredded files (cron-handle-shred-files.php) doesn't do its job correctly.
As a result we encounter diskspace shortage. 

When this job wants to wipe a file that doesn't exists anymore, it will stay in a loop, trying  to delete that file over and over again, without proceeding.  

Can this process be made more robust? Maybe by adding some kind of 'locking'?

**Comment by fransward** [comment]
I saw the following select from the cleanup job:
`"SELECT * FROM Transfers WHERE expires < '2018-07-04' ORDER BY expires ASC;" `
Does this mean that it goes all the way back to the beginning?

**Comment by fransward** [comment]
And the code:
```
// Delete expired audit logs and related data
foreach(Transfer::allExpiredAuditlogs() as $transfer) {
    Logger::info($transfer.' auditlogs expired, deleting them and deleting transfer data');
    AuditLog::clean($transfer);
    $transfer->delete();
}
```
implies that a transfer will only be deleted when the auditlog is expired. After 31 days in our situation. 
While we have these settings in place:
```
$config['default_transfer_days_valid'] = 14;
$config['max_transfer_days_valid'] = 21;
```
So, it will expire the transfer after 14 days, but will delete the transfer only after 31 days.
This explains why we see files older than our max. transfer days valid.

**Comment by WebSpider** [comment]
@fransward is this issue still valid?

**Comment by fransward** [comment]
@WebSpider Probably not, but wouldn't know for sure since I am not involved in Filesender anymore. 
I would close the issue.....
