### ISSUE TITLE
Feature Request: Modify email notifications on an existing transfers

### ISSUE THREAD

**Issue by mdusher** [filesender/filesender#358]
On the "My Transfers" page, it would be nice if a user was able to modify the various email notification options on their currently available transfers instead of just being show which ones were enabled when the transfer was created.

The reason for this request is that we initially had the "email daily statistics" option enabled by default and have been receiving an increasing number of complaints about receiving too many emails per day from our FileSender service (these users were doing multiple transfers, all with the daily statistics option enabled - so they were receiving 7-8 of them daily).

**Comment by WebSpider** [comment]
This should be solved in #801

**Comment by WebSpider** [comment]
Since this issue has a fix merged and no new reports have been made since 2020, I'm going to assume this issue is solved.
If not, feel free to open a new issue, and refer to this one.
