### ISSUE TITLE
encryption: key is regenereated for each blob and could be cached instead

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#374]
Each time a new chunk (blob) is read for upload the TeraSender (and I assume other chunk related code  paths) call crypto_app().encryptBlob() such as: https://github.com/filesender/filesender/blob/master/www/lib/terasender/terasender_worker.js#L139

Inside encryptBlob and decryptBlob this.generateKey() is called each time. Such as https://github.com/filesender/filesender/blob/master/www/js/crypter/crypto_app.js#L38

The encryption key should likely be cached rather than potentially regenerated each blob. This caching could be done completely inside generateKey() to avoid larger code changes https://github.com/filesender/filesender/blob/master/www/js/crypter/crypto_app.js#L23

**Comment by fkooman** [comment]
https://github.com/filesender/filesender/issues/377

**Comment by monkeyiq** [comment]
There is an issue with trying to do this in that each chunk is encoded with it's own IV. That IV has to be passed to deriveKey() to setup the cipher for the block. So it isn't possible with the API.

**Comment by monkeyiq** [comment]
My above comment about the IV during keygen is how the code is but not how the code needs to be, for example the parameters for pbkdf2 do not include the encryption IV:

https://www.w3.org/TR/WebCryptoAPI/#pbkdf2-params

This unlocks the possibility to refactor the code and then sustain much higher pbkdf2 iteration counts with a once off (per terasender worker) impact on cipher performance during upload. And download speeds will be acceptable with larger files and high pbkdf2 round counts. The security should be unchanged by this optimization as it is just replacing many unnecessary calls to deriveKey with one call and reuse of the cached key. There are some other implementation details there for sure. The catch is realizing that the codepath is executed both in main context and web worker contexts so it has to be resilient to that, which may be what lead to the key handling in the current implementation.

Regarding the rolling your own crypto, replacing the whole crypto system and migrating away from WebCrypto to something else that provides an ultra high level API to out of order chunked uploads is likely something to be discussed in another issue, and is a matter for the filesender board to decide on.

**Comment by monkeyiq** [comment]
This has been addressed in the above merges
