### ISSUE TITLE
make it easy to install development environment

### ISSUE THREAD

**Issue by fkooman** [filesender/filesender#379]
It would be really helpful to have an easy to install development setup, e.g.:

```
$ git clone https://github.com/filesender/filesender.git
$ cd filesender
$ composer install # install (dev) dependencies
$ phpunit # to run the unit tests
$ cp config/config.php.example config/config.php
$ php -S localhost:8080 -t www/ # to run a PHP web server for quick tests on local machine
```

Having to install simpleSAMLphp, PostgreSQL is a lot of work and not that easy. Maybe the default can be SQLite with HTTP Basic Authentication and no additional external dependencies.

**Comment by peter-** [comment]
With `auth_sp_type = fake` this should work without any SimpleSAMLphp configuration? Otherwise why do the parameters `auth_sp_fake_*` exist? That should be even easier than using SimpleSAMLphp's `exampleauth` module.

Using SQLite sounds interesting, though, I support the idea trying to see how far one can take this. (FWIW, I've recently played with [H2](http://h2database.com/html/main.html) in embedded more for a Java-based project, which worked well. I doubt it's worth it, but for completness I'll mention that [per their docs](http://h2database.com/html/features.html#feature_list) H2 could also be accessed using the PostgreSQL ODBC driver, without any Java.)

**Comment by fkooman** [comment]
> With auth_sp_type = fake this should work without any SimpleSAMLphp configuration? Otherwise why do the parameters auth_sp_fake_* exist? That should be even easier than using SimpleSAMLphp's exampleauth module.

 I didn't know these options existed. So it is already possible to test FS without also installing simpleSAMLphp? Nice!

> I support the idea trying to see how far one can take this. 

The point was not to see how far, but how to make things easier to deploy, both for development and production.

> The other obvious kind of reply these days is to use containers for additional services, even/esp. in test envs.

That's like giving up and admitting you lost control of your "stack".

**Comment by fkooman** [comment]
> IIRC mysql allows you to run a local 'instance' where you use the library and do not need a real system wide database install. 

Not sure what that is, but if that works out of the box, why not!

> It would be interesting to see how well SQLite could work as the RDBMS. 

Very well actually. It is used by a lot of software and very stable, fast and not to mention easy to use!

> Given the differences between mysql/mariadb and postgresql that are already catered for I would expect some additional effort getting the SQLite filesender backend to operate at 100%.

Well, the most obvious approach would be to use "standard SQL" so there is nothing special required for the various databases.

**Comment by monkeyiq** [comment]
I continue to hope that the subset of SQL supported across multiple vendors will one day reach a point that things "just work" over multiple RDBMS. Doing interesting things across mysql 5.5, mariadb 10.x and postgresql 9.x raises enough edge cases to show that just those subsets are not overlapping as much as one might hope.

**Comment by monkeyiq** [comment]
I think I will refrain from comment.

**Comment by fkooman** [comment]
Sorry, I am not really being constructive here. I'm also not sure how much interest there is for this from the community, so maybe we can close this issue.
