### ISSUE TITLE
GDPR ability to disconnect a saml uid and reconnect it later

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#385]
The recent database update moves the saml auth information into it's own table. 

Now that the information linking a user to the saml auth system is separate it would be nice if a user could be "forgotten" by the system, for example, after 30 days. It would be even better if they could return and have the chance to be remembered again.

Perhaps storing a one way hash of the saml uid in the authentications table and scrubbing the real auth id would work. If a user returns again and there is no entry in the authentications table then the hash of the saml uid could be calculated and the hash looked up. There would be some risk of collision using hash functions so it may be that the user just is created a new each time if they were "scrubbed". 

To avoid the possibility of collision authentications entries might only deleted when the userpreferences entry is and thus the user was fully removed at the time they are "forgotten". So they have to be recreated if they return with a successful saml auth.

**Comment by fkooman** [comment]
> It would be even better if they could return and have the chance to be remembered again.

This is not forgotten.

>  storing a one way hash

Because of the (very) limited input domain, assuming EPPN is used for the user ID, it is not hard to find an identity from a hash.

A possible solution if you are using UIDs in many tables is to create a table with the "SAML UID" and another column with a randomly generated string that you use in the other tables where you need a UID. Then when deleting the row with "SAML UID" the connection to the data is lost. This may or may not be enough for GDPR. But it is a start. 

Using DB foreign key with "ON DELETE CASCADE" you can remove all related entries from other tables if you need to.

**Comment by monkeyiq** [comment]
> A possible solution if you are using UIDs in many tables is to create a table with the "SAML UID" and another column with a randomly generated string that you use in the other tables where you need a UID. Then when deleting the row with "SAML UID" the connection to the data is lost. This may or may not be enough for GDPR. But it is a start. 

This is sort of what the recent database update did. Previously the saml uid was scattered throughout the database. Now that is stored in the authentications table and the authid (autoinc pk of authentications) is linked to the userpreferences tuple for that user.  Things like transfers and clientlogs reference the userpreferences.id (which is now a auto inc pk integer) instead of the saml uid string as before.

Basically all the saml uid string references were collapsed into the authentications table and auto inc pk integers are used to link the other tables together. If one wants the saml uid it is linked from the userpreferecnces table through the authid reference.

I had considered rolling the authentications table into the userpreferences table but even though it is more or less 1-to-1 from an authentications record to a userpreferences record having two tables keeps things related grouped together. Also having the saml uid in a separate table (as now) allows links to be broken while data retiring can be handed as one might elect. Eg, a userpreference tuple might be completely disconnected from the authentications so we have no way to know anything about the saml uid they used but the data might live for 30 days (or whatever the file retire time is). And since there is now referential integrity we can start doing smart things when things are deleted.

**Comment by monkeyiq** [comment]
This shows the main migration from what was to the new integer based linking
https://github.com/filesender/filesender/pull/382/files#diff-6fd4e88d26443f1b59675210b24ffae2R340

**Comment by monkeyiq** [comment]
I think this issue will be shelved as it is better to allow real leaving if that is the intended action.
