### ISSUE TITLE
Empty accepttoc.html.php resulting in orphaned Terms and Conditions checkbox 

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#402]
Since commit a1890bfa the en_AU accepttoc.html.php file is empty, resulting in a lonely checkbox where you can accept the Terms and Conditions if you have this enabled.
The fix is to add the following line to the file again:
```
In /opt/filesender/filesender/language/en_AU/accepttoc.html.php
add:
I accept the following Terms and Conditions of using this service.
```

**Comment by monkeyiq** [comment]
I have just fixed this on poeditor and will link to the lang import that brings it back in

**Comment by monkeyiq** [comment]
This is currently fixed in at least en_AU and nl_NL. I have recently performed an import of all languages.
