### ISSUE TITLE
$config['user_quota'] = 0 not working as expected 

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#403]
According to the admin settings guide you can disable the user quota setting in the config:
```
$config['user_quota'] = 0; //set to 0 to disable. If set to a positive value it sets the per-user maximum
```
However, this results in an over quota error. 
To make this work I had to remove this setting from the config file altogether. (by commenting it out).

Changing the value to a positive one does work, and shows an upload quota, but setting it to 0 won't disable it...

**Comment by jornane** [comment]
Judging from the source code, setting it to `null` should work.

**Comment by fransward** [comment]
Confirmed!

**Comment by monkeyiq** [comment]
This should have been addressed in https://github.com/filesender/filesender/pull/415
