### ISSUE TITLE
CI: Sauce connect and jwt are deprecated (trusty vm upgrade)

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#404]
When updating the CI env to run on trusty I found that the use of jwt to generate limited time secrets is deprecated. I think this might still be working for older VMs but is removed for trusty now.
https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated

And on more digging this:
https://github.com/travis-ci/travis-ci/issues/9350

**Comment by monkeyiq** [comment]
The core of this is the setup of sauce connect https://docs.travis-ci.com/user/sauce-connect/ which wants JWT to work on pull requests, but jwt is discontinued https://docs.travis-ci.com/user/jwt without recommendation of forward plan "Unfortunately, there is no replacement or workaround for the jwt addon at this time." - https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated

Some projects seem to have disabled the functionality, some have created a work around https://github.com/ampproject/amphtml/issues/13047#issuecomment-378655495
Another way is having a server that is informed of the build and somehow triggers the sauce build and shuffles the good/bad results back to travis ci. But that also means adding and maintaining the server.

**Comment by monkeyiq** [comment]
It seems that as of now JWT is still working. But this might be a case of borrowed time.

**Comment by WebSpider** [comment]
Given CI is under reconstruction, this issue may become obsolete as well

**Comment by monkeyiq** [comment]
yeah it is fairly obsolete...
