### ISSUE TITLE
Errors DB upgrade on MYSQL

### ISSUE THREAD

**Issue by Veredior** [filesender/filesender#408]
Just tried to upgrade our filesender 2.0 server, but it seems there are some incompatibilities with a MySQL 5.5 database due to a Debian 8 install.

`[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021] "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'integer) as target_id_as_number  from AuditLogs' at line 1"
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021] Array
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021] (
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021]     [name] => exec
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021]     [args] => Array
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021]         (
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021]             [0] => CREATE OR REPLACE VIEW auditlogsview as select * , DATEDIFF(now(),created) as created_days_ago , cast( target_id as integer) as target_id_as_number  from AuditLogs
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021]         )
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021]
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021] )
[2018-08-31 13:49:33] [upgrade:error] [DBIUsageException details uid:5b892b4d92021]`

After some research, you cant use the CAST function like this `cast( target_id as integer)` instead you can do this : `cast( target_id as unsigned)`

I will create a merge request for this issue.

Second major issue is with the filesbywhoview view which contains a subquery, and this is a big no for all versions before MySQL 5.7.7 . One solution is to create a view for this subquery and call it in filesbywhoview view.

**Comment by madsi1m** [comment]
do we split this into two views? any performance hit?

**Comment by madsi1m** [comment]
oops, just noticed that 10.2 is minimum version for v2.3

**Comment by baumrasen** [comment]
We tested the upgrade from 2.1 to 2.3. (on Debian 9 with MariaDB 10.1.26.)
Running the database.php-script we got this error:

> "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes"
> [0] => CREATE  UNIQUE  INDEX Authentications_saml_user_identification_uid on Authentications (saml_user_identification_uid)

If we change the value in [Line 53 of Authentication.class](https://github.com/filesender/filesender/blob/master/classes/data/Authentication.class.php#L53) to 170 (like @monkeyiq mentioned [here](https://github.com/filesender/filesender/issues/394#issuecomment-414865584)
the script is working without any error.

Are there any problems if we leave it that way? Do we need the 255 chars?

**Comment by Veredior** [comment]
We can use the view from the class Transfer, problem is, the view from File is created before the view from Transfer.

**Comment by Veredior** [comment]
I managed to create the filesbywhoview view by replacing in `File.class.php` the lines between 116 to 121 by `. call_user_func('Transfer::getViewName')`.

There are many errors at the foreign keys creation, on mysql where you cant use 'IF NOT EXISTS' before the declaration of a foreign key. You have to check the existance of the foreign key before, there is a solution at this [URL](https://dba.stackexchange.com/questions/24531/mysql-create-index-if-not-exists)

Moreover, as the foreign keys authid and userid did not exist before 2.1, the initialization of those columns put the default value 0 for all rows. Problem is, mysql throws an error when adding the constraints (lines 486 to 488 in `scripts/upgrade/database.php`) because of the id 0. Workaround is to add `'null' => true` in `Guest.class.php line 52`, `Transfer.class.php line 57`, `User.class.php line 58`.

**Comment by madsi1m** [comment]
#413 commit 3c668c06fa734f3b7a63092f9790a939e931d2ca  passes the upgrade on our dev machine. Thanks Ben!

**Comment by monkeyiq** [comment]
@madsi1m cool! I had the suspicion that moving the CI back to 10.0 with a sprinkling of fixes might make life easier. The great part is that the Travis CI / Selenium tests are now run against both database backends rather than just postgresql, so things should continue to improve as the CI is expanded to include more testing.

Do you have any internal test scripts that might (or a public version) be able to run on Travis CI as well?

**Comment by monkeyiq** [comment]
@Veredior I thought it was strange that mariadb had the "IF NOT EXISTS" for key constraints but postgresql didn't. For postgresql I added propagation of Duplicate as a specific exception in the DBI (https://github.com/filesender/filesender/blob/master/classes/utils/DBI.class.php#L229) and happy to get and ignore that in the update script (https://github.com/filesender/filesender/blob/master/scripts/upgrade/database.php#L259). It seemed more efficient to use if not exists in mariadb (since 10.0.2 https://mariadb.com/kb/en/library/alter-table/) but it might be a good idea to fall back to postresql style on non mariadb backed mysql, or just in general as it is only a handful of keys.

**Comment by Veredior** [comment]
#414 pull request should fix the issues on mysql. I cant test for now on mariadb and pgsql.

**Comment by monkeyiq** [comment]
The core parts of 414 have been merged. As mentioned there, if there are cases where the use of foreign keys is presenting issues I would rather fix those cases than loosen the fk constraint to allow data in the database that is not linked to a specific user.
