### ISSUE TITLE
about_url, help_url unused or docs wrong

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#420]
[`about_url`](https://github.com/filesender/filesender/blob/master/docs/v2.0/admin/configuration/index.md#about_url) is not used anywhere in the code, it seems.

Suggested Resolution: Remove `about_url` from the docs.

---

[`help_url`](https://github.com/filesender/filesender/blob/master/docs/v2.0/admin/configuration/index.md#help_url) is still used in one place, in [`scripts/task/emailfeedback.php`](https://github.com/filesender/filesender/blob/master/scripts/task/emailfeedback.php), but:
  1. That's not consistent with the documentation that mentions a "referenced (local or external) HTML page" as value (which is not used that way in the code, and current code usage does not work with HTTP URLs, see issue below), nor is there code that would render the mentioned pop-up when this variable is set to an empty string.
  1. The remaining use current code makes of this variable will [throw an exception](https://github.com/filesender/filesender/blob/master/scripts/task/emailfeedback.php#L217) if the value of `help_url` is not an email address prefixed with `mailto:`, AFAICT.

Suggested Resolution: Update docs to match current code/behaviour. Possibly also rename the parameter, as the old behaviour is gone anyway (so backwards compatibility is not an option anymore) and a new parameter name could be more expressive of the new use this is being made of.

**Comment by monkeyiq** [comment]
Thank you for this very detailed bug report. Feel free to reopen if I missed something in my resolution.
