### ISSUE TITLE
No Identity provider available

### ISSUE THREAD

**Issue by wehzy** [filesender/filesender#435]
Hi,

I want to install Filesender on a server but I faced an issue on SimpleSAMLphp. There is no choice available to select. I'm a bit lost because I want to configure the username and password myself.

![image](https://user-images.githubusercontent.com/43643517/46147704-85150480-c266-11e8-9408-de94265f870e.png)

What can I do to solve my issue or to skip it ?

**Comment by peter-** [comment]
In case you haven't already, try the SimpleSAMLphp [documentation for setting up Service Providers](https://simplesamlphp.org/docs/stable/simplesamlphp-sp) or the [users mailing list](https://simplesamlphp.org/lists). The Filesender software has no influence on your issue and also this issue tracker isn't really a support forum.

**Comment by monkeyiq** [comment]
If you only want to configure a username and password (or small collection of them) see 
https://github.com/filesender/filesender/blob/master/docs/v2.0/faq/index.md#simplesamlphp-for-local-users-for-small-scale-setup-or-testing

**Comment by monkeyiq** [comment]
I am not too sure what else can be contributed to this issue. I don't think there is anything I can fix in the codebase to improve it so I will transition the issue to closed. People are welcome to continue to add items to it and reopen the issue if something can be changed in the FileSender code to help.
