### ISSUE TITLE
get_a_link pop-up misses download link when hard-coded

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#439]
When `available => true` is set for the `get_a_link` option in the `transfer_option` array the pop-up/overlay shown after the upload contains the full download link (which is the desired behaviour):

```php
$config['transfer_options'] = array(
  'get_a_link' => array(
    'available' => true,
    'advanced' => false,
    'default' => true,
  ),
);
```

![get-a-link_available_true](https://user-images.githubusercontent.com/4047365/47092412-3b955500-d227-11e8-8b47-bb741f16ca6f.png)

But when (only) changing `available => false` for this setting (causing the checkbox to disappear from the UI for uploads, and the parameter to always be active) after the upload completes the download link is missing from the pop-up/overlay:

![get-a-link_available_false](https://user-images.githubusercontent.com/4047365/47092431-4354f980-d227-11e8-851b-0fff555d5eb3.png)

(In both cases after the pop-up/overlay is closed one is taken to the transfer for the finished upload, and the download link can be seen there, though somewhat burried in lots of other information.)

The expected behavior is that whether _the same parameter_ is hard-coded in the config or set in the UI the result should be the same, in this case the pop-up/overlay should contain the download link.

**Comment by peter-** [comment]
**All** `transfer_options` and `guest_options` that have been set in `config.php` to be  `default => true` AND `available => false` (i.e., they're _active_ and _not shown_ to the subject in the web UI) are currently being silently ignored, as if they had not been set `default => true` at all.

(I tried to fix _one_ instance of that in #441 but all other options are still broken if they're not exposed in the web UI.)

**Comment by monkeyiq** [comment]
I have created an option to put the available=>false options into hidden form fields.
https://github.com/filesender/filesender/pull/471

The gain of doing this is that the code that checks options remains simpler.

**Comment by monkeyiq** [comment]
I will take a look at expanding transfer_options_not_available_to_export_to_client to other options we might like to expose when available=false

**Comment by monkeyiq** [comment]
The encryption option being badly nested sort of threw me off for a moment. 497 linked above allows the encryption to be used even when get_a_link is available=false and default=true.

**Comment by monkeyiq** [comment]
I have created https://github.com/filesender/filesender/issues/498 as a follow on from this to recheck in case the client has done anything funny to these mandatory options (available=false).
