### ISSUE TITLE
Incompatibility between Simplesamlphp 1.14.11 and Filesender cron

### ISSUE THREAD

**Issue by Veredior** [filesender/filesender#44]
Hi,
i would like to raise an incompatibility between Simplesamlphp 1.14.11 and the Filesender cron which returns the following error : 

```
PHP Fatal error:  Uncaught exception 'SimpleSAML_Error_Exception' with message 'Setting secure cookie on plain HTTP is not allowed.' in /usr/share/filesender/simplesamlphp-1.14.11/lib/SimpleSAML/Session.php:287
Stack trace:
#0 /usr/share/filesender/simplesamlphp-1.14.11/lib/SimpleSAML/Auth/Simple.php(54): SimpleSAML_Session::getSessionFromRequest()
#1 /usr/share/filesender/filesender-2.0/classes/auth/AuthSPSaml.class.php(69): SimpleSAML_Auth_Simple->isAuthenticated()
#2 [internal function]: AuthSPSaml::isAuthenticated()
#3 /usr/share/filesender/filesender-2.0/classes/auth/AuthSP.class.php(55): call_user_func('AuthSPSaml::isA...')
#4 /usr/share/filesender/filesender-2.0/classes/auth/Auth.class.php(104): AuthSP::isAuthenticated()
#5 /usr/share/filesender/filesender-2.0/classes/utils/Logger.class.php(282): Auth::user()
#6 /usr/share/filesender/filesender-2.0/classes/utils/Logger.class.php(190): Logger::log('info', 'Cron started')
#7 /usr/share/filesender/filesender-2.0/scripts/task/cron.php(37): Logger::info('Cron started')
#8 {m in /usr/share/filesender/simplesamlphp-1.14.11/lib/SimpleSAML/Session.php on line 287
```

There is an incompatibility when the simplesamlphp's parameter `'session.cookie.secure'` is true.

Fortunately there is fix described [here](https://github.com/simplesamlphp/simplesamlphp/issues/353).
Note : don't forget to change `SimpleSAML\Logger` to `SimpleSAML_Logger`.

**Comment by jornane** [comment]
Good catch! From the issue you referenced:
> the problem is that command line utilities shouldn't be using sessions at all

This is also true for FileSender. We must fix the session manager to detect it's running from Cron and refusing to make a session. This shouldn't be much work, as I think FileSender already detects this. Only thing that must be fixed then is that FileSender must not make calls to SimpleSAMLphp if it runs from CLI.
