### ISSUE TITLE
AUP acceptance check only done client-side, can be avoided trivially

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#440]
It's technically trivial (using the browser's developer tools) to remove the HTML elements that are responsible for the subject having to accept the AUPs before starting an upload, thereby circumventing the client-side JavaScript check completely, making the "send" button clickable without accepting anything.

Now, one might be able to phrase the AUPs differently so that _any_ use of this service constitutes acceptance of those terms on part of the subject (and modify the templates so that those AUPs are always shown, with no checkboxes needing to be ticked), but simply adding a _server-side_ check for AUP acceptance prior to accepting the upload would provide a technical solution that avoids any fingerpointing or discussions about whether a subject has in fact accepted those AUPs or not.

**Comment by monkeyiq** [comment]
Let me know if you can get around the merged 493. For me, when deleting the aup element server side this check will stop the upload.
