### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#443]
Would using the [Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) [API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) be an optional alternative to email notifications, for any "Notify me" config options?

I think it might, unless the common use case in fact is "Use an idle machine to start a huge upload and walk away (checking your email inbox from elsewhere for progress)".

**Comment by WebSpider** [comment]
This would certainly make sense for any notifications regarding the state of the up/download. 
I personally would love to just have an upload running in a tab, and filesender sending me notifications about the upload/download, mainly about start/finish or temporary issues disrupting progress

**Comment by monkeyiq** [comment]
It is nice to get more feedback on this. I encourage others to thumbs up feature requests that they would like to see appear.

**Comment by monkeyiq** [comment]
I think since the feature was merged a year ago I might close the issue now. Feel free to reopen it or make a new one if you have issues.
