### ISSUE TITLE
Scrollbar transfer auditlog not working

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#446]
When sending a file to a large number of recipients we noticed that you cannot scroll down in the transfer audit page to see all of them. The scroll bar is not working. It is present, but if you click on the arrows nothing happens. 
This was reported by a user and was tested it both in Google Chrome as well as in Internet Explorer.

**Comment by monkeyiq** [comment]
It seems to be using the page scrollbar. I see the auditlog window come up and it is larger than the page that was already there so scrolls off the bottom of the screen.  In ie11, chrome and firefox I can scroll but only using the page scroll or mouse wheel. Having a useless scrollbar in the auditlog is probably not a good idea though.

**Comment by monkeyiq** [comment]
I assume this is the "see the transfer logs" button on the my transfers page, which is what 473 was targeting.

**Comment by monkeyiq** [comment]
Hopefully the above scrollbar change has made things clearer than they used to be. I am leaving this at that stage pending a possible GUI refresh.
