### ISSUE TITLE
Database upgrade script (database.php) doesn't run nor does it do a rollback as it tells you

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#453]
We encountered problems when upgrading our (production) Filesender code from 2.0 to the latest 2.4 release. 
Many of these problems were due to the fact that the database migrate script didn't work as documented. 

The first time we ran the DB update script (database.php) we got the message:

```
    echo "Error, Rolling database changes back....\n";
    echo " This should leave the database state as it was before you started the script\n";
```

Unfortunately we discovered that this was not the case. The DB changes were not rolled back, leaving us misinformed and with a crooked DB.

We discovered this later, otherwise we would have restored the DB from the backup.

Things that we had to do to make the update script work:
```
* added CREATE VIEW rights
* DELETE FROM Guests WHERE LENGTH(user_id) > 170;
* DELETE FROM UserPreferences WHERE LENGTH(id) > 170;
```

**Comment by madsi1m** [comment]
Hi fransward,

What db server do you use? I am on an old mariadb and it has always worked.

Are you able to put in your changes as a pull request? Others might find it useful.

Cheers

**Comment by fransward** [comment]
`$ mysql -V
mysql  Ver 15.1 Distrib 10.2.19-MariaDB, for Linux (x86_64) using readline 5.1

$ php -v
PHP 5.4.16 (cli) (built: Apr 12 2018 19:02:01)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies`

On previous experiences we had to update MariaDB to make it work. See also #394 

Cheers

**Comment by monkeyiq** [comment]
The above two merges update the post commit message to soften what it says happens after a rollback.  Because the database.php script needs DROP (for views) and REFERENCES (for RI) the current git master (to be release 2.6 soon) allows you to set a special user/pass to use for the script. This is documented on the installation page.

**Comment by monkeyiq** [comment]
If people are upgrading from a version before 2.2 it is recommended to take a database backup before migration as there are some major changes to the database in version 2.2.

**Comment by monkeyiq** [comment]
I assume since this is a few years old that folks are post 2.2 now and the issue can be marked as closed.
