### ISSUE TITLE
Safari does not warn about bad password when downloading encrypted file

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#455]
On Firefox you get a bad password error early on when downloading. on Safari on osx (and not personally verified, on iphone) you do not get an indication of a bad password. This can be troubling if a small typo has caused a bad password for a large download.

**Comment by monkeyiq** [comment]
This may be a short term dead end. Using AES-CBC it appears to always give a result on safari 12 even with bad password (gives bad plaintext). Using AES-GCM it does detect the bad password, so this will be swept into the complete when a soon to be performed AES-GCM switch occurs.

**Comment by monkeyiq** [comment]
This may be helped when https://github.com/filesender/filesender/issues/713 is merged. Though there would likely still be some form of extra decrypt-ok check for CBC mode to see that the password was valid.

**Comment by zivel** [comment]
on Chrome on MacOS the whole file is downloaded before it tries to decrypt it and then says "wrong password". It would be nice to inform the user before the file is downloaded.

**Comment by monkeyiq** [comment]
Which setting are you running for crypto? In PBKDF2/AES-GCM mode it seems to pick up the incorrect password quickly on big sur 11.5.2/safari.
```
$config['encryption_key_version_new_files'] = 3;
```

**Comment by monkeyiq** [comment]
For AES-CBC I probably still need to add something special in there for ios/macos to be as user friendly as one would expect.

**Comment by monkeyiq** [comment]
From a local test it seems `$config['encryption_key_version_new_files'] = 1;` still produces this issue on big sur 11.5.2/safari. I have mentioned this major usability issue to the FileSender board.

**Comment by monkeyiq** [comment]
Hopefully people have migrated to using
```
$config['encryption_key_version_new_files'] = 3;
```

I do not think that a special work around for Safari for `key_version=1` is very likely at this stage.
