### ISSUE TITLE
MySQL error on Admin screen

### ISSUE THREAD

**Issue by jiscfoo** [filesender/filesender#464]
Using FileSender 2.5 Ubuntu 18 with MySQL 5.7, the Admin screen bails out with this in the logs:

```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contain
s nonaggregated column 'filesender.StatLogs.additional_attributes' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

https://stackoverflow.com/questions/36950857/sqlstate42000-syntax-error-or-access-violation-1055-expression-3-of-select suggests the fix is either to alter the Query or tell MySQL to allow the _old_ way of doing `GROUP BY`.

Setting `sql_mode=""` in`my.cnf` does fix this…

Full log attached.
[filesender.log](https://github.com/filesender/filesender/files/2807971/filesender.log)

**Comment by monkeyiq** [comment]
This should be fixed in 521 linked above. I tested on MySQL Ver 14.14 Distrib 5.7.19 on Ubuntu 16.04.3.
