### ISSUE TITLE
%2523 doesn't decode to '#' resulting in 'Unknown page' errors.

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#465]
After a successful download filesender sends the sender a mail message telling that the file has been downloaded and shows a link to the transferlogs:
i.e:
`https://filesender.surf.nl/simplesaml/module.php/core/as_login.php?AuthId=default-sp&ReturnTo=https%3A%2F%2Ffilesender.surf.nl%2F%3Fs%3Dtransfers%2523transfer_115xxx.`

In files_downloaded.mail.php:
`You can access your files and view detailed download statistics on the transfers page at <a href="{files.first().transfer.link}">{files.first().transfer.link}</a>.`

 The URL in the mail is encoded with a %2523 (='%23') which the browser decodes into %23:
`https://filesender.surf.nl/?s=transfers%23transfer_115xxx`

Resulting in an error: **Unknown page**

This url should be decoded using a '#' char in order to work:
`https://filesender.surf.nl/?s=transfers#transfer_115xxx`

**Comment by peter-** [comment]
FWIW, I've [proposed](https://sympa.uninett.no/lists/filesender.org/arc/filesender-dev/2018-10/msg00010.html) (and implemented, locally) for Filesender to use "clean URLs" in outgoing emails (and simlpy rewrite those on the way back in in httpd) which would avoid this issue (and comparable ones reported here as well) completely. The response on-list was `... (crickets) ...` as usual.

**Comment by monkeyiq** [comment]
@peter- I am interested in looking at your implementation. Hopefully the same rewrites can be supported in apache and nginx but if we have one working the other may follow in time.
