### ISSUE TITLE
My transfers/Actions icons and text alignment correction

### ISSUE THREAD

**Issue by 1katoda** [filesender/filesender#468]
Some possible UI corrections
Problem 1:
In the "My transfers" page, the "Files" column holding file names overlaps the "Downloads" column if there had been any downloads.
Solution 1:
Alter `line 150` of the `filesender/templates/transfers_table.php` and add a check if there were any transfers yet, shortening the filename string accordingly.
Before:
`if(strlen($name) > 25) $name = substr($name, 0, 22).'...';`
After:
```
if(strlen($name) > 25) {
  $name_shorten_by = strlen((string) count($transfer->downloads))+strlen(Lang::tr('see_all'));
  if(count($transfer->downloads)) $name = substr($name, 0, 25-$name_shorten_by).'...';
  else $name = substr($name, 0, 22).'...';
}
```

Problem 2:
In the "My transfers" page under the "Actions" column, the icons seem to be aligned in a weird way. They are displayed in 2 rows, the first one containing "Delete", "Add a recipient" and "Send reminder" icons and the second containing the "See the transfer logs" icon. Nothing major, just to make it prettier. So the two possible solutions:
- decrease margin in css to show all of them in the same row, or (the way I did it)
- encapsulate the icons in two <div style="margin:3px"> tags to separate them two by two in both `class="transfers list"` and `class="transfer_details"` tables

EDIT: I know the icons are displayed based on the $extend and $audit parameters, but I think it could be just a bit prettier if the clockwise and counter-clockwise arrows were in the same row.

**Comment by madsi1m** [comment]
Hi, you've done most of the work, any chance to change this into a pull request?

**Comment by 1katoda** [comment]
Hi, done and done. Thanks for the quick reply.
