### ISSUE TITLE
Possibly move FileSender docs to github pages

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#47]
I notice on https://app.assembla.com/spaces/file_sender/wiki/Installation_-_Linux_Source a comment about emailing the dev list with suggestions to update the install docs. Perhaps this would be easier if the documentation was moved from assembla to using github pages? Documentation suggestions could be done as normal PRs.

**Comment by jornane** [comment]
I'm waiting for someone to decide on this in #15.

**Comment by monkeyiq** [comment]
I have done some PRs recently to address this
