### ISSUE TITLE
Database creation and setup instructions potentially stale?

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#48]
Looking at https://app.assembla.com/wiki/show/file_sender/Installation_-_Linux_Source#step_7_-_create_the_filesender_user_and_database

There is a reference to filesender/scripts/filesender_db.sql which doesn't seem to exist (& in find).

I have noticed ./travis/scripts/postgresql-setup.sh which may do the same thing but that seems to get somewhat confused tripping over itself creating a table twice when I try to cajole an environment to execute it as the postgres user.

The other thought is that filesender automatically creates the db setup when executed with an empty db.

**Comment by jornane** [comment]
Those are the instructions for FileSender 1.6. Please refer to http://docs.filesender.org/v2.0/install/ instead.
