### ISSUE TITLE
language selection: the language selector in the menu and my profile are different

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#483]
if you set lang_selector_enabled = true in the config.php to enable the language selector in the menu bar that language selection is very temporary (in the URL) whereas the language selection done on the my profile page is a preference that is stored in the database. 

Maybe we should make those have the same lifetime or warn the user that they are different.

**Comment by WebSpider** [comment]
Is this still relevant ?

**Comment by monkeyiq** [comment]
It seems it is set in the URL and that also has an effect on SESSION now.
