### ISSUE TITLE
Email subject empty when no email subject is provided during file uploads

### ISSUE THREAD

**Issue by spgreen** [filesender/filesender#515]
Using FileSender v2.5.
There seems to be an issue with generated emails, specifically the Email Subject if no subject is set during file upload.

Observations:
- If I enter a subject entry into the 'Subject (optional)' box, I receive an email with the email prefix  and said subject concatenated together which is to be expected, e.g. 'FileSender: <Inputted Subject>'
- If I leave the 'Subject (optional)' empty, I only receive the email prefix. Expecting subject to be to something like the following 'FileSender: File(s) available for download' according to the  [language/en_AU/transfer_available.mail.php](https://github.com/filesender/filesender/blob/master/language/en_AU/transfer_available.mail.php) file 

The default [language/en_AU/transfer_available.mail.php](https://github.com/filesender/filesender/blob/master/language/en_AU/transfer_available.mail.php) file has the two following subject lines:
1. `subject: File{if:transfer.files>1}s{endif} available for download`
1. `subject: {transfer.subject}`

It seems that it is defaulting to the last subject line even when no subject is given. Is this expected behaviour? If not, is there a way to resolve this issue so it is able to pick the appropriate subject line during email generation?

**Comment by monkeyiq** [comment]
It seems to be doing something different to what the docs (https://docs.filesender.org/v2.0/i18n/) are saying. According to the docs the 2 subject line should become blank if there is no subject and thus will be filtered out and the 1. line should be used for those emails.

I am digging into why this is happening now.

**Comment by monkeyiq** [comment]
Thanks for reporting this. It should be fixed with the above PR.
