### ISSUE TITLE
Autocomplete of email address should not be case sensitive

### ISSUE THREAD

**Issue by baumrasen** [filesender/filesender#531]
(with autocomplete function for email addresses in To: field enabled)

You have to type in upper case, if the address is stored with upper case to get the email address autocompleted.
Because of email adresses are working with upper and lower case the system should ignore upper and lower case.

**Comment by monkeyiq** [comment]
Thank you for reporting this. Sorry about the delay. It should be addressed with the merge of https://github.com/filesender/filesender/pull/770
