### ISSUE TITLE
404 for translate_email_page.js

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#537]
There is a reference for a **translate_email_page.php** in **templates/translate_email_page.php**,
but this file doesn't exists and therefore produces a 404.

Offending line:
`<script type="text/javascript" src="{path:js/translate_email_page.js}"></script>`

**Comment by fransward** [comment]
btw, we're using the latest codebase 2.6

**Comment by monkeyiq** [comment]
It seems many of the templates look for their name in path:js/name.js. I don't see a file js/translate_email_page.js here either. I am tempted to add a blank file rather than remove the reference.
