### ISSUE TITLE
Feature privacy request: Access to statistics tab *only*

### ISSUE THREAD

**Issue by adminnr1** [filesender/filesender#550]
Possibility to access the Statistics tab as an admin type roll, *without* access to the Transfers, Guests and Users tabs.
This feature because FileSender is our GDPR friendly service. We want to see the statistics, but **do not** want to see the personal information and do not want to have the possibility to download the files of our users.

**Comment by monkeyiq** [comment]
This has been implemented with the can_view_statistics configuration setting which was included in the FileSender 2.8 release. 

Perhaps we might like to offer an alternate of the browser stats table that is more aggregated?
