### ISSUE TITLE
cron.php error no_such_property

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#557]
When running the cron.php we see the following error:
`php /opt/filesender/filesender/scripts/task/cron.php`

Error:

> PHP Fatal error:  Uncaught PropertyAccessException: no_such_property in /usr/share/filesender/filesender-2.61/classes/data/StatLog.class.php:365
> Stack trace:
> #0 /usr/share/filesender/filesender-2.61/classes/data/DBObject.class.php(558): StatLog->__get('browser')
> #1 /usr/share/filesender/filesender-2.61/classes/data/StatLog.class.php(166): DBObject->toDBData()
> #2 /usr/share/filesender/filesender-2.61/classes/data/StatLog.class.php(299): StatLog->save()
> #3 /usr/share/filesender/filesender-2.61/scripts/task/cron.php(52): StatLog::createGlobal('global_storage_...', 92362768384)
> #4 {main}
>   thrown in /usr/share/filesender/filesender-2.61/classes/data/StatLog.class.php on line 365

Have you seen this before?

**Comment by keros** [comment]
Same here (#88)

**Comment by peter-** [comment]
Yes, Frans (and keros) this also affects us exactly the same way on a fresh install of branch `filesender-2.7`, using PostgreSQL.

If the cron job is what expires files (and sends email notifications about this) I guess this is a total show stopper that prevents any real use of the software.  
(At least I'm not looking forward to sending out hundreds of such notifications after an eventual fix is deployed, months after people have uploaded something in the expectation -- in fact promise, as per the `/?s=privacy` page -- that it would expire a few days later. Not to mention that disk capacities are not unlimited and without expiration soon any disk would be filled, making this an operational issue, too.

**Comment by kadafax** [comment]
Same problem here, it seems :
https://github.com/filesender/filesender/commit/d5981869cc789692428f86d2a9002b15120477ba
and
https://github.com/filesender/filesender/pull/586/commits/5ea92c552420cc19bfd8961db40be66cfe9cb227

fixed the problem

**Comment by yent** [comment]
> Same problem here, it seems :
> [d598186](https://github.com/filesender/filesender/commit/d5981869cc789692428f86d2a9002b15120477ba)
> and
> [5ea92c5](https://github.com/filesender/filesender/commit/5ea92c552420cc19bfd8961db40be66cfe9cb227)
> 
> fixed the problem

Same here using mysql

**Comment by peter-** [comment]
Running tag `filesender-2.8` this now works for me, thanks @belnet-ming and @monkeyiq!

While I think this issue can now be closed I did add the below to `classes/data/constants/DBConstantBrowserType.class.php` (and similarly to `/opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php`):

```diff
@@ -83,6 +83,9 @@ class DBConstantBrowserType extends DBConstant                                             

     static function currentBrowserToEnum()
     {
+        if(!defined($_SERVER['HTTP_USER_AGENT'])) {
+            return self::lookup(self::T_UNKNOWN);
+       }
         $b = $_SERVER['HTTP_USER_AGENT'];
```

in order to avoid the `PHP Notice` message on STDOUT (possibly leading to emails from cron on every run) about `Undefined index: HTTP_USER_AGENT` as that'll always be undefined for cron jobs:

```
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
```

**Comment by peter-** [comment]
Seems this issue (including the tangent about unsed HTTP_USER_AGENT) has long been fixed and can be closed.
