### ISSUE TITLE
Option to download multiple encrypted files

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#560]
This would be very handy to have. If we wish to have a single zip file containing many files that were encrypted then we will have to download the files individually and create the zip file in the browser as all decryption is in the browser. On the upside this would avoid more than one file selection dialog from opening and be a clean user experience.

Another short term option would be the ability to select more than one file to download and enter the decryption key only once and allow the browser to download and decrypt your selected files, saving each individually.

**Comment by madsi1m** [comment]
Sounds like you need a terareciever.

**Comment by WebSpider** [comment]
Could [FSFW](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemWritableFileStream) be used for this case?

**Comment by monkeyiq** [comment]
I am not sure this will be done soon. Downloading multiple encrypted files into a zip files is already implemented.
