### ISSUE TITLE
Incomplete English text in language file (partly embedded in code)

### ISSUE THREAD

**Issue by adminnr1** [filesender/filesender#562]
The welcome text of Filesender is partly in a language file and partly embedded in the code. It should all be in a language file so translations in POeditor can be made. 

Proposition: move text from code to language file. Full welcome text:

<h1>Welcome to {cfg:site_name}</h1>

<p>
 {cfg:site_name} is a secure way to share large files with anyone !
</p>

<p>
  Login to upload your files or invite people to send you a file.
</p>

<p>
  If you have received an invitation to access this site as a guest
  then the email will contain the information you will need to access
  this site and upload files.
</p>

Last part is embedded in code (from If you (...) to (...) files.

Also, delete the space between 'anyone' and '!' in the first line.

**Comment by monkeyiq** [comment]
The above text is from en_AU/site_splash.html.php. That text is taken from the value of 
site_splash from poeditor. So the above text can be updated completely from poeditor. 

It is a little confusing that the translations are taken from poeditor and distributed in the language subdirectory of the FileSender distribution.

**Comment by monkeyiq** [comment]
Please reopen this issue and https://github.com/filesender/filesender/issues/565 https://github.com/filesender/filesender/issues/564 if they are not already addressed.
