### ISSUE TITLE
Expired transfers are not moved to Closed transfer overview

### ISSUE THREAD

**Issue by adminnr1** [filesender/filesender#563]
Expired transfers should be shown in the Expired transfer overview in the My Transfers tab.

Expired transfers are shown in the Currently available transfer. This provides the ability to send a reminder or add a recipient. However, the file is already removed and not available(which is good).

Solution: Move expired transfers tot the Expired transfer overview

**Comment by madsi1m** [comment]
We have also seen this issue on our deployment

**Comment by adminnr1** [comment]
Because expired Transfers are still shown in the 'Currently available transfers' overview, users can extend the expiry date and send a reminder, which creates a download link that will work.
This is not how it should work. When a Transfer is past the expiry date, it should be moved to Closed transers overview and the file should be deleted.
Please fix.
﻿﻿

**Comment by monkeyiq** [comment]
IIRC I did some updates relating to this but seem to have not linked to this report. A recent retest shows transfers moved to "closed" here.

**Comment by monkeyiq** [comment]
Clicking on the download link for a closed transfer shows that the file has been removed. If this is still happening on a recent FileSender for anyone please feel free to reopen. Otherwise, sorry for not linking when I did the update as that would have made for much better feedback.
