### ISSUE TITLE
Incomplete English text in language file About (partly embedded in code) (part3)

### ISSUE THREAD

**Issue by adminnr1** [filesender/filesender#565]
The text in the About file is partly embedded in the code and partly in a language file.
All text should be in the language file so an easy translation can be made via POeditor.

**Comment by monkeyiq** [comment]
The value in the php file should be taken from about_text on poeditor during a language import from poeditor to the FileSender code base.

**Comment by monkeyiq** [comment]
see https://github.com/filesender/filesender/issues/562
