### ISSUE TITLE
Feature: possibly allow authentication using apache

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#567]
Smaller installations might not be interested in setting up simplesamlphp or other auth modules. On the other hand many admins are familiar with the apache auth setup and might like to use that instead of custom user/pass setups on simplesaml. 

This would help support filesender installations on smaller scales but still allow users to invite guests to upload single files to them etc.

**Comment by WebSpider** [comment]
Hasn't this been addressed by introducing local users in recent filesender releases?

**Comment by monkeyiq** [comment]
The local users allows the auth information to be stored in the database. 
The above would use apache itself to auth users. 

But having something alrady available is useful for deployment to smaller (20-100) sized installations :)
