### ISSUE TITLE
Ability to send files from a local file system

### ISSUE THREAD

**Issue by clmcavaney** [filesender/filesender#575]
It would be handy to send files from a local file system, particularly if they are large.
Would it be possible for a filesender user to map to a local user that has permissions to a local file system they could then browse and effectively setup a pointer for filesender to do its magic and share the file to its recipients. (sorry about the long sentence).

**Comment by WebSpider** [comment]
Is it correct that this assumes local access to a filesender server?

**Comment by madsi1m** [comment]
> It would be handy to send files from a local file system, particularly if they are large.
> Would it be possible for a filesender user to map to a local user that has permissions to a local file system they could then browse and effectively setup a pointer for filesender to do its magic and share the file to its recipients. (sorry about the long sentence).

Hi Christopher,

Just an idea, It might be better to use CloudStor's ownCloud for this rather than filesender. Going via owncloud sync client. Copy the files you want, wait for it to sync, then share it.

Cheers
Michael

**Comment by WebSpider** [comment]
@clmcavaney has this issue been resolved?

**Comment by clmcavaney** [comment]
I'm not sure.
I didn't follow up on it at the time. As it would be quite a change/extension to the architecture of FileSender
