### ISSUE TITLE
show number of users in global stats in admin page

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#582]
show number of users in global stats in admin page

**Comment by monkeyiq** [comment]
I have put in the estimated number of users from the database to try to not hit the database too much. It seems like the number of active users per week or day would be a nice statistic, but maybe better presented on a page of it's own.

**Comment by monkeyiq** [comment]
... also my above suggestion is more info from the aggregatestats part of the system.

**Comment by monkeyiq** [comment]
Maybe tracking other stats we would like up is best done in another discussion / gh issue.
