### ISSUE TITLE
The poeditor link in CONTRIBUTE.md page leads to a 404 error

### ISSUE THREAD

**Issue by belnet-ming** [filesender/filesender#585]
link: https://poeditor.com/projects/view?id=48000
![image](https://user-images.githubusercontent.com/49909162/60257283-76ca4680-98d3-11e9-910f-4bb274868d6f.png)

**Comment by monkeyiq** [comment]
This now either takes me to the project (if I have logged in for poeditor on that browser) or to a poeditor login screen. So the 404 is gone it seems.

**Comment by belnet-ming** [comment]
I still got the 404 error (logged in or not)...
Should we change the link to https://poeditor.com/join/project/RqXr9WBJwU (which works fine) from https://docs.filesender.org/v2.0/i18n/ ?

**Comment by monkeyiq** [comment]
Sounds good. I have 608 above set to do that and will merge once CI finishes.
