### ISSUE TITLE
Add a recipient to existing transfer with aup_enabled = true will fail with a bad REST parameter

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#596]
One of the actions on your 'My Transfers' screen is to add a recipient to one of your currently available transfers.

This will throw a Bad REST parameter error:

> Bad REST parameter
> {method}: post
> {endpoint}: transfer

When you have the config setting:
`$config['aup_enabled'] = true;`

Which will me the only valid setting for this parameter when you look at the GDPR.

I've tested with the $config['aup_enabled'] = false; in place and that will succeed.

FWIIW: The debug info on the error gives:

> 
> [2019-07-19 10:47:07] [user 15] [rest:warn] nefarious activity suspected: A user with id 15 has sent a request without AUP data checked and is likely doing something bad.
> [2019-07-19 10:47:07] [user 15] [rest:error] [RestBadParameterException exception uid:5d31919b25054] rest_bad_parameter
> [2019-07-19 10:47:07] [user 15] [rest:error] [RestBadParameterException trace uid:5d31919b25054] #0 /usr/share/filesender/filesender-2.61/classes/rest/RestServer.class.php(303): RestEndpointTransfer->post('207', 'recipient')
> [2019-07-19 10:47:07] [user 15] [rest:error] [RestBadParameterException trace uid:5d31919b25054] #1 /usr/share/filesender/filesender-2.61/www/rest.php(37): RestServer::process()
> [2019-07-19 10:47:07] [user 15] [rest:error] [RestBadParameterException trace uid:5d31919b25054] #2 {main}
> [2019-07-19 10:47:07] [user 15] [rest:error] [RestBadParameterException details uid:5d31919b25054] method = "post"
> [2019-07-19 10:47:07] [user 15] [rest:error] [RestBadParameterException details uid:5d31919b25054] endpoint = "transfer"
> [2019-07-19 10:47:07] [user 15] [rest:error] [RestBadParameterException details uid:5d31919b25054] parameter = "aup_checked"

I would place the 'BUG label' to this one

**Comment by monkeyiq** [comment]
Thank you for the detailed report. I have merged 607 above which should resolve this issue, I tested before creating 607 (and got your above output) and with the update I could add new recipients. 

Please reopen the issue if 607 doesn't fully resolve the problem for you too.

**Comment by fransward** [comment]
Thanks! Just tested it on our beta server and it works like a charm. A messag popup 'Recipient added'is shown and the new recipient receives an email with the download link.
