### ISSUE TITLE
Feature: warning/reminder email on transfer near expiration but not downloaded yet

### ISSUE THREAD

**Issue by belnet-ming** [filesender/filesender#620]
This is a feature request from some of our users:

Recipients to receive a warning/reminder email (option: x day/hour) before expiration (option: if not downloaded yet).
We have users complaining that they forgot to download the files and only remembered when they received the expiration email but it is already too late as the files are already deleted.

**Comment by WebSpider** [comment]
I have seen a support ticket about this as well in our userbase.

**Comment by WebSpider** [comment]
This has since been implemented

**Comment by meijer** [comment]
This is activated by the transfer_automatic_reminder configuration directive, correct? https://docs.filesender.org/filesender/v2.0/admin/configuration/#transfer_automatic_reminder

I heard about 80% of FileSender support calls in the Norwegian R&E install are from recipients whose transfers expired.

**Comment by WebSpider** [comment]
Correct!
