### ISSUE TITLE
reports_show_ip_addr = false still shows IP adresses in transfer logs (bug)

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#621]
The transfer Audit Logs under the 'My Transfers'tab still show the IP-address of the recipients when the configuration directive:

`$config['reports_show_ip_addr'] = false;`

is set.

The documentation is clear:
> reports_show_ip_addr
> 
>     description: Show the IP addresses used in reports
>     mandatory: no
>     type: boolean
>     default: true
>     available: since version 2.0
>     comment: If you want to hide IP addresses from reports set it to false
>

**Comment by monkeyiq** [comment]
This should be fixed in https://github.com/filesender/filesender/pull/635 which I'll merge once CI stabilizes.

**Comment by fransward** [comment]
Thanks. Works for us!

**Comment by peter-** [comment]
Seems #635 was merged into master months ago and is included since `tag:filesender-2.9`. Can this issue be closed, then?

**Comment by fransward** [comment]
We are happy with the fix, so yes!

**Comment by monkeyiq** [comment]
I think I'll move to closing an issue when I merge a fix, especially if I can test before/after behavior. This will leave open the possibility to reopen if the issue if the fix doesn't work for everyone.
