### ISSUE TITLE
Edge console.log doesnt work

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#627]
hard to debug in Edge when console.log doesnt work.

https://www.beyondjava.net/console-log-surprises-with-internet-explorer-11-and-edge

**Comment by monkeyiq** [comment]
Perhaps using a window.filesender.log() which forwards to console.log() is a reasonable solution. It would allow devs to run in a mode that made the collected logs available by a button on the web interface and still allow the "send client logs" feature to work for users of the system on Edge.

**Comment by monkeyiq** [comment]
This may possibly be also causing issues in client logs not showing up (see https://github.com/filesender/filesender/issues/700).

**Comment by monkeyiq** [comment]
It is a good idea to follow up on this with some checking for use of console.log creeping back into the codebase. Such a thing is very likely and would mean those log lines would not be captured on Edge.

**Comment by monkeyiq** [comment]
As the core issue had a fix merged back in may I am closing this issue. Updates to detect console.log calls again should be a future update.
