### ISSUE TITLE
Transfer audit: filename "undefined"

### ISSUE THREAD

**Issue by belnet-ming** [filesender/filesender#642]
In Transfer audit:
The filename is "undefined".
![image](https://user-images.githubusercontent.com/49909162/65033420-3d8afb00-d945-11e9-9d4b-d254005b6a25.png)

```
$lang['report_recipient_event_download_started'] = 'Recipient started downloading {file.path} ({size:file.size})';
```

lang.js is trying to replace {file.path} for the filename, but {file.path} doesn't exist.

In transfer_table.js:
```
var rpl = log[i];
rpl[log[i].target.type.toLowerCase()] = log[i].target;
                
$('<td />').html(lang.tr(lid).r(rpl).out()).appendTo(tr);
```
![image](https://user-images.githubusercontent.com/49909162/65033733-f2251c80-d945-11e9-88a1-1c940635feb6.png)

target.name has been "renamed" to file.name.

Resolution: All **{file.path}** should be changed to **{file.name}** in lang.php and POEditor.

**Comment by peter-** [comment]
Note that while the web UI shows `undefined` for the file name (line 3 below):
![2019-09-17-201648_529x241_scrot](https://user-images.githubusercontent.com/4047365/65068321-be1f1b00-d988-11e9-9062-a4914bd1ce21.png)
if I chose `Send to my email` the file name is correctly included in the email text (both plain and html)

```
Date                      Action that happened
2019-09-17 20:08:03 CEST  Transfer was created
2019-09-17 20:08:03 CEST  Upload started
2019-09-17 20:08:03 CEST  File fs-css-3.mp4 (61.2 kB) uploaded (took 0s)
2019-09-17 20:08:04 CEST  Upload ended
2019-09-17 20:08:04 CEST  Transfer became available (took 1s)
```
So it seems to me email sending and displaying of reports uses slightly different code paths which would suggest a different resolution than the one mentioned above.

**Comment by belnet-ming** [comment]
I've tested my resolution, seems to work on the web UI and the email.
The email uses **{raw:content.plain}** and **{raw:content.html}** for the table, which explains the differences.

![image](https://user-images.githubusercontent.com/49909162/65134038-f7e13780-da03-11e9-8492-818b53b8e872.png)

![image](https://user-images.githubusercontent.com/49909162/65133894-ba7caa00-da03-11e9-9f10-67734bf0f1a1.png)

```
16/09/2019 10:31:55	Transfer was created	
16/09/2019 10:31:55	Upload started	
16/09/2019 10:31:55	File AD_FS_-_SimpleSAMLphp.pdf (443.6 kB) uploaded (took 0s)	
16/09/2019 10:31:56	Upload ended	
16/09/2019 10:31:56	Transfer became available (took 2s)	
17/09/2019 09:36:48	Recipient 1 started downloading AD_FS_-_SimpleSAMLphp.pdf (443.6 kB)	
17/09/2019 09:36:48	Recipient 1 finished downloading AD_FS_-_SimpleSAMLphp.pdf (443.6 kB)	
17/09/2019 13:33:25	Recipient 1 started downloading AD_FS_-_SimpleSAMLphp.pdf (443.6 kB)	
17/09/2019 13:33:25	Recipient 1 finished downloading AD_FS_-_SimpleSAMLphp.pdf (443.6 kB)

```

Another "bug" I've found when trying to trigger the "**target.type == "File**" condition; to test the "This file is named **{file.path},**", but I think this should also be changed in other *.mail.php files.

```
From: filesender/language/en_AU/report_inline.mail.php

    {if:target.type == "Transfer"}
    This transfer has {transfer.files} files with an overall size of {size:transfer.size}.<br /><br />
    
    This transfer is/was available until {date:transfer.expires}.<br /><br />
    
    This transfer was sent to {transfer.recipients} recipients.
    {endif}
    {if:target.type == "File"}
    This file is named {file.path}, has a size of {size:file.size} and is/was available until {date:file.transfer.expires}.
    {endif}
    {if:target.type == "Recipient"}
    This recipient has email address {recipient.email} and is/was valid until {date:recipient.expires}.
    {endif}
```

When you click on "**See what happened to this file**":
![image](https://user-images.githubusercontent.com/49909162/65137279-565ce480-da09-11e9-9070-bac632c5c9a2.png)

It opens 2 "pop-ups", one for the file, the other for the transfer:
![image](https://user-images.githubusercontent.com/49909162/65137473-b18ed700-da09-11e9-921a-a0edba0e3438.png)
I've moved the one up to show the bottom one:
![image](https://user-images.githubusercontent.com/49909162/65137494-bce20280-da09-11e9-8ebc-2691cc661655.png)

And when you click on the "Send to my email" button, it sends the report for the transfer, not for the file.

**Comment by peter-** [comment]
Any updates on this? @belnet-ming: Maybe creating a PR with the proposed fix to the main issue reported here (filename `undefined`) would help in moving this along? Then maybe rename the issue to reflect the other problem which AFAICT deals with the wrong report being sent (in order to avoid having to re-upload all the screenshots)?

**Comment by monkeyiq** [comment]
I have created PR https://github.com/filesender/filesender/pull/724 to allow the full path (if it exists) or the file name to be shown in the my transfers / "see the transfer logs" dialog. This "path" is already setup in File::loadDirectoryPath() for code to use and is now exported through to the GUI with the changes in https://github.com/filesender/filesender/pull/724 and https://github.com/filesender/filesender/pull/723 as a fallback.

**Comment by monkeyiq** [comment]
Please let me know if these updates still leave some dialogs or emails not showing expected data.

**Comment by belnet-ming** [comment]
The filename is correctly shown in the UI:

![image](https://user-images.githubusercontent.com/49909162/73258487-1501f000-41c6-11ea-826d-b516d94c4aa2.png)


And the email is still correct:
![image](https://user-images.githubusercontent.com/49909162/73258656-79bd4a80-41c6-11ea-864e-79cca9d70ddf.png)

**Comment by belnet-ming** [comment]
Closing Issue.
