### ISSUE TITLE
Drag and drop not working on Edge

### ISSUE THREAD

**Issue by Veredior** [filesender/filesender#661]
Hello,
the drag and drop does not work on Microsoft Edge 44.18362.387.0 on Windows 10 1903.
When our users try to drop a file the cursor is changing into a black forbidden cursor.

After looking on internet it seems Microsoft has disabled this feature ?! Is it a known issue ?

**Comment by monkeyiq** [comment]
IIRC initially drag and drop was only working on Chrome. I have used it on Firefox for a while. 

I just tested Edge on Windows 10 using FileSender git master and it allowed a drop to the upload page. I don't recall anything changing recently in FileSender specific to Edge and I seem to have very similar platform software versions. I was dragging a file from the windows explorer to Edge on the upload page.

Windows 10 1903 (Build 18362.418)
Microsoft Edge 44.18362.387.0
Microsoft EdgeHTML 18.18362

Does this work or fail for anyone else?

**Comment by monkeyiq** [comment]
Does anyone else have experience with Edge and D&D. 
Specifically, working or not and which filesender and Edge versions.

**Comment by belnet-ming** [comment]
D&D working with:
FileSender: development branch (67a4acabcd1623144644b299fe63c4b02bf16d53)
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

**Comment by monkeyiq** [comment]
please reopen or report again if this issue is still happening. It may be hard to find as the exact Edge and EdgeHTML versions might not be available on development machines to test against.
