### ISSUE TITLE
A StorageFilesystemFileNotFoundException throws an Incorrect Password message

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#668]
By accident I noticed that a StorageFilesystemFileNotFoundException will produce an **Incorrect Password** message when a user tries to download an encrypted file. Should be a **File not found** message imho.

A snipped of the logs of one of our development servers:

> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException exception uid:5dba103228da3] storage_filesystem_file_not_found
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException trace uid:5dba103228da3] #0 /usr/share/filesender/filesender-2.10-develop/classes/storage/Storage.class.php(175): StorageFilesystem::readChunk(Object(File), 0, 81153)
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException trace uid:5dba103228da3] #1 /usr/share/filesender/filesender-2.10-develop/classes/data/File.class.php(474): Storage::readChunk(Object(File), 0, 81153)
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException trace uid:5dba103228da3] #2 /usr/share/filesender/filesender-2.10-develop/www/download.php(272): File->readChunk(0, 81153)
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException trace uid:5dba103228da3] #3 /usr/share/filesender/filesender-2.10-develop/www/download.php(373): {closure}()
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException trace uid:5dba103228da3] #4 /usr/share/filesender/filesender-2.10-develop/www/download.php(122): downloadSingleFile(Object(Transfer), Object(Recipient), '377', true)
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException trace uid:5dba103228da3] #5 {main}
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException details uid:5dba103228da3] path = "/usr/share/filesender/filesender/files/dc9427f6-0951-4927-ac1d-79ce9fe33d34"
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException details uid:5dba103228da3] file = "File#377(metrokaartboedapest.jpg, 81127 bytes)"
> [2019-10-30 23:35:30] [user 15] [web:error] [StorageFilesystemFileNotFoundException details uid:5dba103228da3] transfer = "Transfer#301"

**Comment by monkeyiq** [comment]
This should be fixed in 2.11

**Comment by monkeyiq** [comment]
PR https://github.com/filesender/filesender/pull/669 should handle this and open the door for reporting other server side issues as something other than the generic "bad password" error.
