### ISSUE TITLE
Guest vouchers that don't expire can still have a date set

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#673]
if you prepare a voucher, and make it “non-expiring”, you can still set an expiry date, and sure enough on that date you get an email saying the voucher has expired (but it hasn’t!)

So, maybe disable the setting of an expiry date for non expiring invitations, nip the problem in the bud right at the invitation. And also check that non expiring during email outs to make sure no you are about to expires are emailed when they shouldn't be.

**Comment by madsi1m** [comment]
Yes please.
An idea: maybe move the tickbox closer to the actual calendar and have it grey out or disable when ticked?

**Comment by monkeyiq** [comment]
digging into this a bit I'm trying to make sure that email doesn't happen now for when expires = null for non expiring guests. I'm wondering if the guest expires email is sent to the guest, the person who created the guest, or both.

**Comment by monkeyiq** [comment]
The current code is at https://github.com/filesender/filesender/pull/683 though I would be happier if I could see in cron.php where it might have been sending the email about expiring.

**Comment by monkeyiq** [comment]
if this bug is still happening for anybody please let me know

**Comment by WebSpider** [comment]
This was planned to be tested by us in the next release, however this has been postponed for now, for obvious global reasons.

**Comment by WebSpider** [comment]
We have not longer encountered this
