### ISSUE TITLE
i18n: Slovenian language and accepting guest vouchers.

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#674]
if you add the Slovenian language, and then click on a voucher you’ve just been issued, you end up with a blank page (this is firefox/win10).

**Comment by Phaze-III** [comment]
This might be a local cloudstor issue and is not restricted to vouchers. It breaks when calling rest.php/lang?callback=lang.setTranslations  with 'sl' in the Accept-Language: request header i.e.: Accept-Language: en-US,en;q=0.7,sl;q=0.3

On cloudstor production this gives a 500 error, on cloudstor-uat the following is shown:
Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR) in /cloudstor/www/filesender/language/sl_SI/lang.php on line 371

**Comment by Phaze-III** [comment]
A similar problem exists with the es_ES lang.php. cloudstor-uat gives:
Parse error: syntax error, unexpected 'is' (T_STRING) in /cloudstor/www/filesender/language/es_ES/lang.php on line 355

Looks like the es and sl files have a few definitions overly escaping a single quote:
```
es_ES/lang.php:$lang['rest_method_not_implemented'] = 'REST meetod ei ole antud endpoint\\'is realiseeritud';
es_ES/lang.php:$lang['serverlog_config_directive'] = 'On seotud konfiguratsiooni direktiiviga \\'{key}\\'';
es_ES/lang.php:$lang['serverlog_wanted_key_in_array'] = 'Attribuut koos võtmega \\'{key}\\' on nõutud';
es_ES/lang.php:$lang['terasender_worker_count'] = 'TeraSender\\'i protsesside arv';
sl_SI/lang.php:$lang['serverlog_config_directive'] = 'Povezana konfiguracijska direktiva \\\\'{key}\\\\'';
sl_SI/lang.php:$lang['serverlog_wanted_key_in_array'] = 'Zahteval se je atribut s ključem \\\\'{key}\\\\'';
```

**Comment by Phaze-III** [comment]
And wondering why the spanish definitions didn't really look like spanish, #675  created.
