### ISSUE TITLE
API access broken when aup_enabled

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#679]
## Problem statement

When trying to access the API using [filesender.py](../tree/master/scripts/client/filesender.py) on a system that uses AUPs...
```php
$config['aup_enabled'] = true;

$config['auth_remote_user_enabled'] = true;
$config['auth_remote_user_autogenerate_secret'] = true;
```
this always fails due to [missing `aup_checked`](https://github.com/filesender/filesender/blob/6d345b457d0c4c3f9cecf3e2f7a2793e38845a42/classes/rest/endpoints/RestEndpointTransfer.class.php#L370-L374) with this message on the client's command line:

```
Exception: Http error 400 {"message":"rest_bad_parameter","uid":"5dc437641651b","details":{"method":"post","endpoint":"transfer"}
```
and the server logging this (giving the only hint as to the reason):
```
[RestBadParameterException details uid:5dc437641651b] parameter = "aup_checked"
```

Since we are running our FileSender instance with `aup_enabled=true` this currently prevents us from offerning API access to our communities.

There are several aspects to this alluded to below and multiple issues may be spun off from this one to track those, if desired.

## Approaches

While it should be easily possible to amend `filesender.py` (and the other client implementations released by the project) to supply the necessary API message signalling that AUPs have been accepted [recent discussions on filesender-dev](https://sympa.uninett.no/lists/filesender.org/arc/filesender-dev/2019-11/msg00007.html) (the whole thread may be worth reading) suggest that maybe the server should not even trust proper API messages that claim that the AUPs where in fact accepted (due to the theoretical possibility of  the existence of "evil clients" unconditionally claiming that, w/o any user interaction) and instead should make issuing of API keys themselfs conditional to the subject prior having accepted the AUPs in the web UI.

If OTOH hypothetical "evil API clients" are not a major concern for the project at this time admending any clients distributed by the project with a flag to signal acceptance of "the current AUPs" via the API is the simplest and most direct fix to this issue.

Personally I think issuing API keys from the  web UI (after AUP acceptance ibid.) aligns well with my suggestion in #579 that it should be possible to create (and re-generate) API keys from the web UI, instead of auto-creating them via the `auth_remote_user_autogenerate_secret` setting or somehow provisioning those yourself somehow): This would make the process of uploading files from the UI completely analogous to generating API keys: the UI plus the server-side check from #440 would enforce that AUPs have been accepted (if necessary) before the subject is able to hit `[Send]` or `[Generate API key]` buttons on the upload or user page respectively, with no requirement to store the acceptance of the AUPs in the DB. (For which btw there _are_ existing columns in the table `userpreferences` -- though they seem to be unused: In my test deployment those are all empty/false/1970-01-01 and I didn't find code that would set `aup_last_ticked_date` at all, for example).

## Related aspects and tangents

There was a slight tangent about whether to support separate AUPs for web and API usage but that was based on speculation about potential use-cases (and designing for those right away), not on concrete, existing requirements from a deployer.

There's also another tangent about potentially supporting use-cases where amended AUPs required their re-acceptance and how that would work with already issued API keys -- with the desire to spare users to re-generate and re-deploy a new API key, but instead allow them to simply re-enable the existing API key (so that no external systems would have to be touched and no keys replaced). Doing that would require facilities to temporarily -- though possibly effective permanently, if not acted on by the subject -- suspend/invalidate existing, previously created and deployed-by-the-subject API keys until the AUPs have been accepted again. So some kind of expiration date (default NULL) or validity column/property for an API key would probably be needed to support that use-case.  

Yet another tangent is to maybe make the AUPs a config parameter (e.g. an associative array keyed by language codes, to support translation of the terms) so that they could be easily both addressed via a URL and also embedded into upload and user pages as needed. When not implementing AUP acceptance in the API client the need for the API client to easily reference the AUPs via a static URL -- like the upload,user,policy pages there could be an AUP page in their own right -- might not exist, though.

I'm putting these all in a separate section here since AFAICT those are additional/other use-cases that go beyond simply fixing the problem of using FileSender over the API with AUPs enabled.

**Comment by monkeyiq** [comment]
I have merged support for creating and deleting the api secret through the web interface at https://github.com/filesender/filesender/pull/718

718 also adds the option to show a dialog with a link to a full aup when the user clicks to create an api key. This is enabled by setting the new config `api_secret_aup_enabled=true`. If that is left at the default `false` value then the user can create a new api secret but does not get presented with a confirmation dialog when doing so.

**Comment by monkeyiq** [comment]
I think I will mark this issue as closed as the AUP for API client functionality and the ability to create and delete the api secret are aimed at the base issue. 

A good follow up issue and discussion to continue along these lines would be to allow versioning of the AUP.
