### ISSUE TITLE
WebUI: Admin -> Users: Show client logs broken

### ISSUE THREAD

**Issue by belnet-ming** [filesender/filesender#700]
Only displaying "No result" for every user.
Also a problem with the display of the table.
![image](https://user-images.githubusercontent.com/49909162/69611416-019fa080-102e-11ea-8200-24567b032cd2.png)

**Comment by monkeyiq** [comment]
Could you please try with the code from https://github.com/filesender/filesender/pull/725 merged. While 725 does not explicitly help this case it does offer an ability to send logs from the account you are logged in as. Thus testing if the logs are being sent, or not being found. 

With 725 in place, clicking on the send logs button will also add a log that you clicked send log before sending the logs. So if there is nothing in the logs you will still see something when you search for your logs in the admin/users page.

For Edge this might also relate to https://github.com/filesender/filesender/issues/627 depending on how many of your users are on Edge or IE. Once 627 is addressed then that will help this issue too.

**Comment by belnet-ming** [comment]
Client logs uploading from Firefox (72.0.1), Chrome (79.0.3945.130), Chromium (79.0.3945.117), Microsoft Edge (44.18362.449.0) and IE (11.592.18362.0) is working.
And the table display is also fixed.

![image](https://user-images.githubusercontent.com/49909162/73257616-63ae8a80-41c4-11ea-9f0b-a99936f41a05.png)

**Comment by monkeyiq** [comment]
cool.
