### ISSUE TITLE
Downloads, pause and resume support?

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#714]
Hi we have some users with very large single file uploads in the range of 500GB+ file. Does FileSender support pause and resume downloads? If not could we? Users on a poor connections would benefit from this. maybe add support for HTTP range header?

**Comment by monkeyiq** [comment]
Pause and resume should work. If not then it is a bug and I am keen to fix things that relate to that functionality not working properly. IMHO upload with pause and resume is core functionality.

If you resume then you might loose the chunks that are in flight at the time and they will restart. This should only happen once as chunks that are already completed should not be lost. So if you resume 3 or 4 times you should only loose the partial chunks the first time and not keep loosing more data if you just resume a bunch of times real quick. In summary, you should only re-loose the same chunks over and over if you are clicking resume before chunks have a chance to complete.

This chunk loss might come into play on really poor connections if you keep failing to upload a single chunk over and over again and thus end up making no progress. Maybe for these connections we might look at being able to commit data more frequently than a filesender chunk (https://docs.filesender.org/v2.0/admin/configuration/#upload_chunk_size). Though that is also used directly by StorageFilesystemChunked as the chunk size to individually store. This might not be a problem as long as sysadmins are aware if we allow upload_chunk_size to vary in the future. Doing something with http ranges would allow finer grained resume without impacting other parts of the system.

Explicitly supporting connections that are poor enough to continually not allow 4-5mb chunks to complete is functionality that has room for improvement in the current code base.

**Comment by monkeyiq** [comment]
feel free to reopen this issue or create new specific ones if somebody experiences cases where resume is failing.
