### ISSUE TITLE
Remove Flash?

### ISSUE THREAD

**Issue by belnet-ming** [filesender/filesender#715]
As (Adobe) Flash is dead (?), removing it completely (in code and descriptions) is maybe best practice for Security concern?

**Comment by monkeyiq** [comment]
I am fairly sure that the current implementation doesn't use flash in any way. So removing references that are not referring to very old versions would be a good thing.

**Comment by monkeyiq** [comment]
There are some references in the translations too, mainly for help_text

**Comment by monkeyiq** [comment]
Hopefully I got most of these in 722 above. I left some references in there for the 1.6 codebase docs but trimmed them right back. The docs v2 installation no longer mentions it which is a big advantage to clarity.
