### ISSUE TITLE
Certificate expired, can't browse docs in Firefox

### ISSUE THREAD

**Issue by datakid** [filesender/filesender#744]
```
Websites prove their identity via certificates, which are valid for a set time period. The certificate for docs.filesender.org expired on 1/31/2020.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
 
View Certificate
```

![Screenshot from 2020-02-07 11-28-22](https://user-images.githubusercontent.com/97304/73990363-0a511300-499d-11ea-9b9d-aba2ed828ad8.png)

**Comment by meijer** [comment]
Thanks for reporting this and good to see our docs are being used. 

We are aware of the isssue with the SSL cetificate for docs.filesender.org and are in contact with our service provider to resolve this. 

Once the immediate issue is resolved, we'll investigate why the certificate was allowed to expire, as we have initiated its renewal several months ago. 

Cheers,
Jan Meijer

**Comment by monkeyiq** [comment]
For people bumping into this you can also access the docs directly from github, for example clicking index.md at https://github.com/filesender/filesender/tree/development/docs/v2.0/admin/configuration

While the links using docs.filesender.org don't work, each page from the menu is still available by navigating around the web interface to the code and the index.md seems to be rendered reasonably ok.

**Comment by janwout** [comment]
Does https://www.firefox.org got the same issue?

**Comment by monkeyiq** [comment]
docs.filesender.org seems to work ok now (tested in Chrome). However www.filesender.org seems like a different issue "This server could not prove that it is www.filesender.org; its security certificate is from www.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection."

**Comment by peter-** [comment]
> docs.filesender.org seems to work ok now (tested in Chrome). However [www.filesender.org](https://www.filesender.org) seems like a different issue

The TLS certificate currently used on https://www.filesender.org/ (IP: 145.100.190.10) is simply invalid (a self-signed bogus cert), probably a misconfiguration of the hosting server:

```
E = root@wordpress.surf.nl
CN = wordpress.surf.nl
OU = SomeOrganizationalUnit
O = SomeOrganization
L = SomeCity
ST = SomeState
C = --
```
Now, the TLS certificate on https://docs.filesender.org (IP: 145.101.124.5) is valid for both https://docs.filesender.org/ as well as https://filesender.org/ but is *not* being used for the SNI/name-based vhost at [https://**www**.filesender.org/](https://www.filesender.org/) -- and that cert doesn't have an entry (CN or X.509v3 SubjectAltName extension) for `www.filesender.org`, so couldn't be used there as is presently.

It would probably be best/easiest to renew the cert used at https://filesender.org/ to also include the `www.filesender.org` SubjectAltName **and** make `www.filesender.org` a `ServerAlias` in the vhost config for `filesender.org`, so both would be served by the same vhost. SURF would know all about that, of course.

**Comment by peter-** [comment]
ping @meijer

**Comment by meijer** [comment]
We were moving websites around 3 May which is probably why this self-signed certificate issue popped up. As far as I can see it's all fixed since about 3 June. Closed.
