### ISSUE TITLE
Feature: More "user friendly" error message

### ISSUE THREAD

**Issue by belnet-ming** [filesender/filesender#754]
A lot of users are asking what to do when they've got an error message like this:
![image](https://user-images.githubusercontent.com/49909162/75664244-73f9cf80-5c72-11ea-8e25-83132b893055.png)

Most of the time, the transfer has expired (or has been deleted by the uploader), but it is not explicitly said in the error message.

So, we should maybe change the error page to a generic "The transfer has expired and files have been deleted from our server." message instead of a "Recipient not found".

**Comment by madsi1m** [comment]
Change the word “server” to the product name eg “CloudStor FileSender” I think we have the name in the config somewhere

**Comment by monkeyiq** [comment]
This has been included in a release. Thanks for reporting the issue!
