### ISSUE TITLE
Decrypt download: Show password only when explicity indicated

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#757]
Currently, when a file is encrypted upon upload, while downloading the fileset, a password is requested for decryption. 

When using Firefox and Chrome, this password is displayed on-screen. 
This request is to make this behavior more aligned with current web practises: 
- Hide for the enduser
- Button to show the password
- Possibly only show the last entered character for a second

**Comment by monkeyiq** [comment]
It may be an interesting option for the user to be able to set "show passwords by default on this computer" in the my profile page. For example if the PC is located in the user's house and they are happy that the screen is private.

**Comment by monkeyiq** [comment]
Hide password has been released in 2.16.

**Comment by WebSpider** [comment]
Confirmed working, thanks
