### ISSUE TITLE
Cron Job Issue

### ISSUE THREAD

**Issue by redolphn** [filesender/filesender#773]
I keep getting the following error emailed to me every day when the FileSender cron job runs.  Any ideas?

/etc/cron.daily/filesender:
PHP Fatal error:  Uncaught Error: Class 'CollectionTree' not found in /opt/filesender/filesender/classes/data/File.class.php:400
Stack trace:
#0 /opt/filesender/filesender/classes/data/Transfer.class.php(807): File::fromTransfer(Object(Transfer))
#1 /opt/filesender/filesender/classes/data/AuditLog.class.php(350): Transfer->__get('files')
#2 /opt/filesender/filesender/classes/data/AuditLog.class.php(414): AuditLog::fromTransfer(Object(Transfer))
#3 /opt/filesender/filesender/classes/data/Transfer.class.php(521): AuditLog::clean(Object(Transfer))
#4 /opt/filesender/filesender/classes/data/DBObject.class.php(413): Transfer->beforeDelete()
#5 /opt/filesender/filesender/classes/data/Transfer.class.php(556): DBObject->delete()
#6 /opt/filesender/filesender/scripts/task/cron.php(65): Transfer->close(false)
#7 {main}
  thrown in /opt/filesender/filesender/classes/data/File.class.php on line 400
/etc/cron.daily/filesender: 3: /etc/cron.daily/filesender: EOF: not found
run-parts: /etc/cron.daily/filesender exited with return code 127

**Comment by redolphn** [comment]
@monkeyiq Any help/resolution on this issue?

**Comment by monkeyiq** [comment]
It seems the class loader is not finding the classes because there are many in one file. I have split them out and created https://github.com/filesender/filesender/pull/790. Please let me know if that resolves the issue for you.

**Comment by monkeyiq** [comment]
I put this in place so that the CI will now also run a cronjob and do a little verification
https://github.com/filesender/filesender/pull/798

**Comment by monkeyiq** [comment]
Hopefully the changes in 790 above have fixed the issue for you. The CI addition should help catch cron issues for everybody. If anyone wants to expand the cron CI testing please let me know.

If this issue is still happening for anyone please reopen.

**Comment by drudich** [comment]
@monkeyiq - not sure if this is related, but since upgrading FileSender, the error listed above seems to be fixed, but now I am seeing the following error emailed to me daily:

/etc/cron.daily/filesender:
/etc/cron.daily/filesender: 3: /etc/cron.daily/filesender: EOF: not found
run-parts: /etc/cron.daily/filesender exited with return code 127
