### ISSUE TITLE
Input of recipient not possible

### ISSUE THREAD

**Issue by baumrasen** [filesender/filesender#782]
With release 2.16 it is no more possible to input an recipient. So file sending is not possible. After the try for autocompletition there is a popup, that request authentication.

**Comment by monkeyiq** [comment]
Could you please try with https://github.com/filesender/filesender/pull/784
I will do a new release if 784 is confirmed to resolve the issue.

**Comment by baumrasen** [comment]
This solve the issue. Thanks!
