### ISSUE TITLE
{invalid_file_name} error when uploading file containing spaces in the filename

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#79]
I'm experiencing errors when trying to send a file containing spaces in the filename.
This happens with any file extension.

```
Screen Shot 2017-05-26 at 12.54.12.png : 144.3 kB
{invalid_file_name}
```
When I rename the file by removing the spaces no error will occur anymore.

btw, the follow default setting is active in the config:
  $config['ban_extension'] = 'exe,bat';

**Comment by bart-j** [comment]
This is due to the default $config['valid_filename_regex'] setting. One solution is to disable this regex with:

    $config['valid_filename_regex'] = '';

There is still another check in the Javascript library validating the filename, so I am not sure why there are two checks.

**Comment by monkeyiq** [comment]
the above pr should fix this issue
