### ISSUE TITLE
Send client logs: error in RestEndpointClientlogs.class.php

### ISSUE THREAD

**Issue by MariusUrkis** [filesender/filesender#811]
Clicking  "Send logs" button in My Profile page result in error:
A non-numeric value encountered in <b>/opt/filesender/filesender/classes/rest/endpoints/RestEndpointClientlogs.class.php</b> on line <b>123</b>

The issue is with if statement in function "put" line 123:
        if ($id & $id != '@me') {
Should be :
        if ($id && $id != '@me') {

**Comment by monkeyiq** [comment]
Tested before pr https://github.com/filesender/filesender/pull/814/files and got the issue as described. Tested with 814 and got a working upload of clientlogs. Also uploaded a new file and sent logs to double check that they arrived in database.

Thanks for the update and inline patch.

**Comment by monkeyiq** [comment]
This will be merged pending CI success.
