### ISSUE TITLE
Mac OS can't unarchive a generated zip package (after download all files as one zip)

### ISSUE THREAD

**Issue by gitsbit** [filesender/filesender#815]
The .zip failed, but Mac OS was able to unarchive the generated .tar package with the built in extractor.

![macos_error](https://user-images.githubusercontent.com/68217272/87302579-eb3d4b00-c511-11ea-89bf-de9b386b3e8f.png)
"error 2: no such file or directory."

Using eg. "Keka" on Mac OS was able to unarchive the .zip generated package (https://www.keka.io/en/)

greets
g.

**Comment by monkeyiq** [comment]
I just did a quick retest. The default FileSender install will suggest downloading the tar file by offering that button with a green highlight. There should also be a blurb above the download buttons mentioning that the zip file is in zip64 format which the native zip handling in macos can not handle and offering a link to an alternative unarchiver. Some FileSender installations customize their appearance so may have removed this information from display.

IMHO it is better to use zip64 all the time (even for smaller archives) to avoid users experiencing problems unarchiving when a zip file becomes large enough that it must be a zip64 format. It would be confusing and likely annoying for a user if most downloads work but a larger download is having problems.

**Comment by monkeyiq** [comment]
I am not sure what the update should be for this issue. I always hope that macos will implement zip64 in the platform at some stage but until that time people using osx will either need to use a third party unarchiver or download the tar file instead.
