### ISSUE TITLE
Cron Job Error

### ISSUE THREAD

**Issue by drudich** [filesender/filesender#842]
Seeing the following error every day when the FileSender cron job runs:

/etc/cron.daily/filesender:
/etc/cron.daily/filesender: 3: /etc/cron.daily/filesender: EOF: not found
run-parts: /etc/cron.daily/filesender exited with return code 127

**Comment by monkeyiq** [comment]
I think the line 3 of the /etc/cron.daily/filesender from the config-templates does not need to be there.

**Comment by monkeyiq** [comment]
Please reopen if there are still issues.
