### ISSUE TITLE
filesender.py breaks on dependency if not installed

### ISSUE THREAD

**Issue by flickerfly** [filesender/filesender#844]
The dependency on `requests` does not appear to be documented and when not installed keeps the script `filesender.py` from running. Requirements for installing should probably be documented somewhere or the script should catch the missing dependency and instruct the user to run `pip3 install requests`.

**Comment by monkeyiq** [comment]
Thanks for the report. I have added some detection in the script and also updated the docs to point to pip or distribution packages where it makes sense. Please reopen or add more issues if there are other things that could be improved.
