### ISSUE TITLE
Possibility to use external SMTP

### ISSUE THREAD

**Issue by imilos** [filesender/filesender#853]
Is it possible to use an external SMTP server for sending email notifications? If yes, how to configure it? I cannot find that feature in the official documentation.

**Comment by peter-** [comment]
Looking at [the code](https://github.com/filesender/filesender/blob/master-filesender-2.20/classes/utils/Mail.class.php#L572) it seems to simply call PHP's [mail](https://www.php.net/manual/en/function.mail.php) function and [its configuration](https://www.php.net/manual/en/mail.configuration.php) (i.e., `sendmail_path`) will likely apply.

FWIW, I've simply let FileSender and PHP do their thing and instead configure the local MTA to use a smarthost. Alternatively, a minimal SMTP server (or `sendmail_path` candidate, see PHP `mail` configuration above) that can do that is [msmtp](https://marlam.de/msmtp/), for example. That also allows use of TLS and ESMTPA features as needed.

**Comment by imilos** [comment]
@peter- many thanks for your help! It makes sense to do handle those things externally.

**Comment by tadela** [comment]
Hey, anyone could help me to config msmtp for filesender/simpleSAMLphp?
If i using cli i can send mail, works fine, but using app it doesn't send.
