### ISSUE TITLE
DB error while running upgrade

### ISSUE THREAD

**Issue by offgridengineering** [filesender/filesender#865]
#php /opt/filesender/filesender/scripts/upgrade/database.php
current db_database is filesender
PHP Fatal error:  Uncaught DBIConnexionException: failed_to_connect_to_database in /opt/filesender/filesender/classes/utils/DBI.class.php:196
Stack trace:
#0 /opt/filesender/filesender/classes/utils/DBI.class.php(245): DBI::connect()
#1 /opt/filesender/filesender/classes/utils/DatabaseMysql.class.php(48): DBI::__callStatic('prepare', Array)
#2 /opt/filesender/filesender/classes/utils/Database.class.php(59): DatabaseMysql::tableExists('Metadatas')
#3 /opt/filesender/filesender/classes/data/Metadata.class.php(103): Database::tableExists('Metadatas')
#4 /opt/filesender/filesender/scripts/upgrade/database.php(71): Metadata::getLatestUsedSchemaVersion()
#5 {main}
  thrown in /opt/filesender/filesender/classes/utils/DBI.class.php on line 196
[root@tr-filesender config]#

# php -v
PHP 7.3.11 (cli) (built: Oct 31 2019 08:30:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies

# uname -a
Linux tr-filesender 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)

# mysql -u filesender -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 9
Server version: 5.5.68-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| filesender         |
| test               |
+--------------------+
3 rows in set (0.00 sec)

MariaDB [(none)]> use filesender;
Database changed
MariaDB [filesender]> show tables;
Empty set (0.00 sec)
MariaDB [filesender]>

**Comment by monkeyiq** [comment]
Thank you for the detailed information. Is there anything in the last parts of the logs (probably in /opt/filesender/log/) which might give more of a hint?

Taking a look around on this system I have `php-mysqlnd-7.4.7-1.fc32.x86_64` installed which is what I suspect is providing my MariaDB access.

**Comment by offgridengineering** [comment]
Re-ran this morning and received something different:

]# php /opt/filesender/filesender/scripts/upgrade/database.php
current db_database is filesender
You currently have database major version 0
This execution will move also move to major version 22
Note that a major migration will only be needed when more advanced SQL is used to migrate

Look for table Metadatas
Table is missing, create it
running database update script on existing schema version 0
Removing views from database so base tables are free to change
database views will be added back later in this script
Checking class User
Removing views for table UserPreferences
Array
(
    [userpreferencesview] => Array
        (
            [mysql] => select * , DATEDIFF(now(),created) as created_days_ago   , transfer_preferences LIKE '%encryption":true%' as prefers_enceyption  , DATEDIFF(now(),last_activity) as last_activity_days_ago  , DATEDIFF(now(),aup_last_ticked_date) as aup_last_ticked_days_ago  , id as email_address  , id is not null as is_active   from UserPreferences
            [pgsql] => select * , extract(day from now() - created ) as created_days_ago   , transfer_preferences LIKE '%encryption":true%' as prefers_enceyption  , extract(day from now() - last_activity ) as last_activity_days_ago  , extract(day from now() - aup_last_ticked_date ) as aup_last_ticked_days_ago  , id as email_address  , id is not null as is_active   from UserPreferences
        )

    [userauthview] => Array
        (
            [mysql] => select up.id as id,authid,a.saml_user_identification_uid as user_id,up.last_activity,up.aup_ticked,up.created from UserPreferences up, Authentications a where up.authid = a.id
            [pgsql] => select up.id as id,authid,a.saml_user_identification_uid as user_id,up.last_activity,up.aup_ticked,up.created from UserPreferences up, Authentications a where up.authid = a.id
        )

)
Removing view for userpreferencesview
removing view userpreferencesview
Error, Rolling database changes back....
 This should leave the database state as it was before you started the script
Encountered exception : database_access_failure, see logs for details (uid: 5f90ad48ddcb3) ...\n[root@tr-filesender log]# ls -la
total 8
drwxr-x---.  2 apache apache   43 Oct 22 07:51 .
drwxr-xr-x. 22 apache apache 4096 Oct 19 14:12 ..
-rw-r--r--.  1 root   root   2379 Oct 22 07:51 filesender_2020-10-21_22h.log
[root@tr-filesender log]# cat filesender_2020-10-21_22h.log
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException exception uid:5f90ad48ddcb3] database_access_failure
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException trace uid:5f90ad48ddcb3] #0 /opt/filesender/filesender/classes/utils/DatabaseMysql.class.php(90): DBI::__callStatic('exec', Array)
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException trace uid:5f90ad48ddcb3] #1 /opt/filesender/filesender/classes/utils/DatabaseMysql.class.php(90): DBI::exec('DROP VIEW IF EX...')
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException trace uid:5f90ad48ddcb3] #2 [internal function]: DatabaseMysql::dropView('UserPreferences', 'userpreferences...')
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException trace uid:5f90ad48ddcb3] #3 /opt/filesender/filesender/classes/utils/Database.class.php(184): call_user_func('DatabaseMysql::...', 'UserPreferences', 'userpreferences...')
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException trace uid:5f90ad48ddcb3] #4 /opt/filesender/filesender/scripts/upgrade/database.php(391): Database::dropView('UserPreferences', 'userpreferences...')
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException trace uid:5f90ad48ddcb3] #5 {main}
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3] "SQLSTATE[42000]: Syntax error or access violation: 1142 DROP command denied to user 'filesender'@'localhost' for table 'userpreferencesview'"
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3] Array
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3] (
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3]     [name] => exec
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3]     [args] => Array
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3]         (
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3]             [0] => DROP VIEW IF EXISTS userpreferencesview
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3]         )
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3]
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3] )
[2020-10-21 22:51:04] [upgrade:error] [DBIUsageException details uid:5f90ad48ddcb3]
[root@tr-filesender log]#

I have not yet removed DROP priv...

**Comment by offgridengineering** [comment]
It did create 1 table this time?

MariaDB [(none)]> use filesender;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [filesender]> show tables;
+----------------------+
| Tables_in_filesender |
+----------------------+
| Metadatas            |
+----------------------+
1 row in set (0.00 sec)
MariaDB [filesender]>

**Comment by monkeyiq** [comment]
From the output it is failing on the DROP VIEW IF EXISTS. Since you still have the DROP permission granted it might be an idea to try to drop a non existing view from the command line:

```
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [filesender]> DROP VIEW IF EXISTS this_view_is_not_there;
Query OK, 0 rows affected, 1 warning (0.000 sec)
```

Also maybe from a mysql session using the `host` to connect to make sure it isn't something unix socket vs ip connection related.

**Comment by monkeyiq** [comment]
Please feel free to reopen the issue if it is still occurring for you.

**Comment by tadela** [comment]
hello, i also have problem:
php /opt/filesender/filesender/scripts/upgrade/database.php                                                                                                                                                       
current db_database is filesender
You currently have database major version 0
This execution will move also move to major version 22
Note that a major migration will only be needed when more advanced SQL is used to migrate

Look for table Metadatas
Table is missing, create it
running database update script on existing schema version 0 
Removing views from database so base tables are free to change
database views will be added back later in this script
Checking class User
Removing views for table UserPreferences
Array
(
    [userpreferencesview] => Array
        (
            [mysql] => select * , DATEDIFF(now(),created) as created_days_ago   , transfer_preferences LIKE '%encryption":true%' as prefers_enceyption  , DATEDIFF(now(),last_activity) as last_activity_days_ago  , DATEDIFF(now(),aup_last_ticked_date) as aup_last_ticked_days_ago  , DATEDIFF(now(),service_aup_accepted_time) as service_aup_accepted_time_days_ago  , id as email_address  , id is not null as is_active   from UserPreferences
            [pgsql] => select * , extract(day from now() - created ) as created_days_ago   , transfer_preferences LIKE '%encryption":true%' as prefers_enceyption  , extract(day from now() - last_activity ) as last_activity_days_ago  , extract(day from now() - aup_last_ticked_date ) as aup_last_ticked_days_ago  , extract(day from now() - service_aup_accepted_time ) as service_aup_accepted_time_days_ago  , id as email_address  , id is not null as is_active   from UserPreferences
        )

    [userauthview] => Array
        (
            [mysql] => select up.id as id,authid,a.saml_user_identification_uid as user_id,up.last_activity,up.aup_ticked,up.created from UserPreferences up, Authentications a where up.authid = a.id 
            [pgsql] => select up.id as id,authid,a.saml_user_identification_uid as user_id,up.last_activity,up.aup_ticked,up.created from UserPreferences up, Authentications a where up.authid = a.id 
        )

)
Removing view for userpreferencesview
removing view userpreferencesview 
Error, Rolling database changes back....
 As this script changes schema items rollback is less useful on MariaDB
    " MariaDB (...) supports rollback of SQL-data change statements, but not of SQL-Schema statements."  
    --  https://mariadb.com/kb/en/rollback/ 

you should either get a full run of this script or compare the output to a backup
Encountered exception : database_access_failure, see logs for details (uid: 61f937ac9ad1c) ...\n

**PHP -V**
php -v                                                                                                                                                                                                            
PHP 7.0.33-57+0~20211119.61+debian10~1.gbp5d8ba5 (cli) (built: Nov 19 2021 06:43:51) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-57+0~20211119.61+debian10~1.gbp5d8ba5, Copyright (c) 1999-2017, by Zend Technologies

**mariadb --version**
mariadb --version                                                                                                                                                                                                 
mariadb  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**cat /etc/*-release**
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by monkeyiq** [comment]
Is there anything interesting in your `/opt/filesender/log` directory for the cited id `61f937ac9ad1c`.

Other than that if you connect to the mariadb server with the same credentials can you create and drop a simple view?
