### ISSUE TITLE
Programmatically download files given a token

### ISSUE THREAD

**Issue by nbenn** [filesender/filesender#869]
First, this is more of a question than an issue report or a feature request. Also, I'm not familiar with filesender but only have had a quick look at the REST API docs, so please excuse ignorance on my side.

Given nothing but a token as in an URL such as

```
https://filesender.org/?s=download&token=0c27af59-72d1-0349-aa59-00000a8076d9
```

Is it possible to programmatically (for example via the REST API)

1. list corresponding files/file names/file sized
1. list corresponding download URLs

**Comment by WebSpider** [comment]
Please check out the filesender REST documentation

https://docs.filesender.org/filesender/v2.0/rest/
