### ISSUE TITLE
FileSender requires a 64-bit PHP installation to work

### ISSUE THREAD

**Issue by Indigo744** [filesender/filesender#870]
Hello

When I try to run FileSender, I get the following error message:
```
FileSender requires a 64-bit PHP installation to work. Please contact your administrator.
```

While it is a pretty straightforward error message, I couldn't find a reference of this requirement anywhere, nor an explanation on why it is needed.

Thank you.

**Comment by monkeyiq** [comment]
It seems that this error message was added to the code in 2014. I'd have to dig a little more to see what requires this.

**Comment by thijskh** [comment]
I believe this has to do with being able to support large files > 2 GB

**Comment by Indigo744** [comment]
It makes sense of course. But why making it mandatory?

**Comment by thijskh** [comment]
I guess because the whole idea of Filesender is that it sends large files, not small files

**Comment by monkeyiq** [comment]
While it is still unsupported, if you are keen you could try removing the line in includes/init.php that forbids it and see if things work for you. 

That 2014 reference I saw above from git is the import from subversion so I would have to dig into the archives more to see why and when it was made mandatory. 

I suspect that there is something that doesn't work as expected and it is easier to force 64 bit than try to run CI over 32 and 64 bit configurations.

**Comment by Indigo744** [comment]
Well I'm not fond of modifying source files as it makes upgrading complicated.

I'll close this issue and see if I can just find a 64-bit PHP version.

Thanks!

**Comment by Phaze-III** [comment]
@monkeyiq 
> That 2014 reference I saw above from git is the import from subversion so I would have to dig into the archives more to see why and when it was made mandatory.

The actual commit introducing the check was 03e03c919db7fd7c4ba4500026f9af741739dc13

It references ticket 977 in Assembla. Based on a backup of the raw data of the Assembla data:

```
2013-08-14 14:52 | #977: Add check for 64-bit PHP installation     created by       vpolden
Credit to Jan for pointing this one out:  A 64-bit version of PHP is required for much of FileSender to work  properly, but this is not currently being checked anywhere in the code.  An error message (similar to what happens if config.php is not found) should be generated if the PHP installation is found to be 32-bit aware only. See http://stackoverflow.com/a/6304354 for one possible way to perform such a check.

2013-08-14 14:54 | #977: Add check for 64-bit PHP installation     commented by       Jan Meijer
I think it was Xander who mentioned it during the last all-hands meeting ;)

2013-08-15 15:48 | #977: Add check for 64-bit PHP installation     set to test by       vpolden
Assigned to changed from None  to vpolden
Status changed from New  to Test         (In file_sender:2528) Test #977: Check for 64-bit PHP.
```
So in part, mea culpa...
