### ISSUE TITLE
Allow (admins) to push expiration date

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#875]
It would be helpful if at least admins could extend the validity of existing transfers, i.e., push the expiration date into the future.

That would allow support personnel to aid users of the system who would otherwise (for whatever reasons, e.g. the recipients having been unavailable for a period longer than the chosen expiration date; or simply because the expiration date was set too short when creating the transfer by mistake) be forced to re-upload the same data set again, only in order to change/extend the validity period.

For large data sets uploading files from the browser is a very tasking process (less so with the CLI client but that's not universally user-friendly the way the web UI is), we shouldn't force this on users more often thatn stricly necessary only because there's no "+1 week" button (or whatever) to extend the validity of files already sitting around on the FileSender server.

I could even imagine some sites allowing end users to do that themselfs, though a limit would have to be enforced at some point, either by limiting the number of times the date can be extended, or the number of days, or both. (E.g. days × times must be less than 10, or whatever.)

**Comment by adminnr1** [comment]
Hi Peter,

I understand you usecase, but I don't see the added value. This moves
filesender more to a storage solution for end users in stead of a
'sending' solution. If you want files to be longer available share them
via your organisations cloud storage solution via a link.
We see Filesender as a short term 'storage' / 'sending' solution, for
longer availability for data we have a different solution (based on
owncloud).

Met vriendelijke groet, Kind regards,

William van Santen

Product Manager Cloud Services | SURF | william.vansanten@surf.nl | T
+31 (0)88 787 30 00 | Absent on Wednesday | LinkedIn
<http://www.linkedin.com/in/williamvansanten>

SURF <https://surf.nl/> is de ICT-coöperatie van onderwijs en onderzoek
in Nederland
SURF <https://surf.nl/en> is the collaborative organisation for ICT in
Dutch education and research


Op 18-11-2020 om 12:23 schreef peter:

**Comment by peter-** [comment]
> Hi Peter, I understand you usecase, but I don't see the added value.

No offence but then you don't understand the use-case. ;)  

Person A painfully manages to upload a 250 GB data set to filesender, possibly from her home (due to the lockdown; or because s/he's not comfortable using the CLI client), over a slow connection. The intended recipient B is being notified but it turns out person B is on vacation just at that moment. The upload expires and person A has to repeat the upload only to enable person B to access the files 2 days after the original upload had expired. Why re-transfer the payload when you only need to change the metadata?

Slightly less hypothetical (though there's nothing hypothetical about people being unavailable and others not knowing about it in advance): Person C manages to upload a large data set to filesender but missed/forgot to extend the expiration date: Our system defaults to a rather short expiration time (`default_transfer_days_valid`) -- precisely because we know what FileSender is meant for -- but still allows for longer validty (`max_transfer_days_valid`) *IF* chosen *when creating a new transfer*. The upload takes hours (or days) but once she realises the short validity s/he can't fix the transfer *meta data* except by deleting the actual payload from the server again and re-uploading it.

That's just silly, IMO.

And not even allowing the admin (who can be assumed to know that FileSender is meant for only transitory storage, even if you don't extend that assumption to ordinary users of the system) to change the metadata after the fact is adding insult to injury. It pains me as service provider having to tell people to upload their data set *again* simply because we don't like to manually mess with the metadata in the database itself.

> This moves filesender more to a storage solution for end users in stead of a 'sending' solution. If you want files to be longer available share them via your organisations cloud storage solution via a link. 

FWIW, If *all* institutions in our community where known to be runing nextCloud/ownCloud or similar systems I probably wouldn't even be running a FileSender instance. Those all have "share file externally via a link" functionality plus advanced file transfer capabilities (delta transfers), among other things.

**Comment by monkeyiq** [comment]
My personal view is that it seems reasonable to allow an admin to extend the date on a transfer. If this is admin only to start it only really effects sites which may wish to push back the expire date.

**Comment by monkeyiq** [comment]
The system has a similar feature already in the "allow_transfer_expiry_date_extension" option. Though this option allows users the ability to extend the expire time for a transfer one or more times. The one or more is done via the configuration for example using an array( 30, 90 ) would allow a first extension of 30 days and a second of 90 more days and then no more extensions for that transfer. There is the option of array( 30, 90, true ) which allows infinite 90 day extensions. While this open ended extension policy might not be what one wants for a user the same sort of configuration can be useful for an admin only version. As the admin can likely connect to the database they can already do infinite extensions but having to fiddle around with SQL.

I think I will add a configuration option "allow_transfer_expiry_date_extension_admin" which will work in a manner similar to "allow_transfer_expiry_date_extension" but only be available and used if you have admin privileges. If the default is off then adding this feature will not change how things work at the moment, if you want it it should be a single line to turn on. This will allow an admin to easily bless one of their or another users transfer to remain in the system for longer. With the `true` as the last array element there should be no restriction on the admin for the number of extensions they can offer.

**Comment by monkeyiq** [comment]
896 above provides a new allow_transfer_expiry_date_extension_admin option to allow admin the ability to extend transfer expire time in a similar way that allow_transfer_expiry_date_extension (if enabled) already allowed regular users to do this.

**Comment by peter-** [comment]
Thanks a lot, @monkeyiq, also for the reminder that `allow_transfer_expiry_date_extension` already existed (even if we currently don't intend to enable that).

Now that `allow_transfer_expiry_date_extension_admin` landed in 2.21 _of course_ we got a request to extend the validity of issued **guest vouchers**, which are currently unaffected by this setting. Would it make sense to extend the meaning of this policy setting to cover invitations as well? Or would you rather have another set of config setting for deviating policies?

Either way, I think extending the validity of vouchers is even less contentious since they take up no space on the server while not in use, contrary to ever extended transfers.  
Depending on how you'd like to implement this I'd open another issue or ask you to re-open this one.

**Comment by monkeyiq** [comment]
I have made a new issue at https://github.com/filesender/filesender/issues/966 for the guest extensions. I thought of another idea where specific users can have extended defaults which might apply to this expires too, it would not be too out of place for a professor to want a little longer by default until their transfers expire.
