### ISSUE TITLE
New interface?

### ISSUE THREAD

**Issue by helmut72** [filesender/filesender#881]
23-03-2020
https://filesender.org/filesenders-brand-new-website-and-style/

"With a new website, comes a new FileSender interface. Stay tuned because we are almost ready to launch a new FileSender version soon."

Is there any timeframe for a new (hopefully) easier interface? I don't know Filesender until 1 week and thought, Filesender interface looks like in the frontpage of filetransfer.org.

Thank you

**Comment by peter-** [comment]
FWIW, you can watch things progress in #832

**Comment by helmut72** [comment]
Thanks! I have overseen the other issue. Will close this.

**Comment by monkeyiq** [comment]
The primariy boostrap UI development is now happening in https://github.com/filesender/filesender/tree/2021/bootstrap

**Comment by monkeyiq** [comment]
Feel free to check that branch (based on 2.22) out and have a look at it and report any issues you may have.
