### ISSUE TITLE
option for a guest ticket link

### ISSUE THREAD

**Issue by helmut72** [filesender/filesender#883]
It looks like it's only possible to send guest invitations via mail from Filesender webinterface. This a new mail. But sometimes it's required to answer exactly to the mail flow from an external company for ongoing support.

There should be an option getting just a guest link to send it with users default mail app.

Thank you.

**Comment by peter-** [comment]
Duplicate of #592

**Comment by helmut72** [comment]
Thanks! I have overseen the other issue. Will close this.
