### ISSUE TITLE
Improve admins' ability to find transfers

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#888]
Providing support for a FileSender instance is currently being made difficult because
* `Admin` -> `Transfers` cannot be searched by sender email (only by min/max transfer id numbers),  
even though once you find and expand ("Show details") a transfer you can clearly see the sender email address,
* under `Admin` -> `Users` -> `Search for user (based on user ID)` you can only search for the (federated, in our case) userid but not for the sender email address (which may not be the same thing, depending on deployment details and configuration).

E.g. we're getting support requests from email address X but I can't search for transfers from that sender in the transfers page, nor can I search for that email adress in `Search for user (based on user ID)` (when the IDP has sent a different userid as SAML attribute).

In our current setup (using the Shibboleth SP) we'd have to perform the following steps to find the transfers for a given person (known only by email at that time):
* Ask the person for an specific transfer id/number (or for their userid, which not only sounds phishy, the subject also has no idea what identifier the IDP and the SP agreed on using to identify the subject with, i.e., the subject may not even know their own userid as far as what FileSender persistend for them. Also FileSender does not display it anywhere within the UI -- not that asking the subject to read their own userid off a web site and tell it to the support sounds like a very elegant way to provide support).
* Then try to find the transfer id in the web server access logs (`fgrep /transfer/12345 /path/to/access.log`) where we'll find the userid of the subject that's being passed to FileSender from the web server (because we've configured the Shib SP to set `REMOTE_USER` from selected SAML attributes and httpd writes out `REMOTE_USER` into the access logs, next to `REMOTE_ADDR`.).
* Then head back to FileSender's admin UI and `Search for user (based on user ID)`, now that we know the userid.

That seems (needlessly) cumbersome, to say the least.

**Comment by peter-** [comment]
That's the kind of thing [you](@monkeyiq ) were looking for in https://github.com/filesender/filesender/issues/747#issuecomment-647286751, I guess.

**Comment by monkeyiq** [comment]
I will take a look at adding search for sender email to the admin/transfers page shortly. The "Show details" page is using the column transfers.user_email from the database as the sender email so I think if we can find transfers based on that then it might help this admin situation. To assist for larger databases we might like to add a secondary index for the transfers.user_email column which would make this search for exact match very quick.

**Comment by monkeyiq** [comment]
Feel free to reopen if there is still an issue.
