### ISSUE TITLE
Option to enforce usage of cryptographically strong passwords

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#902]
At current, all passwords, as long as they meet ```encryption_min_password_length``` are valid.

This is a feature request to add an option to enforce the usage of strong passwords, to mitigate password brute-forcing attacks.

Criteria for a strong password could exist of:
- A minimal length (currently implemented)
- Enforced usage of capital/non-capital letters
- Enforced usage of numbers
- Enforced usage of special characters (ie !=,*&$)

**Comment by adminnr1** [comment]
+1 awesome idea!

**Comment by monkeyiq** [comment]
There is plenty of scope to extend this out to having other specific cases but the above gives a good start relative to the limited constraints (length) that was there already. I think extensions to what was added in 942 could be done by raising new issues or as PRs as desired.
