### ISSUE TITLE
Incorrect download counter

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#908]
Hi,

We've seen some unextected behaviour with regards to download counters in 2.15 and 2.18: 
It appears anonymous downloads of the same single file are only registered if they are from a different IP address. 

Since more and more users end up coming from the same IPv4 address, this is becoming an issue to endusers, who may use the download counter to see if the file has been received.

One possible explanation is the use of the IP in https://github.com/filesender/filesender/blob/d7909eacd7ad9cec850a604bd7bf582cfda79bc4/classes/data/AuditLog.class.php#L552, but since I am uncertain I am opening as an issue, instead of providing a fix.

**Comment by monkeyiq** [comment]
This is interesting, it seems to have been added about 5 years ago to prevent some download tools from triggering file downloaded events multiple times in quick succession. The initial impression then is that maybe removing the bandaid will present the initial issue. Though perhaps we should then look at handling the issue in the cron job side as a prescan for excessive activity from a single IP.

**Comment by WebSpider** [comment]
/tag bug
If it's called a download counter, it should count downloads :-)

**Comment by adminnr1** [comment]
Hi, yes, I see this as a bug too. Our users complain about this (and don't get it).
Is there an update on this issue?

**Comment by adminnr1** [comment]
Hi! Can you please give an update on this?

**Comment by ekrister** [comment]
I also ran into this while testing this software. Seems odd that it really doesn't count the downloads. Is there any way to fix this?

**Comment by monkeyiq** [comment]
I will be taking a look at this now. First move is to disable the IP address check. If there are clogs in the logs because of that it might be best to work out how to make that part of the system more robust as a follow on.

**Comment by WebSpider** [comment]
This is confirmed fixed!
