### ISSUE TITLE
Filename containing multi-byte character(s) is shorten incorrectly

### ISSUE THREAD

**Issue by hironobu-nagaya** [filesender/filesender#916]
Hi,

Sometimes, shorten file name(s) on transfer table becomes empty.
I noticed it occurs only when filename contains multi-byte character(s).
I traced code and I thought that multi-byte character(s) was not included in the consideration.

https://github.com/filesender/filesender/blob/7877cfb5dfa4adb3fb6017edcd06e042731e1206/templates/transfers_table.php#L245-L261

Here is script to check on Bash.

```
$ php << 'EOF'
<?php
// prepare dummy values.
class Lang
{
  public static function tr() {
    return 'See all';
  }
}
$file = new class{};
$file->path = "マルチバイト文字を含むファイル名.txt";
$transfer = new class{};
$transfer->downloads = [];

// FileSender 2.21 - templates/transfers_table.php - line 248-253
// BEGIN
$name = $file->path;
$name_shorten_by = (int) (strlen((string) count($transfer->downloads))+strlen(Lang::tr('see_all'))+3)/2;
    if(strlen($name) > 28-$name_shorten_by) {
        if(count($transfer->downloads)) $name = substr($name, 0, 23-$name_shorten_by).'...';
        else $name = substr($name, 0, 23).'...';
}
// END

echo $name . "\n";
echo htmlentities($name, ENT_QUOTES, 'UTF-8') . "\n"; // same as `Template::sanitizeOutput($name)`
?>
EOF
```

( "マルチバイト文字を含むファイル名" means "filename which contains multi-byte characters(s)" in Japanese )

And it outputs,

```
マルチバイト文...

```
( line 2 is empty )

Environment
-------------

* CentOS 7
* PHP 7.4 ( from [Remi's RPM repository](https://rpms.remirepo.net/) )

```
$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```

```
$ php -v
PHP 7.4.14 (cli) (built: Jan  5 2021 10:45:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

----

I feel sorry I am not good English speaker, and have little knowledge of PHP.
Furthermore, this is first time to submit issue to open source project.

Thank you.

**Comment by monkeyiq** [comment]
Thank you for this detailed bug report! I encourage you to report other issues you find. Having current and expected behaviour in the report (and in this case a small test that I could use to verify my update) makes for a very good report. It is always nice as a developer to verify that things have changed to what is expected when testing locally.

I have an update in https://github.com/filesender/filesender/pull/919 which I will soon merge. I found another location which might present similar issues and have updated for that too (invited guests listing).

Once I merge 919 I will likely mark this as resolved, feel free to reopen the issue if you find cases where the update is not sufficient.

**Comment by monkeyiq** [comment]
I also just tested 919 using the filename twice "マルチバイト文字を含むファイル名マルチバイト文字を含むファイル名.txt" as the mb_strlen was not wanting to shorten the original file name any more. The shortened version of the above repeated filename presents ok in the transfers list when 919  is in place. PR 919 is now merged in development & will be part of the next release.

**Comment by hironobu-nagaya** [comment]
Thank you for your fast response and code fix!
Your polite comments got rid of my hesitation to submit issue.
I will refer your advices when I will submit issue next time.                                                                                                                                                                                  

I checked #919 and I have no problem to close this issue.
Thank you very much!
