### ISSUE TITLE
data protection: disable / expire cached email addresses

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#917]
As discussed [on the list](https://sympa.uninett.no/lists/filesender.org/arc/filesender-dev/2021-02/msg00008.html) it makes sense to allow to *optionally*:
* disable caching of entered email addresses,
* automatically have entered email addresses expired after some (possibly configurable) period  
  (which avoids having to rely on the subjects themselfs to [clean out that data](https://github.com/filesender/filesender/pull/913))

The former would prevent email addresses from being stored ("cached") outside of transfers completely, obviating the need to expire them afterwards.

The latter would keep the "caching" functionality around but would make sure the data is not kept longer than reasonable (certainly not forever), e.g. some grace period after having been entered or after any transfers it was used for have expired.

Clearly both options have negative consequences on the "user-friendliness" of the system and so would have to be made optional -- for those few deployers where data protection issues simply do not exist (however unlikely that may be today).

(Personally I have no intention of making the (mis-)use of FileSender as a "poor man's webmail" system easier: Instead people should be using `get_a_link` and then share that link using their own Mail User Agent which already provides a real address book with all their contacts in it, automatic adding of new recipients, a `Sent` folder where they can easily find when files were shared with whom, etc. but YMMV, of course.)

**Comment by monkeyiq** [comment]
I have made the above pr 922 that disables the frequent emails.

As the frequent emails are stored in json it makes some extra processing in the cron job to expire them. If the oldest mtime was stored in a separate column (indexed) then maybe such processing would not bog down the cron job too much. I thought I would add the disable option first and can look at an expire option as a later update.

**Comment by monkeyiq** [comment]
If anyone wishes to enable this they might also like to do the following to wipe out the existing entries. They will be removed for a user once they attempt to add to the frequent_recipients as well.
```
update UserPreferences set frequent_recipients = '[]';
```

**Comment by monkeyiq** [comment]
I guess the remaining part of this issue is to have an expiration time on frequent recipients as another option.

**Comment by WebSpider** [comment]
Closing this issue and adressing the remaining in #1548
