### ISSUE TITLE
Service level AuP support

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#927]
File sender offers and AuP when uploading a file and when obtaining the web api secret. Some sites already wrap an offering of FileSender with a service level AuP which applies to FileSender and other software that the site is offering.

I think FileSender itself should allow a service AuP which a user must accept. This would allow a site to be configured to not need an AuP for each upload as a user has accepted a service AuP and is authenticated. As previously mentioned in discussions it would be good for this service AuP to support versioning to allow the admin to update the AuP and have it presented to the user again for reacceptance. This is a cleaner solution than many AuPs which state that they "may change from time to time". When the AuP changes I think both users of the site and the admins would both like to know about it and be happy to accept and know of explicit acceptance of the new terms.

**Comment by adminnr1** [comment]
Hi, we very much like this, is there an ETA for this?

**Comment by monkeyiq** [comment]
I will do another round of testing for this (1128 merged) in the next few days

**Comment by monkeyiq** [comment]
This was merged Aug 2021 and has been in releases for a while now.
