### ISSUE TITLE
Docker images created by some script from the github release or a branch / pull request.

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#929]
It would be nice to build docker images for pull requests, or branches and pull requests. Either automatically or via a script. Maybe we could have two images so you could attach them to either MariaDB or PostgreSQL depending on what you like to run as your db.

Github actions allows artefacts to be created as part of CI but I am not sure if we would run into space constraints if we did this action there. Maybe if it was done as part of the CI run the docker image could be pushed to some external storage that allows public downloads.

**Comment by WebSpider** [comment]
I have this setup already, but semi-automated. Integration into CI is a small step. 
Currently a simple buildscript to build the image, and upload the resulting images to my private image repository and dockerhub.

**Comment by WebSpider** [comment]
Various other projects create docker images per PR, as a way to do QA testing on the images.
These images are typically shorter lived than images related to a tag/release.

One of the platforms you can use to publish docker images is dockerhub, who provide nice infrastructure for open source projects.

**Comment by monkeyiq** [comment]
I guess if we want to do this in the CI itself and upload to dockerhub then we might need to put it into something like a savage run to protect the dockerhub secrets from sniffing through a PR.

**Comment by monkeyiq** [comment]
I would love to take a look at your docker scripts assuming there is nothing secret in there. Feel free to PR or send by private email. Also if you are happy for something to be merged into the main filesender repo under scripts/docker for example I would be glad to base those scripts on what you have.

**Comment by WebSpider** [comment]
> I guess if we want to do this in the CI itself and upload to dockerhub then we might need to put it into something like a savage run to protect the dockerhub secrets from sniffing through a PR.

This is quite well handled within GitHub workflow secrets and environments. 
I will prepare a PR for the Docker build and corresponding CI. Without the proper secrets added in the repo or organisation this will obviously fail.

If needed/wanted I can help implementing this as well in the GitHub and Dockerhub filesender organisation, given sufficient permissions
