### ISSUE TITLE
Cron deleting data from the auditlogs table

### ISSUE THREAD

**Issue by jonhan7** [filesender/filesender#932]
I am responsible for the Filesender service at RNP - National Education and Research Network, we provide the Filesender service so that universities in Brazil can take advantage of this fantastic service.

We have been trying to resolve the following issue since October 2020.

The cron.php script is used to delete expired files, the problem is that it is deleting the records from the auditlogs table, we use about 80% of the information in this table to generate our reports. The Rnp operation team is concerned with changing the script code and affecting the service's operation and not being able to return.

I come to ask for help from the community to solve this problem without having any impact.

**Comment by monkeyiq** [comment]
Hi, 

  If you have a high enough value for [auditlog_lifetime](https://docs.filesender.org/v2.0/admin/configuration/#auditlog_lifetime) and the cron script is deleting auditlogs that are less than that many days old then it is a bug and we should look to fix it. 

  If the RNP operations team has located a specific part of the script code that you would like changed to provide the outcome you are after please let me know and I will take a look as to why that code is not respecting auditlog_lifetime and how to update it.

**Comment by jonhan7** [comment]
We did an analysis in the filesender and the auditlog_lifetime variable had been deleted, we implemented it and the problem was solved, monkeyiq, thank you very much for your contribution, with your help we were able to solve a problem of approximately 4 months.

**Comment by monkeyiq** [comment]
I am glad things are able to be configured in a way that works for your setup! If you run into other issues please raise another issue on github or drop the mailing list a line. If something is important to your deployment it is likely to be something that either has or will effect others as well.
