### ISSUE TITLE
I didn't find in the documentation

### ISSUE THREAD

**Issue by lexxmatos** [filesender/filesender#957]
Is there any kind of file not supported in Filesender?

**Comment by madsi1m** [comment]
look at these options in the config.php

$config['ban_extension']
$config['valid_filename_regex']
$config['extension_whitelist_regex']

**Comment by WebSpider** [comment]
@lexxmatos does that answer your question ?

**Comment by lexxmatos** [comment]
Yes, thank you!



Em ter., 23 de mar. de 2021 às 10:31, WebSpider ***@***.***>
escreveu:
