### ISSUE TITLE
Generated password feature does not respect encryption directive.

### ISSUE THREAD

**Issue by michaellegal** [filesender/filesender#999]
Hi, I have that kind of config directives and it seems the generate password feature does not respect the values:

$config['encryption_mandatory'] = true;
$config['encryption_min_password_length'] = '12';
$config['encryption_password_must_have_upper_and_lower_case'] = true;
$config['encryption_password_must_have_numbers'] = true;
$config['encryption_password_must_have_special_characters'] = false;
$config['encryption_generated_password_length'] = 12;
$config['encryption_generated_password_encoding'] = 'base64';

The generated password button still offer something like that: PZPP59uA86FAxMTDisgk2VeO+5FlhmIVEbQjDrxQWaM=

Best regards,

Michael LE GAL

**Comment by monkeyiq** [comment]
Thank you for raising this issue, Some of the documentation is stale. I will update the documentation soon to reflect why this behaviour happens. 

The FileSender project is lucky enough to have input from a professional cryptographer. In line with their suggestions generated passwords are made based on how much entropy is desired for good crypto. Those random bytes are then put into a format that can be displayed as text and presented as the generated password. The goal is to make the generated password as secure as we can for file encryption. Many of the encryption configuration directives such as password_must_have_numbers do not apply to generated passwords. I will update the documentation to outline which options have no effect for generated passwords.

**Comment by monkeyiq** [comment]
I have updated the docs to deprecate encryption_generated_password_length in https://github.com/filesender/filesender/pull/1068.

For now you could set encryption_random_password_version_new_files=1 to use encryption_generated_password_length. However it is highly recommended to retain the system default for generated password length.
